from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Button(_BaseLayoutHierarchyType):
    @property
    def count(self): ...
    @count.setter
    def count(self, val) -> None: ...
    @property
    def label(self): ...
    @label.setter
    def label(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def step(self): ...
    @step.setter
    def step(self, val) -> None: ...
    @property
    def stepmode(self): ...
    @stepmode.setter
    def stepmode(self, val) -> None: ...
    @property
    def templateitemname(self): ...
    @templateitemname.setter
    def templateitemname(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        count: Any | None = ...,
        label: Any | None = ...,
        name: Any | None = ...,
        step: Any | None = ...,
        stepmode: Any | None = ...,
        templateitemname: Any | None = ...,
        visible: Any | None = ...,
        **kwargs
    ) -> None: ...
