from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Realaxis(_BaseLayoutHierarchyType):
    @property
    def color(self): ...
    @color.setter
    def color(self, val) -> None: ...
    @property
    def gridcolor(self): ...
    @gridcolor.setter
    def gridcolor(self, val) -> None: ...
    @property
    def griddash(self): ...
    @griddash.setter
    def griddash(self, val) -> None: ...
    @property
    def gridwidth(self): ...
    @gridwidth.setter
    def gridwidth(self, val) -> None: ...
    @property
    def hoverformat(self): ...
    @hoverformat.setter
    def hoverformat(self, val) -> None: ...
    @property
    def labelalias(self): ...
    @labelalias.setter
    def labelalias(self, val) -> None: ...
    @property
    def layer(self): ...
    @layer.setter
    def layer(self, val) -> None: ...
    @property
    def linecolor(self): ...
    @linecolor.setter
    def linecolor(self, val) -> None: ...
    @property
    def linewidth(self): ...
    @linewidth.setter
    def linewidth(self, val) -> None: ...
    @property
    def showgrid(self): ...
    @showgrid.setter
    def showgrid(self, val) -> None: ...
    @property
    def showline(self): ...
    @showline.setter
    def showline(self, val) -> None: ...
    @property
    def showticklabels(self): ...
    @showticklabels.setter
    def showticklabels(self, val) -> None: ...
    @property
    def showtickprefix(self): ...
    @showtickprefix.setter
    def showtickprefix(self, val) -> None: ...
    @property
    def showticksuffix(self): ...
    @showticksuffix.setter
    def showticksuffix(self, val) -> None: ...
    @property
    def side(self): ...
    @side.setter
    def side(self, val) -> None: ...
    @property
    def tickangle(self): ...
    @tickangle.setter
    def tickangle(self, val) -> None: ...
    @property
    def tickcolor(self): ...
    @tickcolor.setter
    def tickcolor(self, val) -> None: ...
    @property
    def tickfont(self): ...
    @tickfont.setter
    def tickfont(self, val) -> None: ...
    @property
    def tickformat(self): ...
    @tickformat.setter
    def tickformat(self, val) -> None: ...
    @property
    def ticklen(self): ...
    @ticklen.setter
    def ticklen(self, val) -> None: ...
    @property
    def tickprefix(self): ...
    @tickprefix.setter
    def tickprefix(self, val) -> None: ...
    @property
    def ticks(self): ...
    @ticks.setter
    def ticks(self, val) -> None: ...
    @property
    def ticksuffix(self): ...
    @ticksuffix.setter
    def ticksuffix(self, val) -> None: ...
    @property
    def tickvals(self): ...
    @tickvals.setter
    def tickvals(self, val) -> None: ...
    @property
    def tickvalssrc(self): ...
    @tickvalssrc.setter
    def tickvalssrc(self, val) -> None: ...
    @property
    def tickwidth(self): ...
    @tickwidth.setter
    def tickwidth(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        color: Any | None = ...,
        gridcolor: Any | None = ...,
        griddash: Any | None = ...,
        gridwidth: Any | None = ...,
        hoverformat: Any | None = ...,
        labelalias: Any | None = ...,
        layer: Any | None = ...,
        linecolor: Any | None = ...,
        linewidth: Any | None = ...,
        showgrid: Any | None = ...,
        showline: Any | None = ...,
        showticklabels: Any | None = ...,
        showtickprefix: Any | None = ...,
        showticksuffix: Any | None = ...,
        side: Any | None = ...,
        tickangle: Any | None = ...,
        tickcolor: Any | None = ...,
        tickfont: Any | None = ...,
        tickformat: Any | None = ...,
        ticklen: Any | None = ...,
        tickprefix: Any | None = ...,
        ticks: Any | None = ...,
        ticksuffix: Any | None = ...,
        tickvals: Any | None = ...,
        tickvalssrc: Any | None = ...,
        tickwidth: Any | None = ...,
        visible: Any | None = ...,
        **kwargs
    ) -> None: ...
