from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Marker(_BaseTraceHierarchyType):
    @property
    def angle(self): ...
    @angle.setter
    def angle(self, val) -> None: ...
    @property
    def color(self): ...
    @color.setter
    def color(self, val) -> None: ...
    @property
    def line(self): ...
    @line.setter
    def line(self, val) -> None: ...
    @property
    def opacity(self): ...
    @opacity.setter
    def opacity(self, val) -> None: ...
    @property
    def outliercolor(self): ...
    @outliercolor.setter
    def outliercolor(self, val) -> None: ...
    @property
    def size(self): ...
    @size.setter
    def size(self, val) -> None: ...
    @property
    def symbol(self): ...
    @symbol.setter
    def symbol(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        angle: Any | None = ...,
        color: Any | None = ...,
        line: Any | None = ...,
        opacity: Any | None = ...,
        outliercolor: Any | None = ...,
        size: Any | None = ...,
        symbol: Any | None = ...,
        **kwargs
    ) -> None: ...
