from typing import Any

_calc_total_nnz: fused_cython_function
_csr_polynomial_expansion: fused_cython_function

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _calc_expanded_nnz(*args, **kwargs) -> Any: ...
def _get_sizeof_LARGEST_INT_t(*args, **kwargs) -> Any: ...
def py_calc_expanded_nnz_deg2(*args, **kwargs) -> Any: ...
def py_calc_expanded_nnz_deg3(*args, **kwargs) -> Any: ...
