from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Link(_BaseTraceHierarchyType):
    @property
    def arrowlen(self): ...
    @arrowlen.setter
    def arrowlen(self, val) -> None: ...
    @property
    def color(self): ...
    @color.setter
    def color(self, val) -> None: ...
    @property
    def colorscales(self): ...
    @colorscales.setter
    def colorscales(self, val) -> None: ...
    @property
    def colorscaledefaults(self): ...
    @colorscaledefaults.setter
    def colorscaledefaults(self, val) -> None: ...
    @property
    def colorsrc(self): ...
    @colorsrc.setter
    def colorsrc(self, val) -> None: ...
    @property
    def customdata(self): ...
    @customdata.setter
    def customdata(self, val) -> None: ...
    @property
    def customdatasrc(self): ...
    @customdatasrc.setter
    def customdatasrc(self, val) -> None: ...
    @property
    def hoverinfo(self): ...
    @hoverinfo.setter
    def hoverinfo(self, val) -> None: ...
    @property
    def hoverlabel(self): ...
    @hoverlabel.setter
    def hoverlabel(self, val) -> None: ...
    @property
    def hovertemplate(self): ...
    @hovertemplate.setter
    def hovertemplate(self, val) -> None: ...
    @property
    def hovertemplatesrc(self): ...
    @hovertemplatesrc.setter
    def hovertemplatesrc(self, val) -> None: ...
    @property
    def label(self): ...
    @label.setter
    def label(self, val) -> None: ...
    @property
    def labelsrc(self): ...
    @labelsrc.setter
    def labelsrc(self, val) -> None: ...
    @property
    def line(self): ...
    @line.setter
    def line(self, val) -> None: ...
    @property
    def source(self): ...
    @source.setter
    def source(self, val) -> None: ...
    @property
    def sourcesrc(self): ...
    @sourcesrc.setter
    def sourcesrc(self, val) -> None: ...
    @property
    def target(self): ...
    @target.setter
    def target(self, val) -> None: ...
    @property
    def targetsrc(self): ...
    @targetsrc.setter
    def targetsrc(self, val) -> None: ...
    @property
    def value(self): ...
    @value.setter
    def value(self, val) -> None: ...
    @property
    def valuesrc(self): ...
    @valuesrc.setter
    def valuesrc(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        arrowlen: Any | None = ...,
        color: Any | None = ...,
        colorscales: Any | None = ...,
        colorscaledefaults: Any | None = ...,
        colorsrc: Any | None = ...,
        customdata: Any | None = ...,
        customdatasrc: Any | None = ...,
        hoverinfo: Any | None = ...,
        hoverlabel: Any | None = ...,
        hovertemplate: Any | None = ...,
        hovertemplatesrc: Any | None = ...,
        label: Any | None = ...,
        labelsrc: Any | None = ...,
        line: Any | None = ...,
        source: Any | None = ...,
        sourcesrc: Any | None = ...,
        target: Any | None = ...,
        targetsrc: Any | None = ...,
        value: Any | None = ...,
        valuesrc: Any | None = ...,
        **kwargs
    ) -> None: ...
