from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Node(_BaseTraceHierarchyType):
    @property
    def color(self): ...
    @color.setter
    def color(self, val) -> None: ...
    @property
    def colorsrc(self): ...
    @colorsrc.setter
    def colorsrc(self, val) -> None: ...
    @property
    def customdata(self): ...
    @customdata.setter
    def customdata(self, val) -> None: ...
    @property
    def customdatasrc(self): ...
    @customdatasrc.setter
    def customdatasrc(self, val) -> None: ...
    @property
    def groups(self): ...
    @groups.setter
    def groups(self, val) -> None: ...
    @property
    def hoverinfo(self): ...
    @hoverinfo.setter
    def hoverinfo(self, val) -> None: ...
    @property
    def hoverlabel(self): ...
    @hoverlabel.setter
    def hoverlabel(self, val) -> None: ...
    @property
    def hovertemplate(self): ...
    @hovertemplate.setter
    def hovertemplate(self, val) -> None: ...
    @property
    def hovertemplatesrc(self): ...
    @hovertemplatesrc.setter
    def hovertemplatesrc(self, val) -> None: ...
    @property
    def label(self): ...
    @label.setter
    def label(self, val) -> None: ...
    @property
    def labelsrc(self): ...
    @labelsrc.setter
    def labelsrc(self, val) -> None: ...
    @property
    def line(self): ...
    @line.setter
    def line(self, val) -> None: ...
    @property
    def pad(self): ...
    @pad.setter
    def pad(self, val) -> None: ...
    @property
    def thickness(self): ...
    @thickness.setter
    def thickness(self, val) -> None: ...
    @property
    def x(self): ...
    @x.setter
    def x(self, val) -> None: ...
    @property
    def xsrc(self): ...
    @xsrc.setter
    def xsrc(self, val) -> None: ...
    @property
    def y(self): ...
    @y.setter
    def y(self, val) -> None: ...
    @property
    def ysrc(self): ...
    @ysrc.setter
    def ysrc(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        color: Any | None = ...,
        colorsrc: Any | None = ...,
        customdata: Any | None = ...,
        customdatasrc: Any | None = ...,
        groups: Any | None = ...,
        hoverinfo: Any | None = ...,
        hoverlabel: Any | None = ...,
        hovertemplate: Any | None = ...,
        hovertemplatesrc: Any | None = ...,
        label: Any | None = ...,
        labelsrc: Any | None = ...,
        line: Any | None = ...,
        pad: Any | None = ...,
        thickness: Any | None = ...,
        x: Any | None = ...,
        xsrc: Any | None = ...,
        y: Any | None = ...,
        ysrc: Any | None = ...,
        **kwargs
    ) -> None: ...
