from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Delta(_BaseTraceHierarchyType):
    @property
    def decreasing(self): ...
    @decreasing.setter
    def decreasing(self, val) -> None: ...
    @property
    def font(self): ...
    @font.setter
    def font(self, val) -> None: ...
    @property
    def increasing(self): ...
    @increasing.setter
    def increasing(self, val) -> None: ...
    @property
    def position(self): ...
    @position.setter
    def position(self, val) -> None: ...
    @property
    def prefix(self): ...
    @prefix.setter
    def prefix(self, val) -> None: ...
    @property
    def reference(self): ...
    @reference.setter
    def reference(self, val) -> None: ...
    @property
    def relative(self): ...
    @relative.setter
    def relative(self, val) -> None: ...
    @property
    def suffix(self): ...
    @suffix.setter
    def suffix(self, val) -> None: ...
    @property
    def valueformat(self): ...
    @valueformat.setter
    def valueformat(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        decreasing: Any | None = ...,
        font: Any | None = ...,
        increasing: Any | None = ...,
        position: Any | None = ...,
        prefix: Any | None = ...,
        reference: Any | None = ...,
        relative: Any | None = ...,
        suffix: Any | None = ...,
        valueformat: Any | None = ...,
        **kwargs
    ) -> None: ...
