from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Gauge(_BaseTraceHierarchyType):
    @property
    def axis(self): ...
    @axis.setter
    def axis(self, val) -> None: ...
    @property
    def bar(self): ...
    @bar.setter
    def bar(self, val) -> None: ...
    @property
    def bgcolor(self): ...
    @bgcolor.setter
    def bgcolor(self, val) -> None: ...
    @property
    def bordercolor(self): ...
    @bordercolor.setter
    def bordercolor(self, val) -> None: ...
    @property
    def borderwidth(self): ...
    @borderwidth.setter
    def borderwidth(self, val) -> None: ...
    @property
    def shape(self): ...
    @shape.setter
    def shape(self, val) -> None: ...
    @property
    def steps(self): ...
    @steps.setter
    def steps(self, val) -> None: ...
    @property
    def stepdefaults(self): ...
    @stepdefaults.setter
    def stepdefaults(self, val) -> None: ...
    @property
    def threshold(self): ...
    @threshold.setter
    def threshold(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        axis: Any | None = ...,
        bar: Any | None = ...,
        bgcolor: Any | None = ...,
        bordercolor: Any | None = ...,
        borderwidth: Any | None = ...,
        shape: Any | None = ...,
        steps: Any | None = ...,
        stepdefaults: Any | None = ...,
        threshold: Any | None = ...,
        **kwargs
    ) -> None: ...
