with

raw as (
    select
        cfxmlid as cfxml_id,
        viewtopic as viewtopic,
        viewid as viewid,
        cfxmlprevid as cfxml_prev_id,
        transactionsequencenumber as transaction_sequence_numb,
        agencynumber as agy_numb,
        agencyfullname as agy_full_name,
        agencyaddressfirstline as agy_address_first_line,
        agencystreetaddress as agy_street_address,
        agencycityname as agy_city,
        agencystatecode as agy_state_code,
        agencyzipcode as agy_zip_code,
        policysymbol as policy_sym,
        policynumber as policy_numb,
        statisticalpolicymodulenumber as policy_module,
        companycode as company_code,
        policyeffectivedate as policy_efff_date,
        policyexpirationdate as policy_exp_date,

        quotenumber as quote_numb,
        quoteversionnumber as quote_version_numb,

        priorviewtopic as prior_viewtopic,
        priorpolicyfullnumber as prior_policy_full_numb,
        priorpolicynumber2 as prior_policy_numb2,
        priorpolicynumber3 as prior_policy_numb3,
        priorpolicynumber4 as prior_policy_numb4,
        priorpolicynumber5 as prior_policy_numb5,
        priorpolicynumber6 as prior_policy_numb6,

        firstpolicyeffectivedate as first_policy_eff_date,
        firstinsuredlegalentitytype as first_insured_legal_entity_type,
        firstinsuredfullname as first_insured_full_name,

        insured_address_first_line as insured_address_first_line,
        insured_address_street as insured_address_street,
        insured_address_city as insured_address_city,
        insured_address_county as insured_address_county,
        insured_address_zip_5 as insured_address_zip_5,
        insured_address_zip_extension as insured_address_zip_extension,
        insured_address_state as insured_address_state,
        insured_address_latitude as insured_address_latitude,
        insured_address_longitude as insured_address_longitude,

        policyproducttypedescription as policy_product_type_desc,
        packagetypedescription as package_type_desc,
        risktypecode as risk_type_code,
        customer_care_center_ind as is_cccc,
        risktypedescription as risk_type_desc,

        targetmarketprogramdescription as target_market_program_desc,
        dartcode as dart_code,
        dart1code as dart1_code,
        dart1description as dart1_desc,
        dart2code as dart2_code,
        dart2description as dart2_desc,
        dart3code as dart3_code,
        dart3description as dart3_desc,
        dart4code as dart4_code,
        dart4description as dart4_desc,
        dart5code as dart5_code,
        dart5description as dart5_desc,
        dart6code as dart6_code,
        dart6description as dart6_desc,
        dart7code as dart7_code,
        dart7description as dart7_desc,
        dart8code as dart8_code,
        dart8description as dart8_desc,
        dart9code as dart9_code,
        dart9description as dart9_desc,

        firstinsurednaicscode as first_insured_naics_code,
        try_cast(naicsoverriddenindicator as utinyint) as is_naics_overridden,
        try_cast(naicsvalidatedindicator as utinyint) as is_naics_validated,

        primaryriskstatecode as primary_risk_state_code,
        billingmethoddescription as billing_method_desc,
        paymentmethoddescription as payment_method_desc,
        premiumpaymentplandescription as premium_payment_plan_desc,
        packagecommissionpercent as package_commission_pct,

        try_cast(loss_free_discount_ind as utinyint) as is_loss_free,
        prop_exp_rating_eligible_ind as is_elligible_property_experience_rating,
        prop_cause_of_loss_form as property_cause_of_loss_form,

        try_cast(annualpremiumamount as double) as annual_premium,
        try_cast(transactionpremiumamount as double) as transaction_premium,

        transactiontypedescription as transaction_type_desc,
        transactiontypesourcedescription as transaction_type_source_desc,

        try_cast(transactioneffectivedate as date) as transaction_eff_date,
        try_cast(transactionexpirationdate as date) as transaction_exp_date,
        transactionstatusdescription as transaction_status_desc,
        try_cast(transactionprocesseddatetime as datetime) as transaction_proccessed_at,
        trans_out_of_seq_ind as is_transaction_out_of_sequence,
        policystatusdescription as policy_status_desc,
        min_prem_applied_ind as is_minimum_premium_applied,
        prop_min_prem_applied_ind as is_property_minimum_premium_applied,
        try_cast(property_annual_premium as double) as property_annual_premium,
        try_cast(property_transaction_premium as double) as property_transaction_premium,
        try_cast(firepolicyearnedpremium as double) as fire_policy_earned_premium,

        try_cast(locationnumber as uinteger) as location_numb,
        try_cast(buildingnumber as uinteger) as building_numb,
        streetaddress as street_address,
        addressfirstline as address_first_line,
        addresssecondline as address_second_line,
        cityname as city,
        statecode as state_code,
        zipcode as zip_code,
        zipextensioncode as zip_extension_code,
        countyname as county,
        try_cast(longitude as double) as longitude,
        try_cast(latitude as double) as latitude,

        locationterritory as location_territory,
        group2territory as group2__territory,
        specialformterritory as special_form__territory,
        eqterritory as eq__territory,
        eqzone as eq__zone,
        commercialfirebuildingratetype as fire__building_rate_type,
        building_vacant_ind as is_building_vacant,
        try_cast(number_stories_quantity as uinteger) as number_stories,
        sprinkler_ind as is_sprinklered,
        bceg_description as bceg_desc,
        try_cast(hazard_grade_number as uinteger) as hazard_grade,
        try_cast(construction_year as uinteger) as construction_year,

        bgi_construction as group1__construction,
        bgii_construction_original as group2__construction_original,
        bgii_construction_final as group2__construction_final,
        bgii_masonry_type as group2__masonry_type,
        bgii_rise_description as group2__rise_desc,
        bgii_steel_type as group2__steel_type,
        try_cast(square_footage as double) as square_footage,

        protection_class as protection_class,
        commercialfirebuildingrcpcode as fire__building_rcp_code,
        amount_of_insurance_limit as amount_of_insurance,
        wind_hail_excl_ind as is_wind_hail_excluded,

        try_cast(hurricane_deductible as double) as hurricane_deductible,
        try_cast(named_storm_deductible as double) as named_storm_deductible,
        try_cast(wind_hail_deductible as double) as wind_hail_deductible,
        try_cast(property_deductible as double) as property_deductible,

        bgii_construction_ny as group2__construction_ny,

        coveragecomponentagreementid as coverage_component_agreement_id,
        sourcecoveragedescription as source_coverage_desc,
        actionindicator as is_action,
        coverageratingversionidentifier as coverage_rating_version_id,
        coveragetypedescription as coverage_type_desc,
        coveragerisktypedescription as coverage_risk_type_desc,

        classificationcode as class_code,
        classificationdescription as class_desc,
        cincipak_class_code as cincipak_class_code,

        blanketinsuranceindicator as is_blanket_insurance,
        classificationdescriptionove0001 as class_desc_ove,
        coinsurancepercent as coinsurance_pct,
        contentstypedescription as contents_type_desc,

        try_cast(broadcalculated1stmodrate as double) as broad__calculated_1st_mod_rate,
        try_cast(broadcalculated2ndmodrate as double) as broad__calculated_2nd_mod_rate,
        try_cast(broadnetrate as double) as board__net_rate,
        try_cast(civilauthorityincperiodfactor as double) as civil_authority_inc_period_factor,
        try_cast(extendedperiodofindemnityfactor as double) as extended_period_of_indemnity_factor,

        try_cast(group1calculated1stmodrate as double) as group1__calculated_1st_mod_rate,
        try_cast(group1calculated1stmodratewi0001 as double) as group1__calculated_1st_mod_rate_with,
        try_cast(group1calculated2ndmodrate as double) as group1__calculated_2nd_mod_rate,
        try_cast(group1calculated2ndmodratewi0001 as double) as group1__calculated_2nd_mod_rate_with,

        try_cast(group1calculatedbldgrate as double) as group1__calculated_building_rate,
        try_cast(group1calculatedbldgratewith0001 as double) as group1__calculated_building_rate_with,
        try_cast(group1netrate as double) as group1__net_rate,
        try_cast(group1netratewithoutvandalism as double) as group1__net_rate_wo_vandalism,
        try_cast(group1specificfireratemutliplier as double) as group1__specific_fire_rate_factor,
        try_cast(group2calculated1stmodrate as double) as group2__calculated_1st_mod_rate,
        try_cast(group2calculated2ndmodrate as double) as group2__calculated_2nd_mod_rate,
        try_cast(group2calculatedbldgrate as double) as group2__calculated_building_rate,
        try_cast(group2netrate as double) as group2__net_rate,
        try_cast(group2specificfireratemutliplier as double) as group2__specific_fire_rate_factor,

        try_cast(mercantilefactor as double) as mercantile_factor,
        try_cast(mercantilerate as double) as mercantile_rate,
        try_cast(mfgfactor as double) as manufacturing_factor,
        try_cast(mfgrate as double) as manufacturing_rate,
        try_cast(miningpropertiesgroup1factor as double) as group1__mining_properties_factor,
        try_cast(miningpropertiesgroup2factor as double) as group2__mining_properties_factor,
        try_cast(businessincomeoptionfactor as double) as business_income__factor,
        try_cast(ordinanceorlawincperiodfactor as double) as ordinance_or_law_inc_period__factor,
        try_cast(ordinarypayrollexclusionfactor as double) as ordinary_payroll_exclusion__factor,
        try_cast(powerheatrefrigerationfactor as double) as power_heat_refrigeration__factor,

        try_cast(rentalareaquantity as double) as rental_area_quantity,
        try_cast(rentalfactor as double) as rental__factor,
        try_cast(rentalrate as double) as rental__rate,
        try_cast(totalratemodificationfactor as double) as tmf,

        try_cast(specialformcalculated1stmodrate as double) as special_form__calculated_1st_mod_rate,
        try_cast(specialformcalculated2ndmodrate as double) as special_form__calculated_2nd_mod_rate,
        try_cast(specialformnetrate as double) as special_form__net_rate,
        try_cast(specialformtotalpremium as double) as special_form__total_premium,
        try_cast(utilityservicesdeviationfactor as double) as utility_services__deviation_factor,

        utilityservicesdeviationind as is_utility_services_deviation,

        try_cast(powerheatandrefrigerationded0001 as double) as power_heat_refrigeration__deductible,
        try_cast(waitingperioddeductiblehours as double) as waiting_period_deductible__hours,
        try_cast(waitingperioddeductiblefactor as double) as waiting_period_deductible__factor,
        try_cast(tbceggroup2factor as double) as group2__bceg_factor,
        try_cast(modifiedactualtheftincrement as double) as modified_actual_theft_increment,
        try_cast(actualtheftincrement as double) as actual_theft_increment,
        try_cast(agreedvaluefactor as double) as agreed_value_factor,

        basicgroup2cosmeticexclusion0001 as group2__cosmetic_exclusion,
        try_cast(windhaildeductiblefactor as double) as wind_hail__deductible_factor,
        try_cast(basicgroup1protectionclassmu0001 as double) as group1__protection_class_factor,
        try_cast(basicgroup1vandalismloadrate0001 as double) as group1__vandalism_mod_rate,
        try_cast(broadcoinsurancefactor as double) as broad__coinsurance_factor,
        try_cast(broadmodifiedbaserate as double) as board__modified_base_rate,
        try_cast(acvprovisionfactor as double) as actual_cash_value_factor,
        try_cast(broadformbaseratefactor as double) as broad__base_rate_factor,
        try_cast(functionalreplacementcostfactor as double) as functional_replacement_cost_factor,

        try_cast(group1baseratefactor as double) as group1__base_rate_factor,
        try_cast(group1coinsuranceadditionfactor as double) as group1__coinsurance_addition_factor,
        try_cast(group2baseratefactor as double) as group2__base_rate_factor,

        try_cast(icedammingdeductiblefactor as double) as ice_damming_deductible_factor,
        incidentalapartmentfactor as incidental_apartment_factor,
        lossfreediscount as loss_free_discount,
        medicalsocietyfactor as medical_society_factor,
        namedstormdeductiblefactor as named_storm_deductible_factor,
        ratereductionfactor as rate_reduction_factor,
        specialblanketfirstratingtotal as special__blanket_first_rating_total,
        specialformblanketfirstratin0001 as nan,
        specialformbaseratefactor as special__base_rate_factor,
        windstormlossmitigationfactor as wind_storm_loss_mitigation_factor,
        windstormprotectivedevicesfactor as wind_storm_protective_devices_factor,
        deductiblefactor as deductible_factor,
        group1coinsurancefactor as group1__coinsurance_factor,
        group1coinsuranceless80factor as group1__coinsurance_below_80_factor,
        group1modifiedbaserate as group1__modified_base_rate,
        group1modifiedbaseratewithou0001 as group1__modified_base_rate_without_vandalism,
        group1specificfireratemultiplier as group1__specific_fire_rate_factor,
        group2coinsurancefactor as group2__coinsurance_factor,
        group2coinsuranceless80perce0001 as group2__coinsurance_below_80_factor,
        group2modifiedbaserate as group2__modified_base_rate,
        group2specificfireratemultiplier as group2__specific_fire_rate_factor,
        hurricanedeductiblefactor as hurricane_deductible_factor,
        specialcoinsurancefactor as special__coinsurance_factor,
        specialmodifiedbaserate as special__modified_base_rate,
        statedeviationfactor as state_deviation_factor,
        tierratingfactor as tier_rating_factor,
        vacantpropertyfactor as vacant_propery_factor,
        vandalismexclusionfactor as vandalism_exclusion_factor,
        specialformterritorialmultiplier as special__territorial_multiplier,
        vandalismexclfactorwithoutva0001 as vandalism_exclusion_factor_without_va,
        sprinklerexclminusrate as sprinkler_exclusion_minus_rate,
        sprinklerexclusionfactor as sprinkler_exclusion_factor,
        territorialmultiplier as territorial_multiplier,
        windhailexclfactor as wind_hail_exclusion_factor,
        broadformcalculatedbldgrate as broad__calculated_building_rate,
        deductiblepercentage as deductible_pct,
        includedlimitamount as included_limit,
        ratinglimit as rating_limit,
        specialformcalculatedbldgrate as special__calculated_building_rate,
        businccincipaksprinklerexclu0001 as business_in_cincipak_sprinkler_exclusion,
        businccincipaktheftexclusion0001 as business_in_cincipak_theft_exclusion,
        businccincipakvandalismexclu0001 as business_in_cincipak_vandalism_exclusion,
        agreedvalueindicator as is_agreed_value,
        basicgroup1isospecificlossco0001 as group1__iso_specific_loss_co,
        basicgroup2isospecificlossco0001 as group2__iso_specific_loss_co,
        basicgroup2numericprefixfactor as group2__numeric_prefix_factor,
        blanketadjustedlimitamount as blanket__adjusted_limit,
        blanketadjustedlimitper100 as blanket__adjusted_limit_per_100,
        icedammingdeductible as ice_damming_deductible,
        originalrqlimit as original_rq_limit,
        limitamount as limit,
        limitamountper100 as limit_per_100,
        propertyvaluationtypedescription as property_valuation_type_desc,
        rategroup as rate_group,
        classlimit as class_limit,
        classlimitforrating as class_limit_for_rating,
        companyratemodificationfactor as company_rmf,
        actuallosssustainedoption as actual_loss_sustained_option,
        extperiodnbrofdays as extended_period_of_indemnity_number_of_days,
        extendedperiodofindemnityind0001 as is_extended_period_of_indemnity,
        extraexpensedescription as extra_expense_desc,
        includingrentalresolved as including_rental_resolved,
        mercantileareaquantity as mercantile_area_quantity,
        manufacturingareaquantity as manufacturing_area_quantity,
        miningpropertiesindicator as is_mining_property,
        monthlylimitationquantity as monthly_limitation_quantity,
        ordinarypayrollexclusionindi0001 as is_ordinary_payroll_exclusion,
        maxlimit as max_limit,
        reportingrate as reporting_rate,
        group1blanketfirstratingtota0001 as group1__blanket_first_rating_total,
        totalpremiumblanketfirstrating as total_premium_blanket_first_rating_total,
        group2blanketfirstratingtotal as group2__blanket_first_rating_total,
        currentpeakseasontotal as current_peak_season_total,
        group1totalpremium as group1__total_premium,
        specialtheftblanketfirstrati0001 as special_theft__blanket_first_rating_total,
        specialtheftrolluppremium as special_theft__rollup_premium,
        theftpremium as theft_premium,
        totalpremium as total_premium,
        broadblanketfirstratingtotal as broad__blanket_first_rating_total,
        broadformtotalpremium as broad__total_premium,
        group1premiumwithoutvandalism as group1__premium_without_vandalism,
        group2totalpremium as group2__total_premium,
        group1blanketfirstratingtotal as group1__blanket_first_rating_total,
        lpdpbasis as lpdp_basis,
        buildingcoveragelimitamount as building_coverage_limit,
        buildingcoveragelimitexposure as building_coverage_limit_exposure,
        buildingcoveragepremiumamount as building_coverage_premium,
        buildingeqcoveragelimitamount as building_eq_coverage_limit,
        buildingeqcoveragelimitexposure as building_eq_coverage_limit_exposure,
        coinsurancefactor as coinsurance_factor,
        coverageafactor as coverage_a__factor,
        coverageaearthquakefactor as coverage_a__eq_factor,
        coverageaearthquakepremium as coverage_a__eq_premium,
        coverageafloodonlylimitation0001 as coverage_a__flood_only_limitation,
        coverageapremium as coverage_a__premium,
        coverageatotalpremium as coverage_a__total_premium,
        coverageblimitamount as coverage_b__limit,
        coveragebexposure as coverage_b__exposure,
        coverageclimitamount as coverage_c__limit,
        coveragecexposure as coverage_c__exposure,
        coveragebearthquakenetrate as coverage_b__eq_net_rate,
        coveragebearthquakepremium as coverage_b__eq_premium,
        coveragebfloodonlylimitation0001 as coverage_b__flood_only_limitation,
        coveragebnetrate as coverage_b__net_rate,
        coveragebpremium as coverage_b__premium,
        coveragebtotalpremium as coverage_b__total_premium,
        coveragecearthquakepremium as coverage_c__eq_premium,
        coveragecfloodonlylimitation0001 as coverage_c__flood_only_limitation,
        coveragecnetrate as coverage_c__net_rate,
        coveragecpremium as coverage_c__premium,
        coveragectotalpremium as coverage_c__total_premium,
        buildingearthquakepremium as building__eq_premium,
        floodcoveragelimitamount as flood__limit,
        floodcoveragepremium as flood__premium,
        floodonlylimitationtotalpremium as flood_only_limitation_total_premium,
        inflationguardfactor as inflation_guard_factor,
        totalinsurablereplacementcost as total_insurable_replacement_cost,
        cosmeticexclusionindicator as is_cosmetic_exclusion,
        acvprovisionindicator as is_actual_cash_value,
        medicalsocietyindicator as is_medical_society,
        inflationguardindicator as is_inflation_guard,
        orgicedammingdeductibleindicator as is_org_ice_damming_deductible,
        totalnumberunits as total_number_of_units,
        icedammingdeductibleindicator as is_ice_damming_deductible,
        windstormprotectivedevicesin0001 as is_wind_storm_protective_devices,
        incidentalapartmentindicator as is_incidental_apartment,
        coverageaindicator as is_coverage_a,
        coveragebindicator as is_coverage_b,
        coveragecindicator as is_coverage_c,
        coverageeqindicator as is_coverage_eq,
        floodonlylimitationind as is_flood_only_limitation,
        blanketactionindicator as is_blanket_action,
        blanketcoveragecomponentagre0002 as blanket_coverage_component_agre,
        blanketcoveragetypedescription as blanket_coverage_type_desc,
        blanketcoinsurancepercent as blanket_coinsurance_pct,
        blanketspecialthefttotalpremium as special__blanket_theft_total_premium,
        blanketissuedspecialthefttot0001 as special__issued_blanket_theft_total_premium,
        blanketissuedgroup2totalpremium as group2__issued_blanket_total_premium,
        blanketissuedgroup1totalprem0001 as group1__issued_blanket_total_premium1,
        blanketissuedgroup1totalpremium as group1__issued_blanket_total_premium,
        blanketissuedeqtotalpremium as eq__issued_blanket_total_premium,
        blanketissuedbroadtotalpremium as broad__issued_blanket_total_premium,
        blanketgroup2totalpremium as group2__blanket_total_premium,
        blanketgroup1totalpremiumwit0001 as group1__blanket_total_premium_with,
        blanketgroup1totalpremium as group1__blanket_total_premium,
        blanketeqtotalpremium as eq__blanket_eq_total_premium,
        blanketbroadformtotalpremium as broad__blanket_total_premium,
        blankettotalblanketlimitamou0001 as blanket_total_blanket_limit_per_100,
        blankettotalblanketlimitamount as blanket_total_blanket_limit,
        blanketspecialtheftrate as special__blanket_theft_rate,
        blanketspecialtheftnetrate as special__blanket_theft_net_rate,
        blanketspecialtheftlimitadju0001 as special__blanket_theft_limit_adjustment,
        blanketissuedtotallimitamoun0001 as total__blanket_issued_limit_per_100,
        blanketissuedtotallimitamount as total__blanket_issued_limit,
        blanketissuedeqtotallimitamo0001 as eq__blanket_issued_total_limit_per_100,
        blanketissuedeqtotallimitamount as eq__blanket_issued_total_limit,
        blanketgroup2rate as group2__blanket_rate,
        blanketgroup2netrate as group2__net_blanket_rate,
        blanketgroup2limitadjustment0001 as group2__blanket_limit_adjustment,
        blanketgroup1ratewithoutvand0001 as group1__blanket_rate_without_vandalism,
        blanketgroup1rate as group1__blanket_rate,
        blanketgroup1netratewithoutv0001 as group1__blanket_net_rate_without_vandalism,
        blanketgroup1netrate as group1__blanket_net_rate,
        blanketgroup1limitadjustment0001 as group1__blanket_limit_adjustment,
        blanketeqtotallimitamountper100 as eq__blanket_limit_per_100,
        blanketeqtotallimitamount as eq__blanket_limit,
        blanketeqsublimitnetrate as eq__blanket_sublimit_net_rate,
        blanketeqsublimitcoinsurance0001 as eq__blanket_sublimit_coinsurance,
        blanketeqsublimitadjustmentf0001 as eq__blanket_sublimit_adjustment_factor,
        blanketeqrate as eq__blanket_rate,
        blanketeqnetrate as eq__blanket_net_rate,
        blanketeqlimitadjustmentfactor as eq__blanket_limit_adjustment_factor,
        blanketcoinsurancefactor as blanket_coinsurance_factor,
        blanketissuedblanketcoinsura0001 as blanket_issued_blanket_coinsurance,
        blanketbroadformrate as broad__blanket_rate,
        blanketbroadformnetrate as broad__blanket_net_rate,
        blanketbroadformlimitadjustm0001 as broad__blanket_limit_adjustment,
        blanketraterecalculatedindicator as is_blanket_rate_calculated,
        blanketoriginalrqtotallimit as blanket_original_rq_total_limit,
        eqactionindicator as is_eq_action,
        eqcoveragecomponentagreementname as eq__coverage_component_agreement_name,
        eqminimumpremiumappliedindicator as is_eq_minimum_premium_applied,
        eqblanketinsuranceindicator as is_eq_blanket_insurance,
        eqagreedvaluefactor as eq__agreed_value_factor,
        eqamounttomeetminimumpremium0001 as eq__amount_to_meet_minimum_premium,
        eqbaseratefactor as eq__base_rate_factor,
        bcegeqfactor as eq__bceg_factor,
        eqbiextraexpensefactor as eq__bi_extra_expense_factor,
        eqblanketadjustedlimitamount as eq__blanket_adjusted_limit,
        eqblanketadjustedlimitper1000001 as eq__blanket_adjusted_limit_per_100,
        eqblanketfirstratingtotal as eq__blanket_first_rating_total,
        eqcalculatedblanketpremium as eq__calculated_blanket_premium,
        eqcalculatedpremium as eq__calculated_blanket_premium,
        eqcoinsurancefactor as eq__coinsurance_factor,
        eqdeductiblefactor as eq__deductible_factor,
        eqinflationguardfactor as eq__inflation_guard_factor,
        eqlimitamount as eq__limit,
        eqlossfreediscount as eq__loss_free_discount,
        eqmasonryveneerpercent as eq__masonry_veneer_pct,
        eqmasonryveneerlimitationfactor as eq__masonry_veneer_limitation_factor,
        eqminimumpremiumamount as eq__minimum_premium,
        eqmodifiedbaserate as eq__modified_base_rate,
        eqbuildingheightmodification0001 as eq__building_height_modification,
        eqbusinessincomeordinanceorl0001 as eq__business_income_ordinance_or_l,
        eqpersonalpropertyrategrade as eq__personal_property_rate_grade,
        eqreductioncredit as eq__reduction_credit,
        eqreductionpercentage as eq__reduction_pct,
        eqpackageratemodificationfactor as eq__package_rmf,
        eqtotalratemodificationfactor as eq__tmf,
        eqrooftankonbuildingfactor as eq__roof_tank_on_building_factor,
        eqsprinklerriskfactor as eq__sprinkler_risk_factor,
        eqsublimitfactor as eq__sublimit_factor,
        eqtierfactor as eq__tier_factor,
        eqtimeelementfactor as eq__time_element_factor,
        eqtotalpremium as eq__total_premium,
        eqtransitionbaserate as eq__transition_base_rate,
        eqwaitingperioddedfactor as eq__waiting_period_deductible_factor,
        eqordinanceorlawincreasedper0001 as eq__ordinance_or_law_increased_per_100,
        eqbuildingclasscode as eq__building_class_code,
        eqbuildingclassdescription as eq__building_class_desc,
        eqnumberofstories as eq__number_of_stories,
        eqrooftankindicator as is_eq_roof_tank,
        eqminimumpremiumwaivedindicator as is_eq_minimum_premium_waived,
        blanketlimitamount as blanket_limit,
        blanketdeductibleamount as blanket_deductible,
        blanketeqdeductibleamount as eq__blanket_deductible,
        blanketpropertyvaluationtypedesc as blanket_property_valuation_type_desc,
        blanketagreedvalueindicator as is_blanket_agreed_value,
        blanketinflationguardindicator as is_blanket_inflation_guard,
        blanketeqdollarsdeductibleamount as eq__blanket_dollars_deductible,
        coveragedaysquantity as coverage_days,
        eqsublimitblanketindicator as is_eq_sublimit_blanket,
        eqsublimitblankettype as eq__sublimit_blanket_type,
        number_of_locations as number_of_locations,
        number_of_buildings_for_policy as number_of_buildings_for_policy,
        number_of_buildings_for_location as number_of_buildings_for_location,
        location_annual_premium as location_annual_premium,
        building_annual_premium as building_annual_premium,
        imagenumber as image_numb,
        imageeffectivedate as image_eff_date,
        imageexpirationdate as image_exp_date,
        numberofexposuredays as number_of_exposure_days,
        policyearnedpremium as policy_earned_premium,
        specialformearnedpremium as special__earned_premium,
        group1earnedpremium as group1__earned_premium,
        group2earnedpremium as group2__earned_premium,
        broadformearnedpremium as broad__earned_premium,
        totalearnedpremium as total_earned_premium,
        ghost as ghost,

        try_cast(deductiblerecoverypayment_grp1 as double) as group1__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_grp2 as double) as group2__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_other as double) as other__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_sp0001 as double) as special__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_eq as double) as eq__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_al0001 as double) as all_perils__paid_deuctible_recovery,
        try_cast(expensepayment_grp1 as double) as group1__paid_expense,
        try_cast(expensepayment_grp2 as double) as group2__paid_expense,
        try_cast(expensepayment_other as double) as other__paid_expense,
        try_cast(expensepayment_special as double) as special__paid_expense,
        try_cast(expensepayment_eq as double) as eq__paid_expense,
        try_cast(expensepayment_allperils as double) as all_perils__paid_expense,
        try_cast(expenserecoverypayment_grp1 as double) as group1__paid_expense_recovery,
        try_cast(expenserecoverypayment_grp2 as double) as group2__paid_expense_recovery,
        try_cast(expenserecoverypayment_other as double) as other__paid_expense_recovery,
        try_cast(expenserecoverypayment_special as double) as special__paid_expense_recovery,
        try_cast(expenserecoverypayment_eq as double) as eq__paid_expense_recovery,
        try_cast(expenserecoverypayment_allperils as double) as all_perils__paid_expense_recovery,
        try_cast(losspayment_grp1 as double) as group1__paid_loss,
        try_cast(losspayment_grp2 as double) as group2__paid_loss,
        try_cast(losspayment_other as double) as other__paid_loss,
        try_cast(losspayment_special as double) as special__paid_loss,
        try_cast(losspayment_eq as double) as eq__paid_loss,
        try_cast(losspayment_allperils as double) as all_perils__paid_loss,
        try_cast(salvagepayment_grp1 as double) as group1__paid_salvage,
        try_cast(salvagepayment_grp2 as double) as group2__paid_salvage,
        try_cast(salvagepayment_other as double) as other__paid_salvage,
        try_cast(salvagepayment_special as double) as special__paid_salvage,
        try_cast(salvagepayment_eq as double) as eq__paid_salvage,
        try_cast(salvagepayment_allperils as double) as all_perils__paid_salvage,
        try_cast(subropayment_grp1 as double) as group1__paid_subrogation,
        try_cast(subropayment_grp2 as double) as group2__paid_subrogation,
        try_cast(subropayment_other as double) as other__paid_subrogation,
        try_cast(subropayment_special as double) as special__paid_subrogation,
        try_cast(subropayment_eq as double) as eq__paid_subrogation,
        try_cast(subropayment_allperils as double) as all_perils__paid_subrogation,
        try_cast(totalpaymentamount_allperils as double) as all_perils__total_paid,
        try_cast(catdeductiblerecoverypayment0001 as double) as group1__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0002 as double) as group2__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0003 as double) as other__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0004 as double) as special__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment_eq as double) as eq__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0005 as double) as all_perils__cat_paid_deuctible_recovery,
        try_cast(catexpensepayment_grp1 as double) as group1__cat_paid_expense,
        try_cast(catexpensepayment_grp2 as double) as group2__cat_paid_expense,
        try_cast(catexpensepayment_other as double) as other__cat_paid_expense,
        try_cast(catexpensepayment_special as double) as special__cat_paid_expense,
        try_cast(catexpensepayment_eq as double) as eq__cat_paid_expense,
        try_cast(catexpensepayment_allperils as double) as all_perils__cat_paid_expense,
        try_cast(catexpenserecoverypayment_grp1 as double) as group1__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_grp2 as double) as group2__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_other as double) as other__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_sp0001 as double) as special__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_eq as double) as eq__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_al0001 as double) as all_perils__cat_paid_expense_recovery,
        try_cast(catlosspayment_grp1 as double) as group1__cat_paid_loss,
        try_cast(catlosspayment_grp2 as double) as group2__cat_paid_loss,
        try_cast(catlosspayment_other as double) as other__cat_paid_loss,
        try_cast(catlosspayment_special as double) as special__cat_paid_loss,
        try_cast(catlosspayment_eq as double) as eq__cat_paid_loss,
        try_cast(catlosspayment_allperils as double) as all_perils__cat_paid_loss,
        try_cast(catsalvagepayment_grp1 as double) as group1__cat_paid_salvage,
        try_cast(catsalvagepayment_grp2 as double) as group2__cat_paid_salvage,
        try_cast(catsalvagepayment_other as double) as other__cat_paid_salvage,
        try_cast(catsalvagepayment_special as double) as special__cat_paid_salvage,
        try_cast(catsalvagepayment_eq as double) as eq__cat_paid_salvage,
        try_cast(catsalvagepayment_allperils as double) as all_perils__cat_paid_salvage,
        try_cast(catsubropayment_grp1 as double) as group1__cat_paid_subrogation,
        try_cast(catsubropayment_grp2 as double) as group2__cat_paid_subrogation,
        try_cast(catsubropayment_other as double) as other__cat_paid_subrogation,
        try_cast(catsubropayment_special as double) as special__cat_paid_subrogation,
        try_cast(catsubropayment_eq as double) as eq__cat_paid_subrogation,
        try_cast(catsubropayment_allperils as double) as all_perils__cat_paid_subrogation,
        try_cast(cattotalpaymentamount_allperils as double) as all_perils__cat_total_paid,
        try_cast(deductiblerecoverypayment_al0002 as double) as all_other_causes_of_loss__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_li0001 as double) as liability_cause_of_loss__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_eq_col as double) as eq_cause_of_loss__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_fi0001 as double) as fire_cause_of_loss__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_fr0001 as double) as freezing_cause_of_loss__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_ha0001 as double) as hail_cause_of_loss__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_li0002 as double) as lightning_cause_of_loss__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_no0001 as double) as non_weather_water_cause_of_loss__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_th0001 as double) as theft_cause_of_loss__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_we0001 as double) as weather_water_cause_of_loss__paid_deuctible_recovery,
        try_cast(deductiblerecoverypayment_wi0001 as double) as wind_cause_of_loss__paid_deuctible_recovery,
        try_cast(expensepayment_allother_col as double) as all_other_causes_of_loss__paid_expense,
        try_cast(expensepayment_liability_col as double) as liability_cause_of_loss__paid_expense,
        try_cast(expensepayment_eq_col as double) as eq_cause_of_loss__paid_expense,
        try_cast(expensepayment_fire_col as double) as fire_cause_of_loss__paid_expense,
        try_cast(expensepayment_freezing_col as double) as freezing_cause_of_loss__paid_expense,
        try_cast(expensepayment_hail_col as double) as hail_cause_of_loss__paid_expense,
        try_cast(expensepayment_lightning_col as double) as lightning_cause_of_loss__paid_expense,
        try_cast(expensepayment_nonweatherwat0001 as double) as non_weather_water_cause_of_loss__paid_expense,
        try_cast(expensepayment_theft_col as double) as theft_cause_of_loss__paid_expense,
        try_cast(expensepayment_weatherwater_col as double) as weather_water_cause_of_loss__paid_expense,
        try_cast(expensepayment_wind_col as double) as wind_cause_of_loss__paid_expense,
        try_cast(expenserecoverypayment_allot0001 as double) as all_other_causes_of_loss__paid_expense_recovery,
        try_cast(expenserecoverypayment_liabi0001 as double) as liability_cause_of_loss__paid_expense_recovery,
        try_cast(expenserecoverypayment_eq_col as double) as eq_cause_of_loss__paid_expense_recovery,
        try_cast(expenserecoverypayment_fire_col as double) as fire_cause_of_loss__paid_expense_recovery,
        try_cast(expenserecoverypayment_freez0001 as double) as freezing_cause_of_loss__paid_expense_recovery,
        try_cast(expenserecoverypayment_hail_col as double) as hail_cause_of_loss__paid_expense_recovery,
        try_cast(expenserecoverypayment_light0001 as double) as lightning_cause_of_loss__paid_expense_recovery,
        try_cast(expenserecoverypayment_nonwe0001 as double) as non_weather_water_cause_of_loss__paid_expense_recovery,
        try_cast(expenserecoverypayment_theft_col as double) as theft_cause_of_loss__paid_expense_recovery,
        try_cast(expenserecoverypayment_weath0001 as double) as weather_water_cause_of_loss__paid_expense_recovery,
        try_cast(expenserecoverypayment_wind_col as double) as wind_cause_of_loss__paid_expense_recovery,
        try_cast(losspayment_allother_col as double) as all_other_causes_of_loss__paid_loss,
        try_cast(losspayment_liability_col as double) as liability_cause_of_loss__paid_loss,
        try_cast(losspayment_eq_col as double) as eq_cause_of_loss__paid_loss,
        try_cast(losspayment_fire_col as double) as fire_cause_of_loss__paid_loss,
        try_cast(losspayment_freezing_col as double) as freezing_cause_of_loss__paid_loss,
        try_cast(losspayment_hail_col as double) as hail_cause_of_loss__paid_loss,
        try_cast(losspayment_lightning_col as double) as lightning_cause_of_loss__paid_loss,
        try_cast(losspayment_nonweatherwater_col as double) as non_weather_water_cause_of_loss__paid_loss,
        try_cast(losspayment_theft_col as double) as theft_cause_of_loss__paid_loss,
        try_cast(losspayment_weatherwater_col as double) as weather_water_cause_of_loss__paid_loss,
        try_cast(losspayment_wind_col as double) as wind_cause_of_loss__paid_loss,
        try_cast(salvagepayment_allother_col as double) as all_other_causes_of_loss__paid_salvage,
        try_cast(salvagepayment_eq_col as double) as eq_cause_of_loss__paid_salvage,
        try_cast(salvagepayment_fire_col as double) as fire_cause_of_loss__paid_salvage,
        try_cast(salvagepayment_freezing_col as double) as freezing_cause_of_loss__paid_salvage,
        try_cast(salvagepayment_hail_col as double) as hail_cause_of_loss__paid_salvage,
        try_cast(salvagepayment_lightning_col as double) as lightning_cause_of_loss__paid_salvage,
        try_cast(salvagepayment_nonweatherwat0001 as double) as non_weather_water_cause_of_loss__paid_salvage,
        try_cast(salvagepayment_theft_col as double) as theft_cause_of_loss__paid_salvage,
        try_cast(salvagepayment_weatherwater_col as double) as weather_water_cause_of_loss__paid_salvage,
        try_cast(salvagepayment_wind_col as double) as wind_cause_of_loss__paid_salvage,
        try_cast(subropayment_allother_col as double) as all_other_causes_of_loss__paid_subrogation,
        try_cast(subropayment_liability_col as double) as liability_cause_of_loss__paid_subrogation,
        try_cast(subropayment_eq_col as double) as eq_cause_of_loss__paid_subrogation,
        try_cast(subropayment_fire_col as double) as fire_cause_of_loss__paid_subrogation,
        try_cast(subropayment_freezing_col as double) as freezing_cause_of_loss__paid_subrogation,
        try_cast(subropayment_hail_col as double) as hail_cause_of_loss__paid_subrogation,
        try_cast(subropayment_lightning_col as double) as lightning_cause_of_loss__paid_subrogation,
        try_cast(subropayment_nonweatherwater_col as double) as non_weather_water_cause_of_loss__paid_subrogation,
        try_cast(subropayment_theft_col as double) as theft_cause_of_loss__paid_subrogation,
        try_cast(subropayment_weatherwater_col as double) as weather_water_cause_of_loss__paid_subrogation,
        try_cast(subropayment_wind_col as double) as wind_cause_of_loss__paid_subrogation,
        try_cast(catdeductiblerecoverypayment0006 as double) as all_other_causes_of_loss__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0007 as double) as liability_cause_of_loss__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0008 as double) as eq_cause_of_loss__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0009 as double) as fire_cause_of_loss__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0010 as double) as freezing_cause_of_loss__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0011 as double) as hail_cause_of_loss__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0012 as double) as lightning_cause_of_loss__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0013 as double) as non_weather_water_cause_of_loss__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0014 as double) as theft_cause_of_loss__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0015 as double) as weather_water_cause_of_loss__cat_paid_deuctible_recovery,
        try_cast(catdeductiblerecoverypayment0016 as double) as wind_cause_of_loss__cat_paid_deuctible_recovery,
        try_cast(catexpensepayment_allother_col as double) as all_other_causes_of_loss__cat_paid_expense,
        try_cast(catexpensepayment_liability_col as double) as liability_cause_of_loss__cat_paid_expense,
        try_cast(catexpensepayment_eq_col as double) as eq_cause_of_loss__cat_paid_expense,
        try_cast(catexpensepayment_fire_col as double) as fire_cause_of_loss__cat_paid_expense,
        try_cast(catexpensepayment_freezing_col as double) as freezing_cause_of_loss__cat_paid_expense,
        try_cast(catexpensepayment_hail_col as double) as hail_cause_of_loss__cat_paid_expense,
        try_cast(catexpensepayment_lightning_col as double) as lightning_cause_of_loss__cat_paid_expense,
        try_cast(catexpensepayment_nonweather0001 as double) as non_weather_water_cause_of_loss__cat_paid_expense,
        try_cast(catexpensepayment_theft_col as double) as theft_cause_of_loss__cat_paid_expense,
        try_cast(catexpensepayment_weatherwat0001 as double) as weather_water_cause_of_loss__cat_paid_expense,
        try_cast(catexpensepayment_wind_col as double) as wind_cause_of_loss__cat_paid_expense,
        try_cast(catexpenserecoverypayment_al0002 as double) as all_other_causes_of_loss__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_li0001 as double) as liability_cause_of_loss__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_eq_col as double) as eq_cause_of_loss__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_fi0001 as double) as fire_cause_of_loss__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_fr0001 as double) as freezing_cause_of_loss__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_ha0001 as double) as hail_cause_of_loss__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_li0002 as double) as lightning_cause_of_loss__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_no0001 as double) as non_weather_water_cause_of_loss__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_th0001 as double) as theft_cause_of_loss__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_we0001 as double) as weather_water_cause_of_loss__cat_paid_expense_recovery,
        try_cast(catexpenserecoverypayment_wi0001 as double) as wind_cause_of_loss__cat_paid_expense_recovery,
        try_cast(catlosspayment_allother_col as double) as all_other_causes_of_loss__cat_paid_loss,
        try_cast(catlosspayment_liability_col as double) as liability_cause_of_loss__cat_paid_loss,
        try_cast(catlosspayment_eq_col as double) as eq_cause_of_loss__cat_paid_loss,
        try_cast(catlosspayment_fire_col as double) as fire_cause_of_loss__cat_paid_loss,
        try_cast(catlosspayment_freezing_col as double) as freezing_cause_of_loss__cat_paid_loss,
        try_cast(catlosspayment_hail_col as double) as hail_cause_of_loss__cat_paid_loss,
        try_cast(catlosspayment_lightning_col as double) as lightning_cause_of_loss__cat_paid_loss,
        try_cast(catlosspayment_nonweatherwat0001 as double) as non_weather_water_cause_of_loss__cat_paid_loss,
        try_cast(catlosspayment_theft_col as double) as theft_cause_of_loss__cat_paid_loss,
        try_cast(catlosspayment_weatherwater_col as double) as weather_water_cause_of_loss__cat_paid_loss,
        try_cast(catlosspayment_wind_col as double) as wind_cause_of_loss__cat_paid_loss,
        try_cast(catsalvagepayment_allother_col as double) as all_other_causes_of_loss__cat_paid_salvage,
        try_cast(catsalvagepayment_eq_col as double) as eq_cause_of_loss__cat_paid_salvage,
        try_cast(catsalvagepayment_fire_col as double) as fire_cause_of_loss__cat_paid_salvage,
        try_cast(catsalvagepayment_freezing_col as double) as freezing_cause_of_loss__cat_paid_salvage,
        try_cast(catsalvagepayment_hail_col as double) as hail_cause_of_loss__cat_paid_salvage,
        try_cast(catsalvagepayment_lightning_col as double) as lightning_cause_of_loss__cat_paid_salvage,
        try_cast(catsalvagepayment_nonweather0001 as double) as non_weather_water_cause_of_loss__cat_paid_salvage,
        try_cast(catsalvagepayment_theft_col as double) as theft_cause_of_loss__cat_paid_salvage,
        try_cast(catsalvagepayment_weatherwat0001 as double) as weather_water_cause_of_loss__cat_paid_salvage,
        try_cast(catsalvagepayment_wind_col as double) as wind_cause_of_loss__cat_paid_salvage,
        try_cast(catsubropayment_allother_col as double) as all_other_causes_of_loss__cat_paid_subrogation,
        try_cast(catsubropayment_liability_col as double) as liability_cause_of_loss__cat_paid_subrogation,
        try_cast(catsubropayment_eq_col as double) as eq_cause_of_loss__cat_paid_subrogation,
        try_cast(catsubropayment_fire_col as double) as fire_cause_of_loss__cat_paid_subrogation,
        try_cast(catsubropayment_freezing_col as double) as freezing_cause_of_loss__cat_paid_subrogation,
        try_cast(catsubropayment_hail_col as double) as hail_cause_of_loss__cat_paid_subrogation,
        try_cast(catsubropayment_lightning_col as double) as lightning_cause_of_loss__cat_paid_subrogation,
        try_cast(catsubropayment_nonweatherwa0001 as double) as non_weather_water_cause_of_loss__cat_paid_subrogation,
        try_cast(catsubropayment_theft_col as double) as theft_cause_of_loss__cat_paid_subrogation,
        try_cast(catsubropayment_weatherwater_col as double) as weather_water_cause_of_loss__cat_paid_subrogation,
        try_cast(catsubropayment_wind_col as double) as wind_cause_of_loss__cat_paid_subrogation,
        try_cast(deductiblerecoveryreserve_grp1 as double) as group1__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_grp2 as double) as group2__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_other as double) as other__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_sp0001 as double) as special__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_eq as double) as eq__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_al0001 as double) as all_perils__deductible_recovery_reserve,
        try_cast(expensesreserve_grp1 as double) as group1__expenses_reserve,
        try_cast(expensesreserve_grp2 as double) as group2__expenses_reserve,
        try_cast(expensesreserve_other as double) as other__expenses_reserve,
        try_cast(expensesreserve_special as double) as special__expenses_reserve,
        try_cast(expensesreserve_eq as double) as eq__expenses_reserve,
        try_cast(expensesreserve_allperils as double) as all_perils__expenses_reserve,
        try_cast(expenserecoveryreserve_grp1 as double) as group1__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_grp2 as double) as group2__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_other as double) as other__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_special as double) as special__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_eq as double) as eq__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_allperils as double) as all_perils__expense_recovery_reserve,
        try_cast(lossreserve_grp1 as double) as group1__loss_reserve,
        try_cast(lossreserve_grp2 as double) as group2__loss_reserve,
        try_cast(lossreserve_other as double) as other__loss_reserve,
        try_cast(lossreserve_special as double) as special__loss_reserve,
        try_cast(lossreserve_eq as double) as eq__loss_reserve,
        try_cast(lossreserve_allperils as double) as all_perils__loss_reserve,
        try_cast(totalreserveamount_allperils as double) as all_perils__total_reserve,
        try_cast(catdeductiblerecoveryreserve0001 as double) as group1__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0002 as double) as group2__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0003 as double) as other__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0004 as double) as special__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve_eq as double) as eq__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0005 as double) as all_perils__cat_deductible_recovery_reserve,
        try_cast(catexpensesreserve_grp1 as double) as group1__cat_expenses_reserve,
        try_cast(catexpensesreserve_grp2 as double) as group2__cat_expenses_reserve,
        try_cast(catexpensesreserve_other as double) as other__cat_expenses_reserve,
        try_cast(catexpensesreserve_special as double) as special__cat_expenses_reserve,
        try_cast(catexpensesreserve_eq as double) as eq__cat_expenses_reserve,
        try_cast(catexpensesreserve_allperils as double) as all_perils__cat_expenses_reserve,
        try_cast(catexpenserecoveryreserve_grp1 as double) as group1__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_grp2 as double) as group2__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_other as double) as other__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_sp0001 as double) as special__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_eq as double) as eq__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_al0001 as double) as all_perils__cat_expense_recovery_reserve,
        try_cast(catlossreserve_grp1 as double) as group1__cat_loss_reserve,
        try_cast(catlossreserve_grp2 as double) as group2__cat_loss_reserve,
        try_cast(catlossreserve_other as double) as other__cat_loss_reserve,
        try_cast(catlossreserve_special as double) as special__cat_loss_reserve,
        try_cast(catlossreserve_eq as double) as eq__cat_loss_reserve,
        try_cast(catlossreserve_allperils as double) as all_perils__cat_loss_reserve,
        try_cast(cattotalreserveamount_allperils as double) as all_perils__cat_total_reserve,
        try_cast(deductiblerecoveryreserve_al0002 as double) as all_other_causes_of_loss__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_li0001 as double) as liability_cause_of_loss__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_eq_col as double) as eq_cause_of_loss__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_fi0001 as double) as fire_cause_of_loss__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_fr0001 as double) as freezing_cause_of_loss__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_ha0001 as double) as hail_cause_of_loss__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_li0002 as double) as lightning_cause_of_loss__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_no0001 as double) as non_weather_water_cause_of_loss__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_th0001 as double) as theft_cause_of_loss__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_we0001 as double) as weather_water_cause_of_loss__deductible_recovery_reserve,
        try_cast(deductiblerecoveryreserve_wi0001 as double) as wind_cause_of_loss__deductible_recovery_reserve,
        try_cast(expensesreserve_allother_col as double) as all_other_causes_of_loss__expenses_reserve,
        try_cast(expensesreserve_liability_col as double) as liability_cause_of_loss__expenses_reserve,
        try_cast(expensesreserve_eq_col as double) as eq_cause_of_loss__expenses_reserve,
        try_cast(expensesreserve_fire_col as double) as fire_cause_of_loss__expenses_reserve,
        try_cast(expensesreserve_freezing_col as double) as freezing_cause_of_loss__expenses_reserve,
        try_cast(expensesreserve_hail_col as double) as hail_cause_of_loss__expenses_reserve,
        try_cast(expensesreserve_lightning_col as double) as lightning_cause_of_loss__expenses_reserve,
        try_cast(expensesreserve_nonweatherwa0001 as double) as non_weather_water_cause_of_loss__expenses_reserve,
        try_cast(expensesreserve_theft_col as double) as theft_cause_of_loss__expenses_reserve,
        try_cast(expensesreserve_weatherwater_col as double) as weather_water_cause_of_loss__expenses_reserve,
        try_cast(expensesreserve_wind_col as double) as wind_cause_of_loss__expenses_reserve,
        try_cast(expenserecoveryreserve_allot0001 as double) as all_other_causes_of_loss__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_liabi0001 as double) as liability_cause_of_loss__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_eq_col as double) as eq_cause_of_loss__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_fire_col as double) as fire_cause_of_loss__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_freez0001 as double) as freezing_cause_of_loss__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_hail_col as double) as hail_cause_of_loss__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_light0001 as double) as lightning_cause_of_loss__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_nonwe0001 as double) as non_weather_water_cause_of_loss__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_theft_col as double) as theft_cause_of_loss__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_weath0001 as double) as weather_water_cause_of_loss__expense_recovery_reserve,
        try_cast(expenserecoveryreserve_wind_col as double) as wind_cause_of_loss__expense_recovery_reserve,
        try_cast(lossreserve_allother_col as double) as all_other_causes_of_loss__loss_reserve,
        try_cast(lossreserve_liability_col as double) as liability_cause_of_loss__loss_reserve,
        try_cast(lossreserve_eq_col as double) as eq_cause_of_loss__loss_reserve,
        try_cast(lossreserve_fire_col as double) as fire_cause_of_loss__loss_reserve,
        try_cast(lossreserve_freezing_col as double) as freezing_cause_of_loss__loss_reserve,
        try_cast(lossreserve_hail_col as double) as hail_cause_of_loss__loss_reserve,
        try_cast(lossreserve_lightning_col as double) as lightning_cause_of_loss__loss_reserve,
        try_cast(lossreserve_nonweatherwater_col as double) as non_weather_water_cause_of_loss__loss_reserve,
        try_cast(lossreserve_theft_col as double) as theft_cause_of_loss__loss_reserve,
        try_cast(lossreserve_weatherwater_col as double) as weather_water_cause_of_loss__loss_reserve,
        try_cast(lossreserve_wind_col as double) as wind_cause_of_loss__loss_reserve,
        try_cast(catdeductiblerecoveryreserve0006 as double) as all_other_causes_of_loss__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0007 as double) as liability_cause_of_loss__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0008 as double) as eq_cause_of_loss__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0009 as double) as fire_cause_of_loss__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0010 as double) as freezing_cause_of_loss__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0011 as double) as hail_cause_of_loss__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0012 as double) as lightning_cause_of_loss__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0013 as double) as non_weather_water_cause_of_loss__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0014 as double) as theft_cause_of_loss__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0015 as double) as weather_water_cause_of_loss__cat_deductible_recovery_reserve,
        try_cast(catdeductiblerecoveryreserve0016 as double) as wind_cause_of_loss__cat_deductible_recovery_reserve,
        try_cast(catexpensesreserve_allother_col as double) as all_other_causes_of_loss__cat_expenses_reserve,
        try_cast(catexpensesreserve_liability_col as double) as liability_cause_of_loss__cat_expenses_reserve,
        try_cast(catexpensesreserve_eq_col as double) as eq_cause_of_loss__cat_expenses_reserve,
        try_cast(catexpensesreserve_fire_col as double) as fire_cause_of_loss__cat_expenses_reserve,
        try_cast(catexpensesreserve_freezing_col as double) as freezing_cause_of_loss__cat_expenses_reserve,
        try_cast(catexpensesreserve_hail_col as double) as hail_cause_of_loss__cat_expenses_reserve,
        try_cast(catexpensesreserve_lightning_col as double) as lightning_cause_of_loss__cat_expenses_reserve,
        try_cast(catexpensesreserve_nonweathe0001 as double) as non_weather_water_cause_of_loss__cat_expenses_reserve,
        try_cast(catexpensesreserve_theft_col as double) as theft_cause_of_loss__cat_expenses_reserve,
        try_cast(catexpensesreserve_weatherwa0001 as double) as weather_water_cause_of_loss__cat_expenses_reserve,
        try_cast(catexpensesreserve_wind_col as double) as wind_cause_of_loss__cat_expenses_reserve,
        try_cast(catexpenserecoveryreserve_al0002 as double) as all_other_causes_of_loss__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_li0001 as double) as liability_cause_of_loss__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_eq_col as double) as eq_cause_of_loss__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_fi0001 as double) as fire_cause_of_loss__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_fr0001 as double) as freezing_cause_of_loss__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_ha0001 as double) as hail_cause_of_loss__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_li0002 as double) as lightning_cause_of_loss__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_no0001 as double) as non_weather_water_cause_of_loss__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_th0001 as double) as theft_cause_of_loss__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_we0001 as double) as weather_water_cause_of_loss__cat_expense_recovery_reserve,
        try_cast(catexpenserecoveryreserve_wi0001 as double) as wind_cause_of_loss__cat_expense_recovery_reserve,
        try_cast(catlossreserve_allother_col as double) as all_other_causes_of_loss__cat_loss_reserve,
        try_cast(catlossreserve_liability_col as double) as liability_cause_of_loss__cat_loss_reserve,
        try_cast(catlossreserve_eq_col as double) as eq_cause_of_loss__cat_loss_reserve,
        try_cast(catlossreserve_fire_col as double) as fire_cause_of_loss__cat_loss_reserve,
        try_cast(catlossreserve_freezing_col as double) as freezing_cause_of_loss__cat_loss_reserve,
        try_cast(catlossreserve_hail_col as double) as hail_cause_of_loss__cat_loss_reserve,
        try_cast(catlossreserve_lightning_col as double) as lightning_cause_of_loss__cat_loss_reserve,
        try_cast(catlossreserve_nonweatherwat0001 as double) as non_weather_water_cause_of_loss__cat_loss_reserve,
        try_cast(catlossreserve_theft_col as double) as theft_cause_of_loss__cat_loss_reserve,
        try_cast(catlossreserve_weatherwater_col as double) as weather_water_cause_of_loss__cat_loss_reserve,
        try_cast(catlossreserve_wind_col as double) as wind_cause_of_loss__cat_loss_reserve,
        try_cast(totalcoverage_caseincurredlo0001 as double) as total_coverage__case_incurred_loss,
        try_cast(property_case_incurred_loss_0001 as double) as property_case_incurred_loss1,
        try_cast(property_case_incurred_loss_0002 as double) as property_case_incurred_loss2,
        try_cast(property_case_incurred_loss_0003 as double) as property_case_incurred_loss3,
        try_cast(property_case_incurred_loss_0004 as double) as property_case_incurred_loss4,
        try_cast(property_case_incurred_loss_0005 as double) as property_case_incurred_loss5,
        try_cast(property_case_incurred_loss_0006 as double) as property_case_incurred_loss6

    from
        {{ source('exposure_views', 'cf_exposureview') }}

)

select * from raw