[project]
name = "predictables"
version = "0.0.1"
description = "A library for creating predictable objects"
readme = "README.md"
license = "MIT"
keywords = [
  "predictable",
  "object",
  "mock",
  "stub",
  "fake",
  "test",
  "testing",
  "unittest",
  "pytest",
  "mocking",
  "stubbing",
  "faking",
  "mocks",
  "stubs",
  "fakes",
  "unittests",
  "pytests",
]
authors = [{ name = "Andy Weaver" }]
maintainers = [{ name = "Andy Weaver" }, { name = "Andy Weaver" }]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"

[tool.hatchling]
