from .._config import get_config as get_config
from .fixes import parse_version as parse_version
from typing import Any

def device(x): ...
def size(x): ...
def isdtype(dtype, kind, *, xp): ...

class _ArrayAPIWrapper:
    def __init__(self, array_namespace) -> None: ...
    def __getattr__(self, name): ...
    def take(self, X, indices, *, axis: int = ...): ...
    def isdtype(self, dtype, kind): ...

class _NumPyAPIWrapper:
    def __getattr__(self, name): ...
    @property
    def bool(self): ...
    def astype(self, x, dtype, *, copy: bool = ..., casting: str = ...): ...
    def asarray(
        self,
        x,
        *,
        dtype: Any | None = ...,
        device: Any | None = ...,
        copy: Any | None = ...
    ): ...
    def unique_inverse(self, x): ...
    def unique_counts(self, x): ...
    def unique_values(self, x): ...
    def concat(self, arrays, *, axis: Any | None = ...): ...
    def reshape(self, x, shape, *, copy: Any | None = ...): ...
    def isdtype(self, dtype, kind): ...

def get_namespace(*arrays): ...
