class Bunch(dict):
    def __init__(self, **kwargs) -> None: ...
    def __getitem__(self, key): ...
    def __setattr__(self, key, value) -> None: ...
    def __dir__(self): ...
    def __getattr__(self, key): ...
