from typing import Any

check_random_state: function

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _our_rand_r_py(*args, **kwargs) -> Any: ...
def _sample_without_replacement_check_input(*args, **kwargs) -> Any: ...
def _sample_without_replacement_with_pool(*args, **kwargs) -> Any: ...
def _sample_without_replacement_with_reservoir_sampling(*args, **kwargs) -> Any: ...
def _sample_without_replacement_with_tracking_selection(*args, **kwargs) -> Any: ...
def sample_without_replacement(*args, **kwargs) -> Any: ...
