from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _murmurhash3_bytes_array_s32(*args, **kwargs) -> Any: ...
def _murmurhash3_bytes_array_u32(*args, **kwargs) -> Any: ...
def murmurhash3_32(*args, **kwargs) -> Any: ...
def murmurhash3_bytes_s32(*args, **kwargs) -> Any: ...
def murmurhash3_bytes_u32(*args, **kwargs) -> Any: ...
def murmurhash3_int_s32(*args, **kwargs) -> Any: ...
def murmurhash3_int_u32(*args, **kwargs) -> Any: ...
