from typing import Any

_csc_mean_variance_axis0: fused_cython_function
_csr_mean_variance_axis0: fused_cython_function
_incr_mean_variance_axis0: fused_cython_function
_inplace_csr_row_normalize_l1: fused_cython_function
_inplace_csr_row_normalize_l2: fused_cython_function
_sqeuclidean_row_norms_sparse: fused_cython_function
assign_rows_csr: fused_cython_function

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def csc_mean_variance_axis0(*args, **kwargs) -> Any: ...
def csr_mean_variance_axis0(*args, **kwargs) -> Any: ...
def csr_row_norms(*args, **kwargs) -> Any: ...
def incr_mean_variance_axis0(*args, **kwargs) -> Any: ...
def inplace_csr_row_normalize_l1(*args, **kwargs) -> Any: ...
def inplace_csr_row_normalize_l2(*args, **kwargs) -> Any: ...
