from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Cells(_BaseTraceHierarchyType):
    @property
    def align(self): ...
    @align.setter
    def align(self, val) -> None: ...
    @property
    def alignsrc(self): ...
    @alignsrc.setter
    def alignsrc(self, val) -> None: ...
    @property
    def fill(self): ...
    @fill.setter
    def fill(self, val) -> None: ...
    @property
    def font(self): ...
    @font.setter
    def font(self, val) -> None: ...
    @property
    def format(self): ...
    @format.setter
    def format(self, val) -> None: ...
    @property
    def formatsrc(self): ...
    @formatsrc.setter
    def formatsrc(self, val) -> None: ...
    @property
    def height(self): ...
    @height.setter
    def height(self, val) -> None: ...
    @property
    def line(self): ...
    @line.setter
    def line(self, val) -> None: ...
    @property
    def prefix(self): ...
    @prefix.setter
    def prefix(self, val) -> None: ...
    @property
    def prefixsrc(self): ...
    @prefixsrc.setter
    def prefixsrc(self, val) -> None: ...
    @property
    def suffix(self): ...
    @suffix.setter
    def suffix(self, val) -> None: ...
    @property
    def suffixsrc(self): ...
    @suffixsrc.setter
    def suffixsrc(self, val) -> None: ...
    @property
    def values(self): ...
    @values.setter
    def values(self, val) -> None: ...
    @property
    def valuessrc(self): ...
    @valuessrc.setter
    def valuessrc(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        align: Any | None = ...,
        alignsrc: Any | None = ...,
        fill: Any | None = ...,
        font: Any | None = ...,
        format: Any | None = ...,
        formatsrc: Any | None = ...,
        height: Any | None = ...,
        line: Any | None = ...,
        prefix: Any | None = ...,
        prefixsrc: Any | None = ...,
        suffix: Any | None = ...,
        suffixsrc: Any | None = ...,
        values: Any | None = ...,
        valuessrc: Any | None = ...,
        **kwargs
    ) -> None: ...
