from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def in_bitset_memoryview(*args, **kwargs) -> Any: ...
def set_bitset_memoryview(*args, **kwargs) -> Any: ...
def set_raw_bitset_from_binned_bitset(*args, **kwargs) -> Any: ...
