from typing import Any, ClassVar

import numpy.dtypes

HISTOGRAM_DTYPE: numpy.dtypes.VoidDType

class HistogramBuilder:
    X_binned: ClassVar[getset_descriptor] = ...
    gradients: ClassVar[getset_descriptor] = ...
    hessians: ClassVar[getset_descriptor] = ...
    hessians_are_constant: ClassVar[getset_descriptor] = ...
    n_bins: ClassVar[getset_descriptor] = ...
    n_features: ClassVar[getset_descriptor] = ...
    n_threads: ClassVar[getset_descriptor] = ...
    ordered_gradients: ClassVar[getset_descriptor] = ...
    ordered_hessians: ClassVar[getset_descriptor] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def compute_histograms_brute(self, *args, **kwargs) -> Any: ...
    def compute_histograms_subtraction(self, *args, **kwargs) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def __pyx_unpickle_HistogramBuilder(*args, **kwargs) -> Any: ...
def _build_histogram(*args, **kwargs) -> Any: ...
def _build_histogram_naive(*args, **kwargs) -> Any: ...
def _build_histogram_no_hessian(*args, **kwargs) -> Any: ...
def _build_histogram_root(*args, **kwargs) -> Any: ...
def _build_histogram_root_no_hessian(*args, **kwargs) -> Any: ...
def _subtract_histograms(*args, **kwargs) -> Any: ...
