from typing import Any, ClassVar

import sklearn.base

is_classifier: function

class _BinMapper(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator):
    __init__: ClassVar[function] = ...
    _sklearn_auto_wrap_output_keys: ClassVar[set] = ...
    fit: ClassVar[function] = ...
    make_known_categories_bitsets: ClassVar[function] = ...
    transform: ClassVar[function] = ...

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def get_equivalent_estimator(*args, **kwargs) -> Any: ...
def sum_parallel(*args, **kwargs) -> Any: ...
