from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Cluster(_BaseTraceHierarchyType):
    @property
    def color(self): ...
    @color.setter
    def color(self, val) -> None: ...
    @property
    def colorsrc(self): ...
    @colorsrc.setter
    def colorsrc(self, val) -> None: ...
    @property
    def enabled(self): ...
    @enabled.setter
    def enabled(self, val) -> None: ...
    @property
    def maxzoom(self): ...
    @maxzoom.setter
    def maxzoom(self, val) -> None: ...
    @property
    def opacity(self): ...
    @opacity.setter
    def opacity(self, val) -> None: ...
    @property
    def opacitysrc(self): ...
    @opacitysrc.setter
    def opacitysrc(self, val) -> None: ...
    @property
    def size(self): ...
    @size.setter
    def size(self, val) -> None: ...
    @property
    def sizesrc(self): ...
    @sizesrc.setter
    def sizesrc(self, val) -> None: ...
    @property
    def step(self): ...
    @step.setter
    def step(self, val) -> None: ...
    @property
    def stepsrc(self): ...
    @stepsrc.setter
    def stepsrc(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        color: Any | None = ...,
        colorsrc: Any | None = ...,
        enabled: Any | None = ...,
        maxzoom: Any | None = ...,
        opacity: Any | None = ...,
        opacitysrc: Any | None = ...,
        size: Any | None = ...,
        sizesrc: Any | None = ...,
        step: Any | None = ...,
        stepsrc: Any | None = ...,
        **kwargs
    ) -> None: ...
