from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Pathbar(_BaseTraceHierarchyType):
    @property
    def edgeshape(self): ...
    @edgeshape.setter
    def edgeshape(self, val) -> None: ...
    @property
    def side(self): ...
    @side.setter
    def side(self, val) -> None: ...
    @property
    def textfont(self): ...
    @textfont.setter
    def textfont(self, val) -> None: ...
    @property
    def thickness(self): ...
    @thickness.setter
    def thickness(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        edgeshape: Any | None = ...,
        side: Any | None = ...,
        textfont: Any | None = ...,
        thickness: Any | None = ...,
        visible: Any | None = ...,
        **kwargs
    ) -> None: ...
