from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Marker(_BaseTraceHierarchyType):
    @property
    def autocolorscale(self): ...
    @autocolorscale.setter
    def autocolorscale(self, val) -> None: ...
    @property
    def cauto(self): ...
    @cauto.setter
    def cauto(self, val) -> None: ...
    @property
    def cmax(self): ...
    @cmax.setter
    def cmax(self, val) -> None: ...
    @property
    def cmid(self): ...
    @cmid.setter
    def cmid(self, val) -> None: ...
    @property
    def cmin(self): ...
    @cmin.setter
    def cmin(self, val) -> None: ...
    @property
    def coloraxis(self): ...
    @coloraxis.setter
    def coloraxis(self, val) -> None: ...
    @property
    def colorbar(self): ...
    @colorbar.setter
    def colorbar(self, val) -> None: ...
    @property
    def colors(self): ...
    @colors.setter
    def colors(self, val) -> None: ...
    @property
    def colorscale(self): ...
    @colorscale.setter
    def colorscale(self, val) -> None: ...
    @property
    def colorssrc(self): ...
    @colorssrc.setter
    def colorssrc(self, val) -> None: ...
    @property
    def cornerradius(self): ...
    @cornerradius.setter
    def cornerradius(self, val) -> None: ...
    @property
    def depthfade(self): ...
    @depthfade.setter
    def depthfade(self, val) -> None: ...
    @property
    def line(self): ...
    @line.setter
    def line(self, val) -> None: ...
    @property
    def pad(self): ...
    @pad.setter
    def pad(self, val) -> None: ...
    @property
    def pattern(self): ...
    @pattern.setter
    def pattern(self, val) -> None: ...
    @property
    def reversescale(self): ...
    @reversescale.setter
    def reversescale(self, val) -> None: ...
    @property
    def showscale(self): ...
    @showscale.setter
    def showscale(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        autocolorscale: Any | None = ...,
        cauto: Any | None = ...,
        cmax: Any | None = ...,
        cmid: Any | None = ...,
        cmin: Any | None = ...,
        coloraxis: Any | None = ...,
        colorbar: Any | None = ...,
        colors: Any | None = ...,
        colorscale: Any | None = ...,
        colorssrc: Any | None = ...,
        cornerradius: Any | None = ...,
        depthfade: Any | None = ...,
        line: Any | None = ...,
        pad: Any | None = ...,
        pattern: Any | None = ...,
        reversescale: Any | None = ...,
        showscale: Any | None = ...,
        **kwargs
    ) -> None: ...
