from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Domain(_BaseLayoutHierarchyType):
    @property
    def column(self): ...
    @column.setter
    def column(self, val) -> None: ...
    @property
    def row(self): ...
    @row.setter
    def row(self, val) -> None: ...
    @property
    def x(self): ...
    @x.setter
    def x(self, val) -> None: ...
    @property
    def y(self): ...
    @y.setter
    def y(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        column: Any | None = ...,
        row: Any | None = ...,
        x: Any | None = ...,
        y: Any | None = ...,
        **kwargs
    ) -> None: ...
