from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class ColorBar(_BaseLayoutHierarchyType):
    @property
    def bgcolor(self): ...
    @bgcolor.setter
    def bgcolor(self, val) -> None: ...
    @property
    def bordercolor(self): ...
    @bordercolor.setter
    def bordercolor(self, val) -> None: ...
    @property
    def borderwidth(self): ...
    @borderwidth.setter
    def borderwidth(self, val) -> None: ...
    @property
    def dtick(self): ...
    @dtick.setter
    def dtick(self, val) -> None: ...
    @property
    def exponentformat(self): ...
    @exponentformat.setter
    def exponentformat(self, val) -> None: ...
    @property
    def labelalias(self): ...
    @labelalias.setter
    def labelalias(self, val) -> None: ...
    @property
    def len(self): ...
    @len.setter
    def len(self, val) -> None: ...
    @property
    def lenmode(self): ...
    @lenmode.setter
    def lenmode(self, val) -> None: ...
    @property
    def minexponent(self): ...
    @minexponent.setter
    def minexponent(self, val) -> None: ...
    @property
    def nticks(self): ...
    @nticks.setter
    def nticks(self, val) -> None: ...
    @property
    def orientation(self): ...
    @orientation.setter
    def orientation(self, val) -> None: ...
    @property
    def outlinecolor(self): ...
    @outlinecolor.setter
    def outlinecolor(self, val) -> None: ...
    @property
    def outlinewidth(self): ...
    @outlinewidth.setter
    def outlinewidth(self, val) -> None: ...
    @property
    def separatethousands(self): ...
    @separatethousands.setter
    def separatethousands(self, val) -> None: ...
    @property
    def showexponent(self): ...
    @showexponent.setter
    def showexponent(self, val) -> None: ...
    @property
    def showticklabels(self): ...
    @showticklabels.setter
    def showticklabels(self, val) -> None: ...
    @property
    def showtickprefix(self): ...
    @showtickprefix.setter
    def showtickprefix(self, val) -> None: ...
    @property
    def showticksuffix(self): ...
    @showticksuffix.setter
    def showticksuffix(self, val) -> None: ...
    @property
    def thickness(self): ...
    @thickness.setter
    def thickness(self, val) -> None: ...
    @property
    def thicknessmode(self): ...
    @thicknessmode.setter
    def thicknessmode(self, val) -> None: ...
    @property
    def tick0(self): ...
    @tick0.setter
    def tick0(self, val) -> None: ...
    @property
    def tickangle(self): ...
    @tickangle.setter
    def tickangle(self, val) -> None: ...
    @property
    def tickcolor(self): ...
    @tickcolor.setter
    def tickcolor(self, val) -> None: ...
    @property
    def tickfont(self): ...
    @tickfont.setter
    def tickfont(self, val) -> None: ...
    @property
    def tickformat(self): ...
    @tickformat.setter
    def tickformat(self, val) -> None: ...
    @property
    def tickformatstops(self): ...
    @tickformatstops.setter
    def tickformatstops(self, val) -> None: ...
    @property
    def tickformatstopdefaults(self): ...
    @tickformatstopdefaults.setter
    def tickformatstopdefaults(self, val) -> None: ...
    @property
    def ticklabeloverflow(self): ...
    @ticklabeloverflow.setter
    def ticklabeloverflow(self, val) -> None: ...
    @property
    def ticklabelposition(self): ...
    @ticklabelposition.setter
    def ticklabelposition(self, val) -> None: ...
    @property
    def ticklabelstep(self): ...
    @ticklabelstep.setter
    def ticklabelstep(self, val) -> None: ...
    @property
    def ticklen(self): ...
    @ticklen.setter
    def ticklen(self, val) -> None: ...
    @property
    def tickmode(self): ...
    @tickmode.setter
    def tickmode(self, val) -> None: ...
    @property
    def tickprefix(self): ...
    @tickprefix.setter
    def tickprefix(self, val) -> None: ...
    @property
    def ticks(self): ...
    @ticks.setter
    def ticks(self, val) -> None: ...
    @property
    def ticksuffix(self): ...
    @ticksuffix.setter
    def ticksuffix(self, val) -> None: ...
    @property
    def ticktext(self): ...
    @ticktext.setter
    def ticktext(self, val) -> None: ...
    @property
    def ticktextsrc(self): ...
    @ticktextsrc.setter
    def ticktextsrc(self, val) -> None: ...
    @property
    def tickvals(self): ...
    @tickvals.setter
    def tickvals(self, val) -> None: ...
    @property
    def tickvalssrc(self): ...
    @tickvalssrc.setter
    def tickvalssrc(self, val) -> None: ...
    @property
    def tickwidth(self): ...
    @tickwidth.setter
    def tickwidth(self, val) -> None: ...
    @property
    def title(self): ...
    @title.setter
    def title(self, val) -> None: ...
    @property
    def titlefont(self): ...
    @titlefont.setter
    def titlefont(self, val) -> None: ...
    @property
    def titleside(self): ...
    @titleside.setter
    def titleside(self, val) -> None: ...
    @property
    def x(self): ...
    @x.setter
    def x(self, val) -> None: ...
    @property
    def xanchor(self): ...
    @xanchor.setter
    def xanchor(self, val) -> None: ...
    @property
    def xpad(self): ...
    @xpad.setter
    def xpad(self, val) -> None: ...
    @property
    def xref(self): ...
    @xref.setter
    def xref(self, val) -> None: ...
    @property
    def y(self): ...
    @y.setter
    def y(self, val) -> None: ...
    @property
    def yanchor(self): ...
    @yanchor.setter
    def yanchor(self, val) -> None: ...
    @property
    def ypad(self): ...
    @ypad.setter
    def ypad(self, val) -> None: ...
    @property
    def yref(self): ...
    @yref.setter
    def yref(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        bgcolor: Any | None = ...,
        bordercolor: Any | None = ...,
        borderwidth: Any | None = ...,
        dtick: Any | None = ...,
        exponentformat: Any | None = ...,
        labelalias: Any | None = ...,
        len: Any | None = ...,
        lenmode: Any | None = ...,
        minexponent: Any | None = ...,
        nticks: Any | None = ...,
        orientation: Any | None = ...,
        outlinecolor: Any | None = ...,
        outlinewidth: Any | None = ...,
        separatethousands: Any | None = ...,
        showexponent: Any | None = ...,
        showticklabels: Any | None = ...,
        showtickprefix: Any | None = ...,
        showticksuffix: Any | None = ...,
        thickness: Any | None = ...,
        thicknessmode: Any | None = ...,
        tick0: Any | None = ...,
        tickangle: Any | None = ...,
        tickcolor: Any | None = ...,
        tickfont: Any | None = ...,
        tickformat: Any | None = ...,
        tickformatstops: Any | None = ...,
        tickformatstopdefaults: Any | None = ...,
        ticklabeloverflow: Any | None = ...,
        ticklabelposition: Any | None = ...,
        ticklabelstep: Any | None = ...,
        ticklen: Any | None = ...,
        tickmode: Any | None = ...,
        tickprefix: Any | None = ...,
        ticks: Any | None = ...,
        ticksuffix: Any | None = ...,
        ticktext: Any | None = ...,
        ticktextsrc: Any | None = ...,
        tickvals: Any | None = ...,
        tickvalssrc: Any | None = ...,
        tickwidth: Any | None = ...,
        title: Any | None = ...,
        titlefont: Any | None = ...,
        titleside: Any | None = ...,
        x: Any | None = ...,
        xanchor: Any | None = ...,
        xpad: Any | None = ...,
        xref: Any | None = ...,
        y: Any | None = ...,
        yanchor: Any | None = ...,
        ypad: Any | None = ...,
        yref: Any | None = ...,
        **kwargs
    ) -> None: ...
