from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Marker(_BaseTraceHierarchyType):
    @property
    def blend(self): ...
    @blend.setter
    def blend(self, val) -> None: ...
    @property
    def border(self): ...
    @border.setter
    def border(self, val) -> None: ...
    @property
    def color(self): ...
    @color.setter
    def color(self, val) -> None: ...
    @property
    def opacity(self): ...
    @opacity.setter
    def opacity(self, val) -> None: ...
    @property
    def sizemax(self): ...
    @sizemax.setter
    def sizemax(self, val) -> None: ...
    @property
    def sizemin(self): ...
    @sizemin.setter
    def sizemin(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        blend: Any | None = ...,
        border: Any | None = ...,
        color: Any | None = ...,
        opacity: Any | None = ...,
        sizemax: Any | None = ...,
        sizemin: Any | None = ...,
        **kwargs
    ) -> None: ...
