from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Bounds(_BaseLayoutHierarchyType):
    @property
    def east(self): ...
    @east.setter
    def east(self, val) -> None: ...
    @property
    def north(self): ...
    @north.setter
    def north(self, val) -> None: ...
    @property
    def south(self): ...
    @south.setter
    def south(self, val) -> None: ...
    @property
    def west(self): ...
    @west.setter
    def west(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        east: Any | None = ...,
        north: Any | None = ...,
        south: Any | None = ...,
        west: Any | None = ...,
        **kwargs
    ) -> None: ...
