from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Currentvalue(_BaseLayoutHierarchyType):
    @property
    def font(self): ...
    @font.setter
    def font(self, val) -> None: ...
    @property
    def offset(self): ...
    @offset.setter
    def offset(self, val) -> None: ...
    @property
    def prefix(self): ...
    @prefix.setter
    def prefix(self, val) -> None: ...
    @property
    def suffix(self): ...
    @suffix.setter
    def suffix(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    @property
    def xanchor(self): ...
    @xanchor.setter
    def xanchor(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        font: Any | None = ...,
        offset: Any | None = ...,
        prefix: Any | None = ...,
        suffix: Any | None = ...,
        visible: Any | None = ...,
        xanchor: Any | None = ...,
        **kwargs
    ) -> None: ...
