from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Lataxis(_BaseLayoutHierarchyType):
    @property
    def dtick(self): ...
    @dtick.setter
    def dtick(self, val) -> None: ...
    @property
    def gridcolor(self): ...
    @gridcolor.setter
    def gridcolor(self, val) -> None: ...
    @property
    def griddash(self): ...
    @griddash.setter
    def griddash(self, val) -> None: ...
    @property
    def gridwidth(self): ...
    @gridwidth.setter
    def gridwidth(self, val) -> None: ...
    @property
    def range(self): ...
    @range.setter
    def range(self, val) -> None: ...
    @property
    def showgrid(self): ...
    @showgrid.setter
    def showgrid(self, val) -> None: ...
    @property
    def tick0(self): ...
    @tick0.setter
    def tick0(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        dtick: Any | None = ...,
        gridcolor: Any | None = ...,
        griddash: Any | None = ...,
        gridwidth: Any | None = ...,
        range: Any | None = ...,
        showgrid: Any | None = ...,
        tick0: Any | None = ...,
        **kwargs
    ) -> None: ...
