from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Projection(_BaseLayoutHierarchyType):
    @property
    def distance(self): ...
    @distance.setter
    def distance(self, val) -> None: ...
    @property
    def parallels(self): ...
    @parallels.setter
    def parallels(self, val) -> None: ...
    @property
    def rotation(self): ...
    @rotation.setter
    def rotation(self, val) -> None: ...
    @property
    def scale(self): ...
    @scale.setter
    def scale(self, val) -> None: ...
    @property
    def tilt(self): ...
    @tilt.setter
    def tilt(self, val) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        distance: Any | None = ...,
        parallels: Any | None = ...,
        rotation: Any | None = ...,
        scale: Any | None = ...,
        tilt: Any | None = ...,
        type: Any | None = ...,
        **kwargs
    ) -> None: ...
