from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Marker(_BaseTraceHierarchyType):
    @property
    def colors(self): ...
    @colors.setter
    def colors(self, val) -> None: ...
    @property
    def colorssrc(self): ...
    @colorssrc.setter
    def colorssrc(self, val) -> None: ...
    @property
    def line(self): ...
    @line.setter
    def line(self, val) -> None: ...
    @property
    def pattern(self): ...
    @pattern.setter
    def pattern(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        colors: Any | None = ...,
        colorssrc: Any | None = ...,
        line: Any | None = ...,
        pattern: Any | None = ...,
        **kwargs
    ) -> None: ...
