from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Annotation(_BaseLayoutHierarchyType):
    @property
    def align(self): ...
    @align.setter
    def align(self, val) -> None: ...
    @property
    def arrowcolor(self): ...
    @arrowcolor.setter
    def arrowcolor(self, val) -> None: ...
    @property
    def arrowhead(self): ...
    @arrowhead.setter
    def arrowhead(self, val) -> None: ...
    @property
    def arrowside(self): ...
    @arrowside.setter
    def arrowside(self, val) -> None: ...
    @property
    def arrowsize(self): ...
    @arrowsize.setter
    def arrowsize(self, val) -> None: ...
    @property
    def arrowwidth(self): ...
    @arrowwidth.setter
    def arrowwidth(self, val) -> None: ...
    @property
    def ax(self): ...
    @ax.setter
    def ax(self, val) -> None: ...
    @property
    def ay(self): ...
    @ay.setter
    def ay(self, val) -> None: ...
    @property
    def bgcolor(self): ...
    @bgcolor.setter
    def bgcolor(self, val) -> None: ...
    @property
    def bordercolor(self): ...
    @bordercolor.setter
    def bordercolor(self, val) -> None: ...
    @property
    def borderpad(self): ...
    @borderpad.setter
    def borderpad(self, val) -> None: ...
    @property
    def borderwidth(self): ...
    @borderwidth.setter
    def borderwidth(self, val) -> None: ...
    @property
    def captureevents(self): ...
    @captureevents.setter
    def captureevents(self, val) -> None: ...
    @property
    def font(self): ...
    @font.setter
    def font(self, val) -> None: ...
    @property
    def height(self): ...
    @height.setter
    def height(self, val) -> None: ...
    @property
    def hoverlabel(self): ...
    @hoverlabel.setter
    def hoverlabel(self, val) -> None: ...
    @property
    def hovertext(self): ...
    @hovertext.setter
    def hovertext(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def opacity(self): ...
    @opacity.setter
    def opacity(self, val) -> None: ...
    @property
    def showarrow(self): ...
    @showarrow.setter
    def showarrow(self, val) -> None: ...
    @property
    def standoff(self): ...
    @standoff.setter
    def standoff(self, val) -> None: ...
    @property
    def startarrowhead(self): ...
    @startarrowhead.setter
    def startarrowhead(self, val) -> None: ...
    @property
    def startarrowsize(self): ...
    @startarrowsize.setter
    def startarrowsize(self, val) -> None: ...
    @property
    def startstandoff(self): ...
    @startstandoff.setter
    def startstandoff(self, val) -> None: ...
    @property
    def templateitemname(self): ...
    @templateitemname.setter
    def templateitemname(self, val) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, val) -> None: ...
    @property
    def textangle(self): ...
    @textangle.setter
    def textangle(self, val) -> None: ...
    @property
    def valign(self): ...
    @valign.setter
    def valign(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    @property
    def width(self): ...
    @width.setter
    def width(self, val) -> None: ...
    @property
    def x(self): ...
    @x.setter
    def x(self, val) -> None: ...
    @property
    def xanchor(self): ...
    @xanchor.setter
    def xanchor(self, val) -> None: ...
    @property
    def xshift(self): ...
    @xshift.setter
    def xshift(self, val) -> None: ...
    @property
    def y(self): ...
    @y.setter
    def y(self, val) -> None: ...
    @property
    def yanchor(self): ...
    @yanchor.setter
    def yanchor(self, val) -> None: ...
    @property
    def yshift(self): ...
    @yshift.setter
    def yshift(self, val) -> None: ...
    @property
    def z(self): ...
    @z.setter
    def z(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        align: Any | None = ...,
        arrowcolor: Any | None = ...,
        arrowhead: Any | None = ...,
        arrowside: Any | None = ...,
        arrowsize: Any | None = ...,
        arrowwidth: Any | None = ...,
        ax: Any | None = ...,
        ay: Any | None = ...,
        bgcolor: Any | None = ...,
        bordercolor: Any | None = ...,
        borderpad: Any | None = ...,
        borderwidth: Any | None = ...,
        captureevents: Any | None = ...,
        font: Any | None = ...,
        height: Any | None = ...,
        hoverlabel: Any | None = ...,
        hovertext: Any | None = ...,
        name: Any | None = ...,
        opacity: Any | None = ...,
        showarrow: Any | None = ...,
        standoff: Any | None = ...,
        startarrowhead: Any | None = ...,
        startarrowsize: Any | None = ...,
        startstandoff: Any | None = ...,
        templateitemname: Any | None = ...,
        text: Any | None = ...,
        textangle: Any | None = ...,
        valign: Any | None = ...,
        visible: Any | None = ...,
        width: Any | None = ...,
        x: Any | None = ...,
        xanchor: Any | None = ...,
        xshift: Any | None = ...,
        y: Any | None = ...,
        yanchor: Any | None = ...,
        yshift: Any | None = ...,
        z: Any | None = ...,
        **kwargs
    ) -> None: ...
