from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Camera(_BaseLayoutHierarchyType):
    @property
    def center(self): ...
    @center.setter
    def center(self, val) -> None: ...
    @property
    def eye(self): ...
    @eye.setter
    def eye(self, val) -> None: ...
    @property
    def projection(self): ...
    @projection.setter
    def projection(self, val) -> None: ...
    @property
    def up(self): ...
    @up.setter
    def up(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        center: Any | None = ...,
        eye: Any | None = ...,
        projection: Any | None = ...,
        up: Any | None = ...,
        **kwargs
    ) -> None: ...
