from plotly.basedatatypes import BaseTraceType as _BaseTraceType
from typing import Any

class Candlestick(_BaseTraceType):
    @property
    def close(self): ...
    @close.setter
    def close(self, val) -> None: ...
    @property
    def closesrc(self): ...
    @closesrc.setter
    def closesrc(self, val) -> None: ...
    @property
    def customdata(self): ...
    @customdata.setter
    def customdata(self, val) -> None: ...
    @property
    def customdatasrc(self): ...
    @customdatasrc.setter
    def customdatasrc(self, val) -> None: ...
    @property
    def decreasing(self): ...
    @decreasing.setter
    def decreasing(self, val) -> None: ...
    @property
    def high(self): ...
    @high.setter
    def high(self, val) -> None: ...
    @property
    def highsrc(self): ...
    @highsrc.setter
    def highsrc(self, val) -> None: ...
    @property
    def hoverinfo(self): ...
    @hoverinfo.setter
    def hoverinfo(self, val) -> None: ...
    @property
    def hoverinfosrc(self): ...
    @hoverinfosrc.setter
    def hoverinfosrc(self, val) -> None: ...
    @property
    def hoverlabel(self): ...
    @hoverlabel.setter
    def hoverlabel(self, val) -> None: ...
    @property
    def hovertext(self): ...
    @hovertext.setter
    def hovertext(self, val) -> None: ...
    @property
    def hovertextsrc(self): ...
    @hovertextsrc.setter
    def hovertextsrc(self, val) -> None: ...
    @property
    def ids(self): ...
    @ids.setter
    def ids(self, val) -> None: ...
    @property
    def idssrc(self): ...
    @idssrc.setter
    def idssrc(self, val) -> None: ...
    @property
    def increasing(self): ...
    @increasing.setter
    def increasing(self, val) -> None: ...
    @property
    def legend(self): ...
    @legend.setter
    def legend(self, val) -> None: ...
    @property
    def legendgroup(self): ...
    @legendgroup.setter
    def legendgroup(self, val) -> None: ...
    @property
    def legendgrouptitle(self): ...
    @legendgrouptitle.setter
    def legendgrouptitle(self, val) -> None: ...
    @property
    def legendrank(self): ...
    @legendrank.setter
    def legendrank(self, val) -> None: ...
    @property
    def legendwidth(self): ...
    @legendwidth.setter
    def legendwidth(self, val) -> None: ...
    @property
    def line(self): ...
    @line.setter
    def line(self, val) -> None: ...
    @property
    def low(self): ...
    @low.setter
    def low(self, val) -> None: ...
    @property
    def lowsrc(self): ...
    @lowsrc.setter
    def lowsrc(self, val) -> None: ...
    @property
    def meta(self): ...
    @meta.setter
    def meta(self, val) -> None: ...
    @property
    def metasrc(self): ...
    @metasrc.setter
    def metasrc(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def opacity(self): ...
    @opacity.setter
    def opacity(self, val) -> None: ...
    @property
    def open(self): ...
    @open.setter
    def open(self, val) -> None: ...
    @property
    def opensrc(self): ...
    @opensrc.setter
    def opensrc(self, val) -> None: ...
    @property
    def selectedpoints(self): ...
    @selectedpoints.setter
    def selectedpoints(self, val) -> None: ...
    @property
    def showlegend(self): ...
    @showlegend.setter
    def showlegend(self, val) -> None: ...
    @property
    def stream(self): ...
    @stream.setter
    def stream(self, val) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, val) -> None: ...
    @property
    def textsrc(self): ...
    @textsrc.setter
    def textsrc(self, val) -> None: ...
    @property
    def uid(self): ...
    @uid.setter
    def uid(self, val) -> None: ...
    @property
    def uirevision(self): ...
    @uirevision.setter
    def uirevision(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    @property
    def whiskerwidth(self): ...
    @whiskerwidth.setter
    def whiskerwidth(self, val) -> None: ...
    @property
    def x(self): ...
    @x.setter
    def x(self, val) -> None: ...
    @property
    def xaxis(self): ...
    @xaxis.setter
    def xaxis(self, val) -> None: ...
    @property
    def xcalendar(self): ...
    @xcalendar.setter
    def xcalendar(self, val) -> None: ...
    @property
    def xhoverformat(self): ...
    @xhoverformat.setter
    def xhoverformat(self, val) -> None: ...
    @property
    def xperiod(self): ...
    @xperiod.setter
    def xperiod(self, val) -> None: ...
    @property
    def xperiod0(self): ...
    @xperiod0.setter
    def xperiod0(self, val) -> None: ...
    @property
    def xperiodalignment(self): ...
    @xperiodalignment.setter
    def xperiodalignment(self, val) -> None: ...
    @property
    def xsrc(self): ...
    @xsrc.setter
    def xsrc(self, val) -> None: ...
    @property
    def yaxis(self): ...
    @yaxis.setter
    def yaxis(self, val) -> None: ...
    @property
    def yhoverformat(self): ...
    @yhoverformat.setter
    def yhoverformat(self, val) -> None: ...
    @property
    def type(self): ...
    def __init__(
        self,
        arg: Any | None = ...,
        close: Any | None = ...,
        closesrc: Any | None = ...,
        customdata: Any | None = ...,
        customdatasrc: Any | None = ...,
        decreasing: Any | None = ...,
        high: Any | None = ...,
        highsrc: Any | None = ...,
        hoverinfo: Any | None = ...,
        hoverinfosrc: Any | None = ...,
        hoverlabel: Any | None = ...,
        hovertext: Any | None = ...,
        hovertextsrc: Any | None = ...,
        ids: Any | None = ...,
        idssrc: Any | None = ...,
        increasing: Any | None = ...,
        legend: Any | None = ...,
        legendgroup: Any | None = ...,
        legendgrouptitle: Any | None = ...,
        legendrank: Any | None = ...,
        legendwidth: Any | None = ...,
        line: Any | None = ...,
        low: Any | None = ...,
        lowsrc: Any | None = ...,
        meta: Any | None = ...,
        metasrc: Any | None = ...,
        name: Any | None = ...,
        opacity: Any | None = ...,
        open: Any | None = ...,
        opensrc: Any | None = ...,
        selectedpoints: Any | None = ...,
        showlegend: Any | None = ...,
        stream: Any | None = ...,
        text: Any | None = ...,
        textsrc: Any | None = ...,
        uid: Any | None = ...,
        uirevision: Any | None = ...,
        visible: Any | None = ...,
        whiskerwidth: Any | None = ...,
        x: Any | None = ...,
        xaxis: Any | None = ...,
        xcalendar: Any | None = ...,
        xhoverformat: Any | None = ...,
        xperiod: Any | None = ...,
        xperiod0: Any | None = ...,
        xperiodalignment: Any | None = ...,
        xsrc: Any | None = ...,
        yaxis: Any | None = ...,
        yhoverformat: Any | None = ...,
        **kwargs
    ) -> None: ...
