from plotly.basedatatypes import BaseTraceType as _BaseTraceType
from typing import Any

class Carpet(_BaseTraceType):
    @property
    def a(self): ...
    @a.setter
    def a(self, val) -> None: ...
    @property
    def a0(self): ...
    @a0.setter
    def a0(self, val) -> None: ...
    @property
    def aaxis(self): ...
    @aaxis.setter
    def aaxis(self, val) -> None: ...
    @property
    def asrc(self): ...
    @asrc.setter
    def asrc(self, val) -> None: ...
    @property
    def b(self): ...
    @b.setter
    def b(self, val) -> None: ...
    @property
    def b0(self): ...
    @b0.setter
    def b0(self, val) -> None: ...
    @property
    def baxis(self): ...
    @baxis.setter
    def baxis(self, val) -> None: ...
    @property
    def bsrc(self): ...
    @bsrc.setter
    def bsrc(self, val) -> None: ...
    @property
    def carpet(self): ...
    @carpet.setter
    def carpet(self, val) -> None: ...
    @property
    def cheaterslope(self): ...
    @cheaterslope.setter
    def cheaterslope(self, val) -> None: ...
    @property
    def color(self): ...
    @color.setter
    def color(self, val) -> None: ...
    @property
    def customdata(self): ...
    @customdata.setter
    def customdata(self, val) -> None: ...
    @property
    def customdatasrc(self): ...
    @customdatasrc.setter
    def customdatasrc(self, val) -> None: ...
    @property
    def da(self): ...
    @da.setter
    def da(self, val) -> None: ...
    @property
    def db(self): ...
    @db.setter
    def db(self, val) -> None: ...
    @property
    def font(self): ...
    @font.setter
    def font(self, val) -> None: ...
    @property
    def ids(self): ...
    @ids.setter
    def ids(self, val) -> None: ...
    @property
    def idssrc(self): ...
    @idssrc.setter
    def idssrc(self, val) -> None: ...
    @property
    def legend(self): ...
    @legend.setter
    def legend(self, val) -> None: ...
    @property
    def legendgrouptitle(self): ...
    @legendgrouptitle.setter
    def legendgrouptitle(self, val) -> None: ...
    @property
    def legendrank(self): ...
    @legendrank.setter
    def legendrank(self, val) -> None: ...
    @property
    def legendwidth(self): ...
    @legendwidth.setter
    def legendwidth(self, val) -> None: ...
    @property
    def meta(self): ...
    @meta.setter
    def meta(self, val) -> None: ...
    @property
    def metasrc(self): ...
    @metasrc.setter
    def metasrc(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def opacity(self): ...
    @opacity.setter
    def opacity(self, val) -> None: ...
    @property
    def stream(self): ...
    @stream.setter
    def stream(self, val) -> None: ...
    @property
    def uid(self): ...
    @uid.setter
    def uid(self, val) -> None: ...
    @property
    def uirevision(self): ...
    @uirevision.setter
    def uirevision(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    @property
    def x(self): ...
    @x.setter
    def x(self, val) -> None: ...
    @property
    def xaxis(self): ...
    @xaxis.setter
    def xaxis(self, val) -> None: ...
    @property
    def xsrc(self): ...
    @xsrc.setter
    def xsrc(self, val) -> None: ...
    @property
    def y(self): ...
    @y.setter
    def y(self, val) -> None: ...
    @property
    def yaxis(self): ...
    @yaxis.setter
    def yaxis(self, val) -> None: ...
    @property
    def ysrc(self): ...
    @ysrc.setter
    def ysrc(self, val) -> None: ...
    @property
    def type(self): ...
    def __init__(
        self,
        arg: Any | None = ...,
        a: Any | None = ...,
        a0: Any | None = ...,
        aaxis: Any | None = ...,
        asrc: Any | None = ...,
        b: Any | None = ...,
        b0: Any | None = ...,
        baxis: Any | None = ...,
        bsrc: Any | None = ...,
        carpet: Any | None = ...,
        cheaterslope: Any | None = ...,
        color: Any | None = ...,
        customdata: Any | None = ...,
        customdatasrc: Any | None = ...,
        da: Any | None = ...,
        db: Any | None = ...,
        font: Any | None = ...,
        ids: Any | None = ...,
        idssrc: Any | None = ...,
        legend: Any | None = ...,
        legendgrouptitle: Any | None = ...,
        legendrank: Any | None = ...,
        legendwidth: Any | None = ...,
        meta: Any | None = ...,
        metasrc: Any | None = ...,
        name: Any | None = ...,
        opacity: Any | None = ...,
        stream: Any | None = ...,
        uid: Any | None = ...,
        uirevision: Any | None = ...,
        visible: Any | None = ...,
        x: Any | None = ...,
        xaxis: Any | None = ...,
        xsrc: Any | None = ...,
        y: Any | None = ...,
        yaxis: Any | None = ...,
        ysrc: Any | None = ...,
        **kwargs
    ) -> None: ...
