from plotly.basedatatypes import BaseTraceType as _BaseTraceType
from typing import Any

class Choropleth(_BaseTraceType):
    @property
    def autocolorscale(self): ...
    @autocolorscale.setter
    def autocolorscale(self, val) -> None: ...
    @property
    def coloraxis(self): ...
    @coloraxis.setter
    def coloraxis(self, val) -> None: ...
    @property
    def colorbar(self): ...
    @colorbar.setter
    def colorbar(self, val) -> None: ...
    @property
    def colorscale(self): ...
    @colorscale.setter
    def colorscale(self, val) -> None: ...
    @property
    def customdata(self): ...
    @customdata.setter
    def customdata(self, val) -> None: ...
    @property
    def customdatasrc(self): ...
    @customdatasrc.setter
    def customdatasrc(self, val) -> None: ...
    @property
    def featureidkey(self): ...
    @featureidkey.setter
    def featureidkey(self, val) -> None: ...
    @property
    def geo(self): ...
    @geo.setter
    def geo(self, val) -> None: ...
    @property
    def geojson(self): ...
    @geojson.setter
    def geojson(self, val) -> None: ...
    @property
    def hoverinfo(self): ...
    @hoverinfo.setter
    def hoverinfo(self, val) -> None: ...
    @property
    def hoverinfosrc(self): ...
    @hoverinfosrc.setter
    def hoverinfosrc(self, val) -> None: ...
    @property
    def hoverlabel(self): ...
    @hoverlabel.setter
    def hoverlabel(self, val) -> None: ...
    @property
    def hovertemplate(self): ...
    @hovertemplate.setter
    def hovertemplate(self, val) -> None: ...
    @property
    def hovertemplatesrc(self): ...
    @hovertemplatesrc.setter
    def hovertemplatesrc(self, val) -> None: ...
    @property
    def hovertext(self): ...
    @hovertext.setter
    def hovertext(self, val) -> None: ...
    @property
    def hovertextsrc(self): ...
    @hovertextsrc.setter
    def hovertextsrc(self, val) -> None: ...
    @property
    def ids(self): ...
    @ids.setter
    def ids(self, val) -> None: ...
    @property
    def idssrc(self): ...
    @idssrc.setter
    def idssrc(self, val) -> None: ...
    @property
    def legend(self): ...
    @legend.setter
    def legend(self, val) -> None: ...
    @property
    def legendgroup(self): ...
    @legendgroup.setter
    def legendgroup(self, val) -> None: ...
    @property
    def legendgrouptitle(self): ...
    @legendgrouptitle.setter
    def legendgrouptitle(self, val) -> None: ...
    @property
    def legendrank(self): ...
    @legendrank.setter
    def legendrank(self, val) -> None: ...
    @property
    def legendwidth(self): ...
    @legendwidth.setter
    def legendwidth(self, val) -> None: ...
    @property
    def locationmode(self): ...
    @locationmode.setter
    def locationmode(self, val) -> None: ...
    @property
    def locations(self): ...
    @locations.setter
    def locations(self, val) -> None: ...
    @property
    def locationssrc(self): ...
    @locationssrc.setter
    def locationssrc(self, val) -> None: ...
    @property
    def marker(self): ...
    @marker.setter
    def marker(self, val) -> None: ...
    @property
    def meta(self): ...
    @meta.setter
    def meta(self, val) -> None: ...
    @property
    def metasrc(self): ...
    @metasrc.setter
    def metasrc(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def reversescale(self): ...
    @reversescale.setter
    def reversescale(self, val) -> None: ...
    @property
    def selected(self): ...
    @selected.setter
    def selected(self, val) -> None: ...
    @property
    def selectedpoints(self): ...
    @selectedpoints.setter
    def selectedpoints(self, val) -> None: ...
    @property
    def showlegend(self): ...
    @showlegend.setter
    def showlegend(self, val) -> None: ...
    @property
    def showscale(self): ...
    @showscale.setter
    def showscale(self, val) -> None: ...
    @property
    def stream(self): ...
    @stream.setter
    def stream(self, val) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, val) -> None: ...
    @property
    def textsrc(self): ...
    @textsrc.setter
    def textsrc(self, val) -> None: ...
    @property
    def uid(self): ...
    @uid.setter
    def uid(self, val) -> None: ...
    @property
    def uirevision(self): ...
    @uirevision.setter
    def uirevision(self, val) -> None: ...
    @property
    def unselected(self): ...
    @unselected.setter
    def unselected(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    @property
    def z(self): ...
    @z.setter
    def z(self, val) -> None: ...
    @property
    def zauto(self): ...
    @zauto.setter
    def zauto(self, val) -> None: ...
    @property
    def zmax(self): ...
    @zmax.setter
    def zmax(self, val) -> None: ...
    @property
    def zmid(self): ...
    @zmid.setter
    def zmid(self, val) -> None: ...
    @property
    def zmin(self): ...
    @zmin.setter
    def zmin(self, val) -> None: ...
    @property
    def zsrc(self): ...
    @zsrc.setter
    def zsrc(self, val) -> None: ...
    @property
    def type(self): ...
    def __init__(
        self,
        arg: Any | None = ...,
        autocolorscale: Any | None = ...,
        coloraxis: Any | None = ...,
        colorbar: Any | None = ...,
        colorscale: Any | None = ...,
        customdata: Any | None = ...,
        customdatasrc: Any | None = ...,
        featureidkey: Any | None = ...,
        geo: Any | None = ...,
        geojson: Any | None = ...,
        hoverinfo: Any | None = ...,
        hoverinfosrc: Any | None = ...,
        hoverlabel: Any | None = ...,
        hovertemplate: Any | None = ...,
        hovertemplatesrc: Any | None = ...,
        hovertext: Any | None = ...,
        hovertextsrc: Any | None = ...,
        ids: Any | None = ...,
        idssrc: Any | None = ...,
        legend: Any | None = ...,
        legendgroup: Any | None = ...,
        legendgrouptitle: Any | None = ...,
        legendrank: Any | None = ...,
        legendwidth: Any | None = ...,
        locationmode: Any | None = ...,
        locations: Any | None = ...,
        locationssrc: Any | None = ...,
        marker: Any | None = ...,
        meta: Any | None = ...,
        metasrc: Any | None = ...,
        name: Any | None = ...,
        reversescale: Any | None = ...,
        selected: Any | None = ...,
        selectedpoints: Any | None = ...,
        showlegend: Any | None = ...,
        showscale: Any | None = ...,
        stream: Any | None = ...,
        text: Any | None = ...,
        textsrc: Any | None = ...,
        uid: Any | None = ...,
        uirevision: Any | None = ...,
        unselected: Any | None = ...,
        visible: Any | None = ...,
        z: Any | None = ...,
        zauto: Any | None = ...,
        zmax: Any | None = ...,
        zmid: Any | None = ...,
        zmin: Any | None = ...,
        zsrc: Any | None = ...,
        **kwargs
    ) -> None: ...
