from plotly.basedatatypes import BaseTraceType as _BaseTraceType
from typing import Any

class Contourcarpet(_BaseTraceType):
    @property
    def a(self): ...
    @a.setter
    def a(self, val) -> None: ...
    @property
    def a0(self): ...
    @a0.setter
    def a0(self, val) -> None: ...
    @property
    def asrc(self): ...
    @asrc.setter
    def asrc(self, val) -> None: ...
    @property
    def atype(self): ...
    @atype.setter
    def atype(self, val) -> None: ...
    @property
    def autocolorscale(self): ...
    @autocolorscale.setter
    def autocolorscale(self, val) -> None: ...
    @property
    def autocontour(self): ...
    @autocontour.setter
    def autocontour(self, val) -> None: ...
    @property
    def b(self): ...
    @b.setter
    def b(self, val) -> None: ...
    @property
    def b0(self): ...
    @b0.setter
    def b0(self, val) -> None: ...
    @property
    def bsrc(self): ...
    @bsrc.setter
    def bsrc(self, val) -> None: ...
    @property
    def btype(self): ...
    @btype.setter
    def btype(self, val) -> None: ...
    @property
    def carpet(self): ...
    @carpet.setter
    def carpet(self, val) -> None: ...
    @property
    def coloraxis(self): ...
    @coloraxis.setter
    def coloraxis(self, val) -> None: ...
    @property
    def colorbar(self): ...
    @colorbar.setter
    def colorbar(self, val) -> None: ...
    @property
    def colorscale(self): ...
    @colorscale.setter
    def colorscale(self, val) -> None: ...
    @property
    def contours(self): ...
    @contours.setter
    def contours(self, val) -> None: ...
    @property
    def customdata(self): ...
    @customdata.setter
    def customdata(self, val) -> None: ...
    @property
    def customdatasrc(self): ...
    @customdatasrc.setter
    def customdatasrc(self, val) -> None: ...
    @property
    def da(self): ...
    @da.setter
    def da(self, val) -> None: ...
    @property
    def db(self): ...
    @db.setter
    def db(self, val) -> None: ...
    @property
    def fillcolor(self): ...
    @fillcolor.setter
    def fillcolor(self, val) -> None: ...
    @property
    def hovertext(self): ...
    @hovertext.setter
    def hovertext(self, val) -> None: ...
    @property
    def hovertextsrc(self): ...
    @hovertextsrc.setter
    def hovertextsrc(self, val) -> None: ...
    @property
    def ids(self): ...
    @ids.setter
    def ids(self, val) -> None: ...
    @property
    def idssrc(self): ...
    @idssrc.setter
    def idssrc(self, val) -> None: ...
    @property
    def legend(self): ...
    @legend.setter
    def legend(self, val) -> None: ...
    @property
    def legendgroup(self): ...
    @legendgroup.setter
    def legendgroup(self, val) -> None: ...
    @property
    def legendgrouptitle(self): ...
    @legendgrouptitle.setter
    def legendgrouptitle(self, val) -> None: ...
    @property
    def legendrank(self): ...
    @legendrank.setter
    def legendrank(self, val) -> None: ...
    @property
    def legendwidth(self): ...
    @legendwidth.setter
    def legendwidth(self, val) -> None: ...
    @property
    def line(self): ...
    @line.setter
    def line(self, val) -> None: ...
    @property
    def meta(self): ...
    @meta.setter
    def meta(self, val) -> None: ...
    @property
    def metasrc(self): ...
    @metasrc.setter
    def metasrc(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def ncontours(self): ...
    @ncontours.setter
    def ncontours(self, val) -> None: ...
    @property
    def opacity(self): ...
    @opacity.setter
    def opacity(self, val) -> None: ...
    @property
    def reversescale(self): ...
    @reversescale.setter
    def reversescale(self, val) -> None: ...
    @property
    def showlegend(self): ...
    @showlegend.setter
    def showlegend(self, val) -> None: ...
    @property
    def showscale(self): ...
    @showscale.setter
    def showscale(self, val) -> None: ...
    @property
    def stream(self): ...
    @stream.setter
    def stream(self, val) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, val) -> None: ...
    @property
    def textsrc(self): ...
    @textsrc.setter
    def textsrc(self, val) -> None: ...
    @property
    def transpose(self): ...
    @transpose.setter
    def transpose(self, val) -> None: ...
    @property
    def uid(self): ...
    @uid.setter
    def uid(self, val) -> None: ...
    @property
    def uirevision(self): ...
    @uirevision.setter
    def uirevision(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    @property
    def xaxis(self): ...
    @xaxis.setter
    def xaxis(self, val) -> None: ...
    @property
    def yaxis(self): ...
    @yaxis.setter
    def yaxis(self, val) -> None: ...
    @property
    def z(self): ...
    @z.setter
    def z(self, val) -> None: ...
    @property
    def zauto(self): ...
    @zauto.setter
    def zauto(self, val) -> None: ...
    @property
    def zmax(self): ...
    @zmax.setter
    def zmax(self, val) -> None: ...
    @property
    def zmid(self): ...
    @zmid.setter
    def zmid(self, val) -> None: ...
    @property
    def zmin(self): ...
    @zmin.setter
    def zmin(self, val) -> None: ...
    @property
    def zsrc(self): ...
    @zsrc.setter
    def zsrc(self, val) -> None: ...
    @property
    def type(self): ...
    def __init__(
        self,
        arg: Any | None = ...,
        a: Any | None = ...,
        a0: Any | None = ...,
        asrc: Any | None = ...,
        atype: Any | None = ...,
        autocolorscale: Any | None = ...,
        autocontour: Any | None = ...,
        b: Any | None = ...,
        b0: Any | None = ...,
        bsrc: Any | None = ...,
        btype: Any | None = ...,
        carpet: Any | None = ...,
        coloraxis: Any | None = ...,
        colorbar: Any | None = ...,
        colorscale: Any | None = ...,
        contours: Any | None = ...,
        customdata: Any | None = ...,
        customdatasrc: Any | None = ...,
        da: Any | None = ...,
        db: Any | None = ...,
        fillcolor: Any | None = ...,
        hovertext: Any | None = ...,
        hovertextsrc: Any | None = ...,
        ids: Any | None = ...,
        idssrc: Any | None = ...,
        legend: Any | None = ...,
        legendgroup: Any | None = ...,
        legendgrouptitle: Any | None = ...,
        legendrank: Any | None = ...,
        legendwidth: Any | None = ...,
        line: Any | None = ...,
        meta: Any | None = ...,
        metasrc: Any | None = ...,
        name: Any | None = ...,
        ncontours: Any | None = ...,
        opacity: Any | None = ...,
        reversescale: Any | None = ...,
        showlegend: Any | None = ...,
        showscale: Any | None = ...,
        stream: Any | None = ...,
        text: Any | None = ...,
        textsrc: Any | None = ...,
        transpose: Any | None = ...,
        uid: Any | None = ...,
        uirevision: Any | None = ...,
        visible: Any | None = ...,
        xaxis: Any | None = ...,
        yaxis: Any | None = ...,
        z: Any | None = ...,
        zauto: Any | None = ...,
        zmax: Any | None = ...,
        zmid: Any | None = ...,
        zmin: Any | None = ...,
        zsrc: Any | None = ...,
        **kwargs
    ) -> None: ...
