class Data(list):
    def __init__(self, *args, **kwargs) -> None: ...

class Annotations(list):
    def __init__(self, *args, **kwargs) -> None: ...

class Frames(list):
    def __init__(self, *args, **kwargs) -> None: ...

class AngularAxis(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class Annotation(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class ColorBar(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class Contours(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class ErrorX(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class ErrorY(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class ErrorZ(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class Font(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class Legend(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class Line(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class Margin(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class Marker(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class RadialAxis(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class Scene(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class Stream(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class XAxis(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class YAxis(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class ZAxis(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class XBins(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class YBins(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class Trace(dict):
    def __init__(self, *args, **kwargs) -> None: ...

class Histogram2dcontour(dict):
    def __init__(self, *args, **kwargs) -> None: ...
