from plotly.basedatatypes import BaseFrameHierarchyType as _BaseFrameHierarchyType
from typing import Any

class Frame(_BaseFrameHierarchyType):
    @property
    def baseframe(self): ...
    @baseframe.setter
    def baseframe(self, val) -> None: ...
    @property
    def data(self): ...
    @data.setter
    def data(self, val) -> None: ...
    @property
    def group(self): ...
    @group.setter
    def group(self, val) -> None: ...
    @property
    def layout(self): ...
    @layout.setter
    def layout(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def traces(self): ...
    @traces.setter
    def traces(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        baseframe: Any | None = ...,
        data: Any | None = ...,
        group: Any | None = ...,
        layout: Any | None = ...,
        name: Any | None = ...,
        traces: Any | None = ...,
        **kwargs
    ) -> None: ...
