from plotly.basedatatypes import BaseTraceType as _BaseTraceType
from typing import Any

class Histogram2dContour(_BaseTraceType):
    @property
    def autobinx(self): ...
    @autobinx.setter
    def autobinx(self, val) -> None: ...
    @property
    def autobiny(self): ...
    @autobiny.setter
    def autobiny(self, val) -> None: ...
    @property
    def autocolorscale(self): ...
    @autocolorscale.setter
    def autocolorscale(self, val) -> None: ...
    @property
    def autocontour(self): ...
    @autocontour.setter
    def autocontour(self, val) -> None: ...
    @property
    def bingroup(self): ...
    @bingroup.setter
    def bingroup(self, val) -> None: ...
    @property
    def coloraxis(self): ...
    @coloraxis.setter
    def coloraxis(self, val) -> None: ...
    @property
    def colorbar(self): ...
    @colorbar.setter
    def colorbar(self, val) -> None: ...
    @property
    def colorscale(self): ...
    @colorscale.setter
    def colorscale(self, val) -> None: ...
    @property
    def contours(self): ...
    @contours.setter
    def contours(self, val) -> None: ...
    @property
    def customdata(self): ...
    @customdata.setter
    def customdata(self, val) -> None: ...
    @property
    def customdatasrc(self): ...
    @customdatasrc.setter
    def customdatasrc(self, val) -> None: ...
    @property
    def histfunc(self): ...
    @histfunc.setter
    def histfunc(self, val) -> None: ...
    @property
    def histnorm(self): ...
    @histnorm.setter
    def histnorm(self, val) -> None: ...
    @property
    def hoverinfo(self): ...
    @hoverinfo.setter
    def hoverinfo(self, val) -> None: ...
    @property
    def hoverinfosrc(self): ...
    @hoverinfosrc.setter
    def hoverinfosrc(self, val) -> None: ...
    @property
    def hoverlabel(self): ...
    @hoverlabel.setter
    def hoverlabel(self, val) -> None: ...
    @property
    def hovertemplate(self): ...
    @hovertemplate.setter
    def hovertemplate(self, val) -> None: ...
    @property
    def hovertemplatesrc(self): ...
    @hovertemplatesrc.setter
    def hovertemplatesrc(self, val) -> None: ...
    @property
    def ids(self): ...
    @ids.setter
    def ids(self, val) -> None: ...
    @property
    def idssrc(self): ...
    @idssrc.setter
    def idssrc(self, val) -> None: ...
    @property
    def legend(self): ...
    @legend.setter
    def legend(self, val) -> None: ...
    @property
    def legendgroup(self): ...
    @legendgroup.setter
    def legendgroup(self, val) -> None: ...
    @property
    def legendgrouptitle(self): ...
    @legendgrouptitle.setter
    def legendgrouptitle(self, val) -> None: ...
    @property
    def legendrank(self): ...
    @legendrank.setter
    def legendrank(self, val) -> None: ...
    @property
    def legendwidth(self): ...
    @legendwidth.setter
    def legendwidth(self, val) -> None: ...
    @property
    def line(self): ...
    @line.setter
    def line(self, val) -> None: ...
    @property
    def marker(self): ...
    @marker.setter
    def marker(self, val) -> None: ...
    @property
    def meta(self): ...
    @meta.setter
    def meta(self, val) -> None: ...
    @property
    def metasrc(self): ...
    @metasrc.setter
    def metasrc(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def nbinsx(self): ...
    @nbinsx.setter
    def nbinsx(self, val) -> None: ...
    @property
    def nbinsy(self): ...
    @nbinsy.setter
    def nbinsy(self, val) -> None: ...
    @property
    def ncontours(self): ...
    @ncontours.setter
    def ncontours(self, val) -> None: ...
    @property
    def opacity(self): ...
    @opacity.setter
    def opacity(self, val) -> None: ...
    @property
    def reversescale(self): ...
    @reversescale.setter
    def reversescale(self, val) -> None: ...
    @property
    def showlegend(self): ...
    @showlegend.setter
    def showlegend(self, val) -> None: ...
    @property
    def showscale(self): ...
    @showscale.setter
    def showscale(self, val) -> None: ...
    @property
    def stream(self): ...
    @stream.setter
    def stream(self, val) -> None: ...
    @property
    def textfont(self): ...
    @textfont.setter
    def textfont(self, val) -> None: ...
    @property
    def texttemplate(self): ...
    @texttemplate.setter
    def texttemplate(self, val) -> None: ...
    @property
    def uid(self): ...
    @uid.setter
    def uid(self, val) -> None: ...
    @property
    def uirevision(self): ...
    @uirevision.setter
    def uirevision(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    @property
    def x(self): ...
    @x.setter
    def x(self, val) -> None: ...
    @property
    def xaxis(self): ...
    @xaxis.setter
    def xaxis(self, val) -> None: ...
    @property
    def xbingroup(self): ...
    @xbingroup.setter
    def xbingroup(self, val) -> None: ...
    @property
    def xbins(self): ...
    @xbins.setter
    def xbins(self, val) -> None: ...
    @property
    def xcalendar(self): ...
    @xcalendar.setter
    def xcalendar(self, val) -> None: ...
    @property
    def xhoverformat(self): ...
    @xhoverformat.setter
    def xhoverformat(self, val) -> None: ...
    @property
    def xsrc(self): ...
    @xsrc.setter
    def xsrc(self, val) -> None: ...
    @property
    def y(self): ...
    @y.setter
    def y(self, val) -> None: ...
    @property
    def yaxis(self): ...
    @yaxis.setter
    def yaxis(self, val) -> None: ...
    @property
    def ybingroup(self): ...
    @ybingroup.setter
    def ybingroup(self, val) -> None: ...
    @property
    def ybins(self): ...
    @ybins.setter
    def ybins(self, val) -> None: ...
    @property
    def ycalendar(self): ...
    @ycalendar.setter
    def ycalendar(self, val) -> None: ...
    @property
    def yhoverformat(self): ...
    @yhoverformat.setter
    def yhoverformat(self, val) -> None: ...
    @property
    def ysrc(self): ...
    @ysrc.setter
    def ysrc(self, val) -> None: ...
    @property
    def z(self): ...
    @z.setter
    def z(self, val) -> None: ...
    @property
    def zauto(self): ...
    @zauto.setter
    def zauto(self, val) -> None: ...
    @property
    def zhoverformat(self): ...
    @zhoverformat.setter
    def zhoverformat(self, val) -> None: ...
    @property
    def zmax(self): ...
    @zmax.setter
    def zmax(self, val) -> None: ...
    @property
    def zmid(self): ...
    @zmid.setter
    def zmid(self, val) -> None: ...
    @property
    def zmin(self): ...
    @zmin.setter
    def zmin(self, val) -> None: ...
    @property
    def zsrc(self): ...
    @zsrc.setter
    def zsrc(self, val) -> None: ...
    @property
    def type(self): ...
    def __init__(
        self,
        arg: Any | None = ...,
        autobinx: Any | None = ...,
        autobiny: Any | None = ...,
        autocolorscale: Any | None = ...,
        autocontour: Any | None = ...,
        bingroup: Any | None = ...,
        coloraxis: Any | None = ...,
        colorbar: Any | None = ...,
        colorscale: Any | None = ...,
        contours: Any | None = ...,
        customdata: Any | None = ...,
        customdatasrc: Any | None = ...,
        histfunc: Any | None = ...,
        histnorm: Any | None = ...,
        hoverinfo: Any | None = ...,
        hoverinfosrc: Any | None = ...,
        hoverlabel: Any | None = ...,
        hovertemplate: Any | None = ...,
        hovertemplatesrc: Any | None = ...,
        ids: Any | None = ...,
        idssrc: Any | None = ...,
        legend: Any | None = ...,
        legendgroup: Any | None = ...,
        legendgrouptitle: Any | None = ...,
        legendrank: Any | None = ...,
        legendwidth: Any | None = ...,
        line: Any | None = ...,
        marker: Any | None = ...,
        meta: Any | None = ...,
        metasrc: Any | None = ...,
        name: Any | None = ...,
        nbinsx: Any | None = ...,
        nbinsy: Any | None = ...,
        ncontours: Any | None = ...,
        opacity: Any | None = ...,
        reversescale: Any | None = ...,
        showlegend: Any | None = ...,
        showscale: Any | None = ...,
        stream: Any | None = ...,
        textfont: Any | None = ...,
        texttemplate: Any | None = ...,
        uid: Any | None = ...,
        uirevision: Any | None = ...,
        visible: Any | None = ...,
        x: Any | None = ...,
        xaxis: Any | None = ...,
        xbingroup: Any | None = ...,
        xbins: Any | None = ...,
        xcalendar: Any | None = ...,
        xhoverformat: Any | None = ...,
        xsrc: Any | None = ...,
        y: Any | None = ...,
        yaxis: Any | None = ...,
        ybingroup: Any | None = ...,
        ybins: Any | None = ...,
        ycalendar: Any | None = ...,
        yhoverformat: Any | None = ...,
        ysrc: Any | None = ...,
        z: Any | None = ...,
        zauto: Any | None = ...,
        zhoverformat: Any | None = ...,
        zmax: Any | None = ...,
        zmid: Any | None = ...,
        zmin: Any | None = ...,
        zsrc: Any | None = ...,
        **kwargs
    ) -> None: ...
