from plotly.basedatatypes import BaseTraceType as _BaseTraceType
from typing import Any

class Histogram(_BaseTraceType):
    @property
    def alignmentgroup(self): ...
    @alignmentgroup.setter
    def alignmentgroup(self, val) -> None: ...
    @property
    def autobinx(self): ...
    @autobinx.setter
    def autobinx(self, val) -> None: ...
    @property
    def autobiny(self): ...
    @autobiny.setter
    def autobiny(self, val) -> None: ...
    @property
    def bingroup(self): ...
    @bingroup.setter
    def bingroup(self, val) -> None: ...
    @property
    def cliponaxis(self): ...
    @cliponaxis.setter
    def cliponaxis(self, val) -> None: ...
    @property
    def constraintext(self): ...
    @constraintext.setter
    def constraintext(self, val) -> None: ...
    @property
    def cumulative(self): ...
    @cumulative.setter
    def cumulative(self, val) -> None: ...
    @property
    def customdata(self): ...
    @customdata.setter
    def customdata(self, val) -> None: ...
    @property
    def customdatasrc(self): ...
    @customdatasrc.setter
    def customdatasrc(self, val) -> None: ...
    @property
    def error_x(self): ...
    @error_x.setter
    def error_x(self, val) -> None: ...
    @property
    def error_y(self): ...
    @error_y.setter
    def error_y(self, val) -> None: ...
    @property
    def histfunc(self): ...
    @histfunc.setter
    def histfunc(self, val) -> None: ...
    @property
    def histnorm(self): ...
    @histnorm.setter
    def histnorm(self, val) -> None: ...
    @property
    def hoverinfo(self): ...
    @hoverinfo.setter
    def hoverinfo(self, val) -> None: ...
    @property
    def hoverinfosrc(self): ...
    @hoverinfosrc.setter
    def hoverinfosrc(self, val) -> None: ...
    @property
    def hoverlabel(self): ...
    @hoverlabel.setter
    def hoverlabel(self, val) -> None: ...
    @property
    def hovertemplate(self): ...
    @hovertemplate.setter
    def hovertemplate(self, val) -> None: ...
    @property
    def hovertemplatesrc(self): ...
    @hovertemplatesrc.setter
    def hovertemplatesrc(self, val) -> None: ...
    @property
    def hovertext(self): ...
    @hovertext.setter
    def hovertext(self, val) -> None: ...
    @property
    def hovertextsrc(self): ...
    @hovertextsrc.setter
    def hovertextsrc(self, val) -> None: ...
    @property
    def ids(self): ...
    @ids.setter
    def ids(self, val) -> None: ...
    @property
    def idssrc(self): ...
    @idssrc.setter
    def idssrc(self, val) -> None: ...
    @property
    def insidetextanchor(self): ...
    @insidetextanchor.setter
    def insidetextanchor(self, val) -> None: ...
    @property
    def insidetextfont(self): ...
    @insidetextfont.setter
    def insidetextfont(self, val) -> None: ...
    @property
    def legend(self): ...
    @legend.setter
    def legend(self, val) -> None: ...
    @property
    def legendgroup(self): ...
    @legendgroup.setter
    def legendgroup(self, val) -> None: ...
    @property
    def legendgrouptitle(self): ...
    @legendgrouptitle.setter
    def legendgrouptitle(self, val) -> None: ...
    @property
    def legendrank(self): ...
    @legendrank.setter
    def legendrank(self, val) -> None: ...
    @property
    def legendwidth(self): ...
    @legendwidth.setter
    def legendwidth(self, val) -> None: ...
    @property
    def marker(self): ...
    @marker.setter
    def marker(self, val) -> None: ...
    @property
    def meta(self): ...
    @meta.setter
    def meta(self, val) -> None: ...
    @property
    def metasrc(self): ...
    @metasrc.setter
    def metasrc(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def nbinsx(self): ...
    @nbinsx.setter
    def nbinsx(self, val) -> None: ...
    @property
    def nbinsy(self): ...
    @nbinsy.setter
    def nbinsy(self, val) -> None: ...
    @property
    def offsetgroup(self): ...
    @offsetgroup.setter
    def offsetgroup(self, val) -> None: ...
    @property
    def opacity(self): ...
    @opacity.setter
    def opacity(self, val) -> None: ...
    @property
    def orientation(self): ...
    @orientation.setter
    def orientation(self, val) -> None: ...
    @property
    def outsidetextfont(self): ...
    @outsidetextfont.setter
    def outsidetextfont(self, val) -> None: ...
    @property
    def selected(self): ...
    @selected.setter
    def selected(self, val) -> None: ...
    @property
    def selectedpoints(self): ...
    @selectedpoints.setter
    def selectedpoints(self, val) -> None: ...
    @property
    def showlegend(self): ...
    @showlegend.setter
    def showlegend(self, val) -> None: ...
    @property
    def stream(self): ...
    @stream.setter
    def stream(self, val) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, val) -> None: ...
    @property
    def textangle(self): ...
    @textangle.setter
    def textangle(self, val) -> None: ...
    @property
    def textfont(self): ...
    @textfont.setter
    def textfont(self, val) -> None: ...
    @property
    def textposition(self): ...
    @textposition.setter
    def textposition(self, val) -> None: ...
    @property
    def textsrc(self): ...
    @textsrc.setter
    def textsrc(self, val) -> None: ...
    @property
    def texttemplate(self): ...
    @texttemplate.setter
    def texttemplate(self, val) -> None: ...
    @property
    def uid(self): ...
    @uid.setter
    def uid(self, val) -> None: ...
    @property
    def uirevision(self): ...
    @uirevision.setter
    def uirevision(self, val) -> None: ...
    @property
    def unselected(self): ...
    @unselected.setter
    def unselected(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    @property
    def x(self): ...
    @x.setter
    def x(self, val) -> None: ...
    @property
    def xaxis(self): ...
    @xaxis.setter
    def xaxis(self, val) -> None: ...
    @property
    def xbins(self): ...
    @xbins.setter
    def xbins(self, val) -> None: ...
    @property
    def xcalendar(self): ...
    @xcalendar.setter
    def xcalendar(self, val) -> None: ...
    @property
    def xhoverformat(self): ...
    @xhoverformat.setter
    def xhoverformat(self, val) -> None: ...
    @property
    def xsrc(self): ...
    @xsrc.setter
    def xsrc(self, val) -> None: ...
    @property
    def y(self): ...
    @y.setter
    def y(self, val) -> None: ...
    @property
    def yaxis(self): ...
    @yaxis.setter
    def yaxis(self, val) -> None: ...
    @property
    def ybins(self): ...
    @ybins.setter
    def ybins(self, val) -> None: ...
    @property
    def ycalendar(self): ...
    @ycalendar.setter
    def ycalendar(self, val) -> None: ...
    @property
    def yhoverformat(self): ...
    @yhoverformat.setter
    def yhoverformat(self, val) -> None: ...
    @property
    def ysrc(self): ...
    @ysrc.setter
    def ysrc(self, val) -> None: ...
    @property
    def type(self): ...
    def __init__(
        self,
        arg: Any | None = ...,
        alignmentgroup: Any | None = ...,
        autobinx: Any | None = ...,
        autobiny: Any | None = ...,
        bingroup: Any | None = ...,
        cliponaxis: Any | None = ...,
        constraintext: Any | None = ...,
        cumulative: Any | None = ...,
        customdata: Any | None = ...,
        customdatasrc: Any | None = ...,
        error_x: Any | None = ...,
        error_y: Any | None = ...,
        histfunc: Any | None = ...,
        histnorm: Any | None = ...,
        hoverinfo: Any | None = ...,
        hoverinfosrc: Any | None = ...,
        hoverlabel: Any | None = ...,
        hovertemplate: Any | None = ...,
        hovertemplatesrc: Any | None = ...,
        hovertext: Any | None = ...,
        hovertextsrc: Any | None = ...,
        ids: Any | None = ...,
        idssrc: Any | None = ...,
        insidetextanchor: Any | None = ...,
        insidetextfont: Any | None = ...,
        legend: Any | None = ...,
        legendgroup: Any | None = ...,
        legendgrouptitle: Any | None = ...,
        legendrank: Any | None = ...,
        legendwidth: Any | None = ...,
        marker: Any | None = ...,
        meta: Any | None = ...,
        metasrc: Any | None = ...,
        name: Any | None = ...,
        nbinsx: Any | None = ...,
        nbinsy: Any | None = ...,
        offsetgroup: Any | None = ...,
        opacity: Any | None = ...,
        orientation: Any | None = ...,
        outsidetextfont: Any | None = ...,
        selected: Any | None = ...,
        selectedpoints: Any | None = ...,
        showlegend: Any | None = ...,
        stream: Any | None = ...,
        text: Any | None = ...,
        textangle: Any | None = ...,
        textfont: Any | None = ...,
        textposition: Any | None = ...,
        textsrc: Any | None = ...,
        texttemplate: Any | None = ...,
        uid: Any | None = ...,
        uirevision: Any | None = ...,
        unselected: Any | None = ...,
        visible: Any | None = ...,
        x: Any | None = ...,
        xaxis: Any | None = ...,
        xbins: Any | None = ...,
        xcalendar: Any | None = ...,
        xhoverformat: Any | None = ...,
        xsrc: Any | None = ...,
        y: Any | None = ...,
        yaxis: Any | None = ...,
        ybins: Any | None = ...,
        ycalendar: Any | None = ...,
        yhoverformat: Any | None = ...,
        ysrc: Any | None = ...,
        **kwargs
    ) -> None: ...
