from plotly.basedatatypes import BaseLayoutType as _BaseLayoutType
from typing import Any

class Layout(_BaseLayoutType):
    @property
    def activeselection(self): ...
    @activeselection.setter
    def activeselection(self, val) -> None: ...
    @property
    def activeshape(self): ...
    @activeshape.setter
    def activeshape(self, val) -> None: ...
    @property
    def annotations(self): ...
    @annotations.setter
    def annotations(self, val) -> None: ...
    @property
    def annotationdefaults(self): ...
    @annotationdefaults.setter
    def annotationdefaults(self, val) -> None: ...
    @property
    def autosize(self): ...
    @autosize.setter
    def autosize(self, val) -> None: ...
    @property
    def autotypenumbers(self): ...
    @autotypenumbers.setter
    def autotypenumbers(self, val) -> None: ...
    @property
    def bargap(self): ...
    @bargap.setter
    def bargap(self, val) -> None: ...
    @property
    def bargroupgap(self): ...
    @bargroupgap.setter
    def bargroupgap(self, val) -> None: ...
    @property
    def barmode(self): ...
    @barmode.setter
    def barmode(self, val) -> None: ...
    @property
    def barnorm(self): ...
    @barnorm.setter
    def barnorm(self, val) -> None: ...
    @property
    def boxgap(self): ...
    @boxgap.setter
    def boxgap(self, val) -> None: ...
    @property
    def boxgroupgap(self): ...
    @boxgroupgap.setter
    def boxgroupgap(self, val) -> None: ...
    @property
    def boxmode(self): ...
    @boxmode.setter
    def boxmode(self, val) -> None: ...
    @property
    def calendar(self): ...
    @calendar.setter
    def calendar(self, val) -> None: ...
    @property
    def clickmode(self): ...
    @clickmode.setter
    def clickmode(self, val) -> None: ...
    @property
    def coloraxis(self): ...
    @coloraxis.setter
    def coloraxis(self, val) -> None: ...
    @property
    def colorscale(self): ...
    @colorscale.setter
    def colorscale(self, val) -> None: ...
    @property
    def colorway(self): ...
    @colorway.setter
    def colorway(self, val) -> None: ...
    @property
    def computed(self): ...
    @computed.setter
    def computed(self, val) -> None: ...
    @property
    def datarevision(self): ...
    @datarevision.setter
    def datarevision(self, val) -> None: ...
    @property
    def dragmode(self): ...
    @dragmode.setter
    def dragmode(self, val) -> None: ...
    @property
    def editrevision(self): ...
    @editrevision.setter
    def editrevision(self, val) -> None: ...
    @property
    def extendfunnelareacolors(self): ...
    @extendfunnelareacolors.setter
    def extendfunnelareacolors(self, val) -> None: ...
    @property
    def extendiciclecolors(self): ...
    @extendiciclecolors.setter
    def extendiciclecolors(self, val) -> None: ...
    @property
    def extendpiecolors(self): ...
    @extendpiecolors.setter
    def extendpiecolors(self, val) -> None: ...
    @property
    def extendsunburstcolors(self): ...
    @extendsunburstcolors.setter
    def extendsunburstcolors(self, val) -> None: ...
    @property
    def extendtreemapcolors(self): ...
    @extendtreemapcolors.setter
    def extendtreemapcolors(self, val) -> None: ...
    @property
    def font(self): ...
    @font.setter
    def font(self, val) -> None: ...
    @property
    def funnelareacolorway(self): ...
    @funnelareacolorway.setter
    def funnelareacolorway(self, val) -> None: ...
    @property
    def funnelgap(self): ...
    @funnelgap.setter
    def funnelgap(self, val) -> None: ...
    @property
    def funnelgroupgap(self): ...
    @funnelgroupgap.setter
    def funnelgroupgap(self, val) -> None: ...
    @property
    def funnelmode(self): ...
    @funnelmode.setter
    def funnelmode(self, val) -> None: ...
    @property
    def geo(self): ...
    @geo.setter
    def geo(self, val) -> None: ...
    @property
    def grid(self): ...
    @grid.setter
    def grid(self, val) -> None: ...
    @property
    def height(self): ...
    @height.setter
    def height(self, val) -> None: ...
    @property
    def hiddenlabels(self): ...
    @hiddenlabels.setter
    def hiddenlabels(self, val) -> None: ...
    @property
    def hiddenlabelssrc(self): ...
    @hiddenlabelssrc.setter
    def hiddenlabelssrc(self, val) -> None: ...
    @property
    def hidesources(self): ...
    @hidesources.setter
    def hidesources(self, val) -> None: ...
    @property
    def hoverdistance(self): ...
    @hoverdistance.setter
    def hoverdistance(self, val) -> None: ...
    @property
    def hoverlabel(self): ...
    @hoverlabel.setter
    def hoverlabel(self, val) -> None: ...
    @property
    def hovermode(self): ...
    @hovermode.setter
    def hovermode(self, val) -> None: ...
    @property
    def iciclecolorway(self): ...
    @iciclecolorway.setter
    def iciclecolorway(self, val) -> None: ...
    @property
    def images(self): ...
    @images.setter
    def images(self, val) -> None: ...
    @property
    def imagedefaults(self): ...
    @imagedefaults.setter
    def imagedefaults(self, val) -> None: ...
    @property
    def legend(self): ...
    @legend.setter
    def legend(self, val) -> None: ...
    @property
    def mapbox(self): ...
    @mapbox.setter
    def mapbox(self, val) -> None: ...
    @property
    def margin(self): ...
    @margin.setter
    def margin(self, val) -> None: ...
    @property
    def meta(self): ...
    @meta.setter
    def meta(self, val) -> None: ...
    @property
    def metasrc(self): ...
    @metasrc.setter
    def metasrc(self, val) -> None: ...
    @property
    def minreducedheight(self): ...
    @minreducedheight.setter
    def minreducedheight(self, val) -> None: ...
    @property
    def minreducedwidth(self): ...
    @minreducedwidth.setter
    def minreducedwidth(self, val) -> None: ...
    @property
    def modebar(self): ...
    @modebar.setter
    def modebar(self, val) -> None: ...
    @property
    def newselection(self): ...
    @newselection.setter
    def newselection(self, val) -> None: ...
    @property
    def newshape(self): ...
    @newshape.setter
    def newshape(self, val) -> None: ...
    @property
    def paper_bgcolor(self): ...
    @paper_bgcolor.setter
    def paper_bgcolor(self, val) -> None: ...
    @property
    def piecolorway(self): ...
    @piecolorway.setter
    def piecolorway(self, val) -> None: ...
    @property
    def plot_bgcolor(self): ...
    @plot_bgcolor.setter
    def plot_bgcolor(self, val) -> None: ...
    @property
    def polar(self): ...
    @polar.setter
    def polar(self, val) -> None: ...
    @property
    def scattergap(self): ...
    @scattergap.setter
    def scattergap(self, val) -> None: ...
    @property
    def scattermode(self): ...
    @scattermode.setter
    def scattermode(self, val) -> None: ...
    @property
    def scene(self): ...
    @scene.setter
    def scene(self, val) -> None: ...
    @property
    def selectdirection(self): ...
    @selectdirection.setter
    def selectdirection(self, val) -> None: ...
    @property
    def selectionrevision(self): ...
    @selectionrevision.setter
    def selectionrevision(self, val) -> None: ...
    @property
    def selections(self): ...
    @selections.setter
    def selections(self, val) -> None: ...
    @property
    def selectiondefaults(self): ...
    @selectiondefaults.setter
    def selectiondefaults(self, val) -> None: ...
    @property
    def separators(self): ...
    @separators.setter
    def separators(self, val) -> None: ...
    @property
    def shapes(self): ...
    @shapes.setter
    def shapes(self, val) -> None: ...
    @property
    def shapedefaults(self): ...
    @shapedefaults.setter
    def shapedefaults(self, val) -> None: ...
    @property
    def showlegend(self): ...
    @showlegend.setter
    def showlegend(self, val) -> None: ...
    @property
    def sliders(self): ...
    @sliders.setter
    def sliders(self, val) -> None: ...
    @property
    def sliderdefaults(self): ...
    @sliderdefaults.setter
    def sliderdefaults(self, val) -> None: ...
    @property
    def smith(self): ...
    @smith.setter
    def smith(self, val) -> None: ...
    @property
    def spikedistance(self): ...
    @spikedistance.setter
    def spikedistance(self, val) -> None: ...
    @property
    def sunburstcolorway(self): ...
    @sunburstcolorway.setter
    def sunburstcolorway(self, val) -> None: ...
    @property
    def template(self): ...
    @template.setter
    def template(self, val) -> None: ...
    @property
    def ternary(self): ...
    @ternary.setter
    def ternary(self, val) -> None: ...
    @property
    def title(self): ...
    @title.setter
    def title(self, val) -> None: ...
    @property
    def titlefont(self): ...
    @titlefont.setter
    def titlefont(self, val) -> None: ...
    @property
    def transition(self): ...
    @transition.setter
    def transition(self, val) -> None: ...
    @property
    def treemapcolorway(self): ...
    @treemapcolorway.setter
    def treemapcolorway(self, val) -> None: ...
    @property
    def uirevision(self): ...
    @uirevision.setter
    def uirevision(self, val) -> None: ...
    @property
    def uniformtext(self): ...
    @uniformtext.setter
    def uniformtext(self, val) -> None: ...
    @property
    def updatemenus(self): ...
    @updatemenus.setter
    def updatemenus(self, val) -> None: ...
    @property
    def updatemenudefaults(self): ...
    @updatemenudefaults.setter
    def updatemenudefaults(self, val) -> None: ...
    @property
    def violingap(self): ...
    @violingap.setter
    def violingap(self, val) -> None: ...
    @property
    def violingroupgap(self): ...
    @violingroupgap.setter
    def violingroupgap(self, val) -> None: ...
    @property
    def violinmode(self): ...
    @violinmode.setter
    def violinmode(self, val) -> None: ...
    @property
    def waterfallgap(self): ...
    @waterfallgap.setter
    def waterfallgap(self, val) -> None: ...
    @property
    def waterfallgroupgap(self): ...
    @waterfallgroupgap.setter
    def waterfallgroupgap(self, val) -> None: ...
    @property
    def waterfallmode(self): ...
    @waterfallmode.setter
    def waterfallmode(self, val) -> None: ...
    @property
    def width(self): ...
    @width.setter
    def width(self, val) -> None: ...
    @property
    def xaxis(self): ...
    @xaxis.setter
    def xaxis(self, val) -> None: ...
    @property
    def yaxis(self): ...
    @yaxis.setter
    def yaxis(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        activeselection: Any | None = ...,
        activeshape: Any | None = ...,
        annotations: Any | None = ...,
        annotationdefaults: Any | None = ...,
        autosize: Any | None = ...,
        autotypenumbers: Any | None = ...,
        bargap: Any | None = ...,
        bargroupgap: Any | None = ...,
        barmode: Any | None = ...,
        barnorm: Any | None = ...,
        boxgap: Any | None = ...,
        boxgroupgap: Any | None = ...,
        boxmode: Any | None = ...,
        calendar: Any | None = ...,
        clickmode: Any | None = ...,
        coloraxis: Any | None = ...,
        colorscale: Any | None = ...,
        colorway: Any | None = ...,
        computed: Any | None = ...,
        datarevision: Any | None = ...,
        dragmode: Any | None = ...,
        editrevision: Any | None = ...,
        extendfunnelareacolors: Any | None = ...,
        extendiciclecolors: Any | None = ...,
        extendpiecolors: Any | None = ...,
        extendsunburstcolors: Any | None = ...,
        extendtreemapcolors: Any | None = ...,
        font: Any | None = ...,
        funnelareacolorway: Any | None = ...,
        funnelgap: Any | None = ...,
        funnelgroupgap: Any | None = ...,
        funnelmode: Any | None = ...,
        geo: Any | None = ...,
        grid: Any | None = ...,
        height: Any | None = ...,
        hiddenlabels: Any | None = ...,
        hiddenlabelssrc: Any | None = ...,
        hidesources: Any | None = ...,
        hoverdistance: Any | None = ...,
        hoverlabel: Any | None = ...,
        hovermode: Any | None = ...,
        iciclecolorway: Any | None = ...,
        images: Any | None = ...,
        imagedefaults: Any | None = ...,
        legend: Any | None = ...,
        mapbox: Any | None = ...,
        margin: Any | None = ...,
        meta: Any | None = ...,
        metasrc: Any | None = ...,
        minreducedheight: Any | None = ...,
        minreducedwidth: Any | None = ...,
        modebar: Any | None = ...,
        newselection: Any | None = ...,
        newshape: Any | None = ...,
        paper_bgcolor: Any | None = ...,
        piecolorway: Any | None = ...,
        plot_bgcolor: Any | None = ...,
        polar: Any | None = ...,
        scattergap: Any | None = ...,
        scattermode: Any | None = ...,
        scene: Any | None = ...,
        selectdirection: Any | None = ...,
        selectionrevision: Any | None = ...,
        selections: Any | None = ...,
        selectiondefaults: Any | None = ...,
        separators: Any | None = ...,
        shapes: Any | None = ...,
        shapedefaults: Any | None = ...,
        showlegend: Any | None = ...,
        sliders: Any | None = ...,
        sliderdefaults: Any | None = ...,
        smith: Any | None = ...,
        spikedistance: Any | None = ...,
        sunburstcolorway: Any | None = ...,
        template: Any | None = ...,
        ternary: Any | None = ...,
        title: Any | None = ...,
        titlefont: Any | None = ...,
        transition: Any | None = ...,
        treemapcolorway: Any | None = ...,
        uirevision: Any | None = ...,
        uniformtext: Any | None = ...,
        updatemenus: Any | None = ...,
        updatemenudefaults: Any | None = ...,
        violingap: Any | None = ...,
        violingroupgap: Any | None = ...,
        violinmode: Any | None = ...,
        waterfallgap: Any | None = ...,
        waterfallgroupgap: Any | None = ...,
        waterfallmode: Any | None = ...,
        width: Any | None = ...,
        xaxis: Any | None = ...,
        yaxis: Any | None = ...,
        **kwargs
    ) -> None: ...
