from plotly.basedatatypes import BaseTraceType as _BaseTraceType
from typing import Any

class Mesh3d(_BaseTraceType):
    @property
    def alphahull(self): ...
    @alphahull.setter
    def alphahull(self, val) -> None: ...
    @property
    def autocolorscale(self): ...
    @autocolorscale.setter
    def autocolorscale(self, val) -> None: ...
    @property
    def cauto(self): ...
    @cauto.setter
    def cauto(self, val) -> None: ...
    @property
    def cmax(self): ...
    @cmax.setter
    def cmax(self, val) -> None: ...
    @property
    def cmid(self): ...
    @cmid.setter
    def cmid(self, val) -> None: ...
    @property
    def cmin(self): ...
    @cmin.setter
    def cmin(self, val) -> None: ...
    @property
    def color(self): ...
    @color.setter
    def color(self, val) -> None: ...
    @property
    def coloraxis(self): ...
    @coloraxis.setter
    def coloraxis(self, val) -> None: ...
    @property
    def colorbar(self): ...
    @colorbar.setter
    def colorbar(self, val) -> None: ...
    @property
    def colorscale(self): ...
    @colorscale.setter
    def colorscale(self, val) -> None: ...
    @property
    def contour(self): ...
    @contour.setter
    def contour(self, val) -> None: ...
    @property
    def customdata(self): ...
    @customdata.setter
    def customdata(self, val) -> None: ...
    @property
    def customdatasrc(self): ...
    @customdatasrc.setter
    def customdatasrc(self, val) -> None: ...
    @property
    def delaunayaxis(self): ...
    @delaunayaxis.setter
    def delaunayaxis(self, val) -> None: ...
    @property
    def facecolor(self): ...
    @facecolor.setter
    def facecolor(self, val) -> None: ...
    @property
    def facecolorsrc(self): ...
    @facecolorsrc.setter
    def facecolorsrc(self, val) -> None: ...
    @property
    def flatshading(self): ...
    @flatshading.setter
    def flatshading(self, val) -> None: ...
    @property
    def hoverinfo(self): ...
    @hoverinfo.setter
    def hoverinfo(self, val) -> None: ...
    @property
    def hoverinfosrc(self): ...
    @hoverinfosrc.setter
    def hoverinfosrc(self, val) -> None: ...
    @property
    def hoverlabel(self): ...
    @hoverlabel.setter
    def hoverlabel(self, val) -> None: ...
    @property
    def hovertemplate(self): ...
    @hovertemplate.setter
    def hovertemplate(self, val) -> None: ...
    @property
    def hovertemplatesrc(self): ...
    @hovertemplatesrc.setter
    def hovertemplatesrc(self, val) -> None: ...
    @property
    def hovertext(self): ...
    @hovertext.setter
    def hovertext(self, val) -> None: ...
    @property
    def hovertextsrc(self): ...
    @hovertextsrc.setter
    def hovertextsrc(self, val) -> None: ...
    @property
    def i(self): ...
    @i.setter
    def i(self, val) -> None: ...
    @property
    def ids(self): ...
    @ids.setter
    def ids(self, val) -> None: ...
    @property
    def idssrc(self): ...
    @idssrc.setter
    def idssrc(self, val) -> None: ...
    @property
    def intensity(self): ...
    @intensity.setter
    def intensity(self, val) -> None: ...
    @property
    def intensitymode(self): ...
    @intensitymode.setter
    def intensitymode(self, val) -> None: ...
    @property
    def intensitysrc(self): ...
    @intensitysrc.setter
    def intensitysrc(self, val) -> None: ...
    @property
    def isrc(self): ...
    @isrc.setter
    def isrc(self, val) -> None: ...
    @property
    def j(self): ...
    @j.setter
    def j(self, val) -> None: ...
    @property
    def jsrc(self): ...
    @jsrc.setter
    def jsrc(self, val) -> None: ...
    @property
    def k(self): ...
    @k.setter
    def k(self, val) -> None: ...
    @property
    def ksrc(self): ...
    @ksrc.setter
    def ksrc(self, val) -> None: ...
    @property
    def legend(self): ...
    @legend.setter
    def legend(self, val) -> None: ...
    @property
    def legendgroup(self): ...
    @legendgroup.setter
    def legendgroup(self, val) -> None: ...
    @property
    def legendgrouptitle(self): ...
    @legendgrouptitle.setter
    def legendgrouptitle(self, val) -> None: ...
    @property
    def legendrank(self): ...
    @legendrank.setter
    def legendrank(self, val) -> None: ...
    @property
    def legendwidth(self): ...
    @legendwidth.setter
    def legendwidth(self, val) -> None: ...
    @property
    def lighting(self): ...
    @lighting.setter
    def lighting(self, val) -> None: ...
    @property
    def lightposition(self): ...
    @lightposition.setter
    def lightposition(self, val) -> None: ...
    @property
    def meta(self): ...
    @meta.setter
    def meta(self, val) -> None: ...
    @property
    def metasrc(self): ...
    @metasrc.setter
    def metasrc(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def opacity(self): ...
    @opacity.setter
    def opacity(self, val) -> None: ...
    @property
    def reversescale(self): ...
    @reversescale.setter
    def reversescale(self, val) -> None: ...
    @property
    def scene(self): ...
    @scene.setter
    def scene(self, val) -> None: ...
    @property
    def showlegend(self): ...
    @showlegend.setter
    def showlegend(self, val) -> None: ...
    @property
    def showscale(self): ...
    @showscale.setter
    def showscale(self, val) -> None: ...
    @property
    def stream(self): ...
    @stream.setter
    def stream(self, val) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, val) -> None: ...
    @property
    def textsrc(self): ...
    @textsrc.setter
    def textsrc(self, val) -> None: ...
    @property
    def uid(self): ...
    @uid.setter
    def uid(self, val) -> None: ...
    @property
    def uirevision(self): ...
    @uirevision.setter
    def uirevision(self, val) -> None: ...
    @property
    def vertexcolor(self): ...
    @vertexcolor.setter
    def vertexcolor(self, val) -> None: ...
    @property
    def vertexcolorsrc(self): ...
    @vertexcolorsrc.setter
    def vertexcolorsrc(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    @property
    def x(self): ...
    @x.setter
    def x(self, val) -> None: ...
    @property
    def xcalendar(self): ...
    @xcalendar.setter
    def xcalendar(self, val) -> None: ...
    @property
    def xhoverformat(self): ...
    @xhoverformat.setter
    def xhoverformat(self, val) -> None: ...
    @property
    def xsrc(self): ...
    @xsrc.setter
    def xsrc(self, val) -> None: ...
    @property
    def y(self): ...
    @y.setter
    def y(self, val) -> None: ...
    @property
    def ycalendar(self): ...
    @ycalendar.setter
    def ycalendar(self, val) -> None: ...
    @property
    def yhoverformat(self): ...
    @yhoverformat.setter
    def yhoverformat(self, val) -> None: ...
    @property
    def ysrc(self): ...
    @ysrc.setter
    def ysrc(self, val) -> None: ...
    @property
    def z(self): ...
    @z.setter
    def z(self, val) -> None: ...
    @property
    def zcalendar(self): ...
    @zcalendar.setter
    def zcalendar(self, val) -> None: ...
    @property
    def zhoverformat(self): ...
    @zhoverformat.setter
    def zhoverformat(self, val) -> None: ...
    @property
    def zsrc(self): ...
    @zsrc.setter
    def zsrc(self, val) -> None: ...
    @property
    def type(self): ...
    def __init__(
        self,
        arg: Any | None = ...,
        alphahull: Any | None = ...,
        autocolorscale: Any | None = ...,
        cauto: Any | None = ...,
        cmax: Any | None = ...,
        cmid: Any | None = ...,
        cmin: Any | None = ...,
        color: Any | None = ...,
        coloraxis: Any | None = ...,
        colorbar: Any | None = ...,
        colorscale: Any | None = ...,
        contour: Any | None = ...,
        customdata: Any | None = ...,
        customdatasrc: Any | None = ...,
        delaunayaxis: Any | None = ...,
        facecolor: Any | None = ...,
        facecolorsrc: Any | None = ...,
        flatshading: Any | None = ...,
        hoverinfo: Any | None = ...,
        hoverinfosrc: Any | None = ...,
        hoverlabel: Any | None = ...,
        hovertemplate: Any | None = ...,
        hovertemplatesrc: Any | None = ...,
        hovertext: Any | None = ...,
        hovertextsrc: Any | None = ...,
        i: Any | None = ...,
        ids: Any | None = ...,
        idssrc: Any | None = ...,
        intensity: Any | None = ...,
        intensitymode: Any | None = ...,
        intensitysrc: Any | None = ...,
        isrc: Any | None = ...,
        j: Any | None = ...,
        jsrc: Any | None = ...,
        k: Any | None = ...,
        ksrc: Any | None = ...,
        legend: Any | None = ...,
        legendgroup: Any | None = ...,
        legendgrouptitle: Any | None = ...,
        legendrank: Any | None = ...,
        legendwidth: Any | None = ...,
        lighting: Any | None = ...,
        lightposition: Any | None = ...,
        meta: Any | None = ...,
        metasrc: Any | None = ...,
        name: Any | None = ...,
        opacity: Any | None = ...,
        reversescale: Any | None = ...,
        scene: Any | None = ...,
        showlegend: Any | None = ...,
        showscale: Any | None = ...,
        stream: Any | None = ...,
        text: Any | None = ...,
        textsrc: Any | None = ...,
        uid: Any | None = ...,
        uirevision: Any | None = ...,
        vertexcolor: Any | None = ...,
        vertexcolorsrc: Any | None = ...,
        visible: Any | None = ...,
        x: Any | None = ...,
        xcalendar: Any | None = ...,
        xhoverformat: Any | None = ...,
        xsrc: Any | None = ...,
        y: Any | None = ...,
        ycalendar: Any | None = ...,
        yhoverformat: Any | None = ...,
        ysrc: Any | None = ...,
        z: Any | None = ...,
        zcalendar: Any | None = ...,
        zhoverformat: Any | None = ...,
        zsrc: Any | None = ...,
        **kwargs
    ) -> None: ...
