from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Geo(_BaseLayoutHierarchyType):
    @property
    def bgcolor(self): ...
    @bgcolor.setter
    def bgcolor(self, val) -> None: ...
    @property
    def center(self): ...
    @center.setter
    def center(self, val) -> None: ...
    @property
    def coastlinecolor(self): ...
    @coastlinecolor.setter
    def coastlinecolor(self, val) -> None: ...
    @property
    def coastlinewidth(self): ...
    @coastlinewidth.setter
    def coastlinewidth(self, val) -> None: ...
    @property
    def countrycolor(self): ...
    @countrycolor.setter
    def countrycolor(self, val) -> None: ...
    @property
    def countrywidth(self): ...
    @countrywidth.setter
    def countrywidth(self, val) -> None: ...
    @property
    def domain(self): ...
    @domain.setter
    def domain(self, val) -> None: ...
    @property
    def fitbounds(self): ...
    @fitbounds.setter
    def fitbounds(self, val) -> None: ...
    @property
    def framecolor(self): ...
    @framecolor.setter
    def framecolor(self, val) -> None: ...
    @property
    def framewidth(self): ...
    @framewidth.setter
    def framewidth(self, val) -> None: ...
    @property
    def lakecolor(self): ...
    @lakecolor.setter
    def lakecolor(self, val) -> None: ...
    @property
    def landcolor(self): ...
    @landcolor.setter
    def landcolor(self, val) -> None: ...
    @property
    def lataxis(self): ...
    @lataxis.setter
    def lataxis(self, val) -> None: ...
    @property
    def lonaxis(self): ...
    @lonaxis.setter
    def lonaxis(self, val) -> None: ...
    @property
    def oceancolor(self): ...
    @oceancolor.setter
    def oceancolor(self, val) -> None: ...
    @property
    def projection(self): ...
    @projection.setter
    def projection(self, val) -> None: ...
    @property
    def resolution(self): ...
    @resolution.setter
    def resolution(self, val) -> None: ...
    @property
    def rivercolor(self): ...
    @rivercolor.setter
    def rivercolor(self, val) -> None: ...
    @property
    def riverwidth(self): ...
    @riverwidth.setter
    def riverwidth(self, val) -> None: ...
    @property
    def scope(self): ...
    @scope.setter
    def scope(self, val) -> None: ...
    @property
    def showcoastlines(self): ...
    @showcoastlines.setter
    def showcoastlines(self, val) -> None: ...
    @property
    def showcountries(self): ...
    @showcountries.setter
    def showcountries(self, val) -> None: ...
    @property
    def showframe(self): ...
    @showframe.setter
    def showframe(self, val) -> None: ...
    @property
    def showlakes(self): ...
    @showlakes.setter
    def showlakes(self, val) -> None: ...
    @property
    def showland(self): ...
    @showland.setter
    def showland(self, val) -> None: ...
    @property
    def showocean(self): ...
    @showocean.setter
    def showocean(self, val) -> None: ...
    @property
    def showrivers(self): ...
    @showrivers.setter
    def showrivers(self, val) -> None: ...
    @property
    def showsubunits(self): ...
    @showsubunits.setter
    def showsubunits(self, val) -> None: ...
    @property
    def subunitcolor(self): ...
    @subunitcolor.setter
    def subunitcolor(self, val) -> None: ...
    @property
    def subunitwidth(self): ...
    @subunitwidth.setter
    def subunitwidth(self, val) -> None: ...
    @property
    def uirevision(self): ...
    @uirevision.setter
    def uirevision(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        bgcolor: Any | None = ...,
        center: Any | None = ...,
        coastlinecolor: Any | None = ...,
        coastlinewidth: Any | None = ...,
        countrycolor: Any | None = ...,
        countrywidth: Any | None = ...,
        domain: Any | None = ...,
        fitbounds: Any | None = ...,
        framecolor: Any | None = ...,
        framewidth: Any | None = ...,
        lakecolor: Any | None = ...,
        landcolor: Any | None = ...,
        lataxis: Any | None = ...,
        lonaxis: Any | None = ...,
        oceancolor: Any | None = ...,
        projection: Any | None = ...,
        resolution: Any | None = ...,
        rivercolor: Any | None = ...,
        riverwidth: Any | None = ...,
        scope: Any | None = ...,
        showcoastlines: Any | None = ...,
        showcountries: Any | None = ...,
        showframe: Any | None = ...,
        showlakes: Any | None = ...,
        showland: Any | None = ...,
        showocean: Any | None = ...,
        showrivers: Any | None = ...,
        showsubunits: Any | None = ...,
        subunitcolor: Any | None = ...,
        subunitwidth: Any | None = ...,
        uirevision: Any | None = ...,
        visible: Any | None = ...,
        **kwargs
    ) -> None: ...
