from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Grid(_BaseLayoutHierarchyType):
    @property
    def columns(self): ...
    @columns.setter
    def columns(self, val) -> None: ...
    @property
    def domain(self): ...
    @domain.setter
    def domain(self, val) -> None: ...
    @property
    def pattern(self): ...
    @pattern.setter
    def pattern(self, val) -> None: ...
    @property
    def roworder(self): ...
    @roworder.setter
    def roworder(self, val) -> None: ...
    @property
    def rows(self): ...
    @rows.setter
    def rows(self, val) -> None: ...
    @property
    def subplots(self): ...
    @subplots.setter
    def subplots(self, val) -> None: ...
    @property
    def xaxes(self): ...
    @xaxes.setter
    def xaxes(self, val) -> None: ...
    @property
    def xgap(self): ...
    @xgap.setter
    def xgap(self, val) -> None: ...
    @property
    def xside(self): ...
    @xside.setter
    def xside(self, val) -> None: ...
    @property
    def yaxes(self): ...
    @yaxes.setter
    def yaxes(self, val) -> None: ...
    @property
    def ygap(self): ...
    @ygap.setter
    def ygap(self, val) -> None: ...
    @property
    def yside(self): ...
    @yside.setter
    def yside(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        columns: Any | None = ...,
        domain: Any | None = ...,
        pattern: Any | None = ...,
        roworder: Any | None = ...,
        rows: Any | None = ...,
        subplots: Any | None = ...,
        xaxes: Any | None = ...,
        xgap: Any | None = ...,
        xside: Any | None = ...,
        yaxes: Any | None = ...,
        ygap: Any | None = ...,
        yside: Any | None = ...,
        **kwargs
    ) -> None: ...
