from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Hoverlabel(_BaseLayoutHierarchyType):
    @property
    def align(self): ...
    @align.setter
    def align(self, val) -> None: ...
    @property
    def bgcolor(self): ...
    @bgcolor.setter
    def bgcolor(self, val) -> None: ...
    @property
    def bordercolor(self): ...
    @bordercolor.setter
    def bordercolor(self, val) -> None: ...
    @property
    def font(self): ...
    @font.setter
    def font(self, val) -> None: ...
    @property
    def grouptitlefont(self): ...
    @grouptitlefont.setter
    def grouptitlefont(self, val) -> None: ...
    @property
    def namelength(self): ...
    @namelength.setter
    def namelength(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        align: Any | None = ...,
        bgcolor: Any | None = ...,
        bordercolor: Any | None = ...,
        font: Any | None = ...,
        grouptitlefont: Any | None = ...,
        namelength: Any | None = ...,
        **kwargs
    ) -> None: ...
