from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Image(_BaseLayoutHierarchyType):
    @property
    def layer(self): ...
    @layer.setter
    def layer(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def opacity(self): ...
    @opacity.setter
    def opacity(self, val) -> None: ...
    @property
    def sizex(self): ...
    @sizex.setter
    def sizex(self, val) -> None: ...
    @property
    def sizey(self): ...
    @sizey.setter
    def sizey(self, val) -> None: ...
    @property
    def sizing(self): ...
    @sizing.setter
    def sizing(self, val) -> None: ...
    @property
    def source(self): ...
    @source.setter
    def source(self, val) -> None: ...
    @property
    def templateitemname(self): ...
    @templateitemname.setter
    def templateitemname(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    @property
    def x(self): ...
    @x.setter
    def x(self, val) -> None: ...
    @property
    def xanchor(self): ...
    @xanchor.setter
    def xanchor(self, val) -> None: ...
    @property
    def xref(self): ...
    @xref.setter
    def xref(self, val) -> None: ...
    @property
    def y(self): ...
    @y.setter
    def y(self, val) -> None: ...
    @property
    def yanchor(self): ...
    @yanchor.setter
    def yanchor(self, val) -> None: ...
    @property
    def yref(self): ...
    @yref.setter
    def yref(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        layer: Any | None = ...,
        name: Any | None = ...,
        opacity: Any | None = ...,
        sizex: Any | None = ...,
        sizey: Any | None = ...,
        sizing: Any | None = ...,
        source: Any | None = ...,
        templateitemname: Any | None = ...,
        visible: Any | None = ...,
        x: Any | None = ...,
        xanchor: Any | None = ...,
        xref: Any | None = ...,
        y: Any | None = ...,
        yanchor: Any | None = ...,
        yref: Any | None = ...,
        **kwargs
    ) -> None: ...
