from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Modebar(_BaseLayoutHierarchyType):
    @property
    def activecolor(self): ...
    @activecolor.setter
    def activecolor(self, val) -> None: ...
    @property
    def add(self): ...
    @add.setter
    def add(self, val) -> None: ...
    @property
    def addsrc(self): ...
    @addsrc.setter
    def addsrc(self, val) -> None: ...
    @property
    def bgcolor(self): ...
    @bgcolor.setter
    def bgcolor(self, val) -> None: ...
    @property
    def color(self): ...
    @color.setter
    def color(self, val) -> None: ...
    @property
    def orientation(self): ...
    @orientation.setter
    def orientation(self, val) -> None: ...
    @property
    def remove(self): ...
    @remove.setter
    def remove(self, val) -> None: ...
    @property
    def removesrc(self): ...
    @removesrc.setter
    def removesrc(self, val) -> None: ...
    @property
    def uirevision(self): ...
    @uirevision.setter
    def uirevision(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        activecolor: Any | None = ...,
        add: Any | None = ...,
        addsrc: Any | None = ...,
        bgcolor: Any | None = ...,
        color: Any | None = ...,
        orientation: Any | None = ...,
        remove: Any | None = ...,
        removesrc: Any | None = ...,
        uirevision: Any | None = ...,
        **kwargs
    ) -> None: ...
