from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Polar(_BaseLayoutHierarchyType):
    @property
    def angularaxis(self): ...
    @angularaxis.setter
    def angularaxis(self, val) -> None: ...
    @property
    def bargap(self): ...
    @bargap.setter
    def bargap(self, val) -> None: ...
    @property
    def barmode(self): ...
    @barmode.setter
    def barmode(self, val) -> None: ...
    @property
    def bgcolor(self): ...
    @bgcolor.setter
    def bgcolor(self, val) -> None: ...
    @property
    def domain(self): ...
    @domain.setter
    def domain(self, val) -> None: ...
    @property
    def gridshape(self): ...
    @gridshape.setter
    def gridshape(self, val) -> None: ...
    @property
    def hole(self): ...
    @hole.setter
    def hole(self, val) -> None: ...
    @property
    def radialaxis(self): ...
    @radialaxis.setter
    def radialaxis(self, val) -> None: ...
    @property
    def sector(self): ...
    @sector.setter
    def sector(self, val) -> None: ...
    @property
    def uirevision(self): ...
    @uirevision.setter
    def uirevision(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        angularaxis: Any | None = ...,
        bargap: Any | None = ...,
        barmode: Any | None = ...,
        bgcolor: Any | None = ...,
        domain: Any | None = ...,
        gridshape: Any | None = ...,
        hole: Any | None = ...,
        radialaxis: Any | None = ...,
        sector: Any | None = ...,
        uirevision: Any | None = ...,
        **kwargs
    ) -> None: ...
