from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Ternary(_BaseLayoutHierarchyType):
    @property
    def aaxis(self): ...
    @aaxis.setter
    def aaxis(self, val) -> None: ...
    @property
    def baxis(self): ...
    @baxis.setter
    def baxis(self, val) -> None: ...
    @property
    def bgcolor(self): ...
    @bgcolor.setter
    def bgcolor(self, val) -> None: ...
    @property
    def caxis(self): ...
    @caxis.setter
    def caxis(self, val) -> None: ...
    @property
    def domain(self): ...
    @domain.setter
    def domain(self, val) -> None: ...
    @property
    def sum(self): ...
    @sum.setter
    def sum(self, val) -> None: ...
    @property
    def uirevision(self): ...
    @uirevision.setter
    def uirevision(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        aaxis: Any | None = ...,
        baxis: Any | None = ...,
        bgcolor: Any | None = ...,
        caxis: Any | None = ...,
        domain: Any | None = ...,
        sum: Any | None = ...,
        uirevision: Any | None = ...,
        **kwargs
    ) -> None: ...
