from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Updatemenu(_BaseLayoutHierarchyType):
    @property
    def active(self): ...
    @active.setter
    def active(self, val) -> None: ...
    @property
    def bgcolor(self): ...
    @bgcolor.setter
    def bgcolor(self, val) -> None: ...
    @property
    def bordercolor(self): ...
    @bordercolor.setter
    def bordercolor(self, val) -> None: ...
    @property
    def borderwidth(self): ...
    @borderwidth.setter
    def borderwidth(self, val) -> None: ...
    @property
    def buttons(self): ...
    @buttons.setter
    def buttons(self, val) -> None: ...
    @property
    def buttondefaults(self): ...
    @buttondefaults.setter
    def buttondefaults(self, val) -> None: ...
    @property
    def direction(self): ...
    @direction.setter
    def direction(self, val) -> None: ...
    @property
    def font(self): ...
    @font.setter
    def font(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def pad(self): ...
    @pad.setter
    def pad(self, val) -> None: ...
    @property
    def showactive(self): ...
    @showactive.setter
    def showactive(self, val) -> None: ...
    @property
    def templateitemname(self): ...
    @templateitemname.setter
    def templateitemname(self, val) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    @property
    def x(self): ...
    @x.setter
    def x(self, val) -> None: ...
    @property
    def xanchor(self): ...
    @xanchor.setter
    def xanchor(self, val) -> None: ...
    @property
    def y(self): ...
    @y.setter
    def y(self, val) -> None: ...
    @property
    def yanchor(self): ...
    @yanchor.setter
    def yanchor(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        active: Any | None = ...,
        bgcolor: Any | None = ...,
        bordercolor: Any | None = ...,
        borderwidth: Any | None = ...,
        buttons: Any | None = ...,
        buttondefaults: Any | None = ...,
        direction: Any | None = ...,
        font: Any | None = ...,
        name: Any | None = ...,
        pad: Any | None = ...,
        showactive: Any | None = ...,
        templateitemname: Any | None = ...,
        type: Any | None = ...,
        visible: Any | None = ...,
        x: Any | None = ...,
        xanchor: Any | None = ...,
        y: Any | None = ...,
        yanchor: Any | None = ...,
        **kwargs
    ) -> None: ...
