from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Aaxis(_BaseTraceHierarchyType):
    @property
    def arraydtick(self): ...
    @arraydtick.setter
    def arraydtick(self, val) -> None: ...
    @property
    def arraytick0(self): ...
    @arraytick0.setter
    def arraytick0(self, val) -> None: ...
    @property
    def autorange(self): ...
    @autorange.setter
    def autorange(self, val) -> None: ...
    @property
    def autotypenumbers(self): ...
    @autotypenumbers.setter
    def autotypenumbers(self, val) -> None: ...
    @property
    def categoryarray(self): ...
    @categoryarray.setter
    def categoryarray(self, val) -> None: ...
    @property
    def categoryarraysrc(self): ...
    @categoryarraysrc.setter
    def categoryarraysrc(self, val) -> None: ...
    @property
    def categoryorder(self): ...
    @categoryorder.setter
    def categoryorder(self, val) -> None: ...
    @property
    def cheatertype(self): ...
    @cheatertype.setter
    def cheatertype(self, val) -> None: ...
    @property
    def color(self): ...
    @color.setter
    def color(self, val) -> None: ...
    @property
    def dtick(self): ...
    @dtick.setter
    def dtick(self, val) -> None: ...
    @property
    def endline(self): ...
    @endline.setter
    def endline(self, val) -> None: ...
    @property
    def endlinecolor(self): ...
    @endlinecolor.setter
    def endlinecolor(self, val) -> None: ...
    @property
    def endlinewidth(self): ...
    @endlinewidth.setter
    def endlinewidth(self, val) -> None: ...
    @property
    def exponentformat(self): ...
    @exponentformat.setter
    def exponentformat(self, val) -> None: ...
    @property
    def fixedrange(self): ...
    @fixedrange.setter
    def fixedrange(self, val) -> None: ...
    @property
    def gridcolor(self): ...
    @gridcolor.setter
    def gridcolor(self, val) -> None: ...
    @property
    def griddash(self): ...
    @griddash.setter
    def griddash(self, val) -> None: ...
    @property
    def gridwidth(self): ...
    @gridwidth.setter
    def gridwidth(self, val) -> None: ...
    @property
    def labelalias(self): ...
    @labelalias.setter
    def labelalias(self, val) -> None: ...
    @property
    def labelpadding(self): ...
    @labelpadding.setter
    def labelpadding(self, val) -> None: ...
    @property
    def labelprefix(self): ...
    @labelprefix.setter
    def labelprefix(self, val) -> None: ...
    @property
    def labelsuffix(self): ...
    @labelsuffix.setter
    def labelsuffix(self, val) -> None: ...
    @property
    def linecolor(self): ...
    @linecolor.setter
    def linecolor(self, val) -> None: ...
    @property
    def linewidth(self): ...
    @linewidth.setter
    def linewidth(self, val) -> None: ...
    @property
    def minexponent(self): ...
    @minexponent.setter
    def minexponent(self, val) -> None: ...
    @property
    def minorgridcolor(self): ...
    @minorgridcolor.setter
    def minorgridcolor(self, val) -> None: ...
    @property
    def minorgridcount(self): ...
    @minorgridcount.setter
    def minorgridcount(self, val) -> None: ...
    @property
    def minorgriddash(self): ...
    @minorgriddash.setter
    def minorgriddash(self, val) -> None: ...
    @property
    def minorgridwidth(self): ...
    @minorgridwidth.setter
    def minorgridwidth(self, val) -> None: ...
    @property
    def nticks(self): ...
    @nticks.setter
    def nticks(self, val) -> None: ...
    @property
    def range(self): ...
    @range.setter
    def range(self, val) -> None: ...
    @property
    def rangemode(self): ...
    @rangemode.setter
    def rangemode(self, val) -> None: ...
    @property
    def separatethousands(self): ...
    @separatethousands.setter
    def separatethousands(self, val) -> None: ...
    @property
    def showexponent(self): ...
    @showexponent.setter
    def showexponent(self, val) -> None: ...
    @property
    def showgrid(self): ...
    @showgrid.setter
    def showgrid(self, val) -> None: ...
    @property
    def showline(self): ...
    @showline.setter
    def showline(self, val) -> None: ...
    @property
    def showticklabels(self): ...
    @showticklabels.setter
    def showticklabels(self, val) -> None: ...
    @property
    def showtickprefix(self): ...
    @showtickprefix.setter
    def showtickprefix(self, val) -> None: ...
    @property
    def showticksuffix(self): ...
    @showticksuffix.setter
    def showticksuffix(self, val) -> None: ...
    @property
    def smoothing(self): ...
    @smoothing.setter
    def smoothing(self, val) -> None: ...
    @property
    def startline(self): ...
    @startline.setter
    def startline(self, val) -> None: ...
    @property
    def startlinecolor(self): ...
    @startlinecolor.setter
    def startlinecolor(self, val) -> None: ...
    @property
    def startlinewidth(self): ...
    @startlinewidth.setter
    def startlinewidth(self, val) -> None: ...
    @property
    def tick0(self): ...
    @tick0.setter
    def tick0(self, val) -> None: ...
    @property
    def tickangle(self): ...
    @tickangle.setter
    def tickangle(self, val) -> None: ...
    @property
    def tickfont(self): ...
    @tickfont.setter
    def tickfont(self, val) -> None: ...
    @property
    def tickformat(self): ...
    @tickformat.setter
    def tickformat(self, val) -> None: ...
    @property
    def tickformatstops(self): ...
    @tickformatstops.setter
    def tickformatstops(self, val) -> None: ...
    @property
    def tickformatstopdefaults(self): ...
    @tickformatstopdefaults.setter
    def tickformatstopdefaults(self, val) -> None: ...
    @property
    def tickmode(self): ...
    @tickmode.setter
    def tickmode(self, val) -> None: ...
    @property
    def tickprefix(self): ...
    @tickprefix.setter
    def tickprefix(self, val) -> None: ...
    @property
    def ticksuffix(self): ...
    @ticksuffix.setter
    def ticksuffix(self, val) -> None: ...
    @property
    def ticktext(self): ...
    @ticktext.setter
    def ticktext(self, val) -> None: ...
    @property
    def ticktextsrc(self): ...
    @ticktextsrc.setter
    def ticktextsrc(self, val) -> None: ...
    @property
    def tickvals(self): ...
    @tickvals.setter
    def tickvals(self, val) -> None: ...
    @property
    def tickvalssrc(self): ...
    @tickvalssrc.setter
    def tickvalssrc(self, val) -> None: ...
    @property
    def title(self): ...
    @title.setter
    def title(self, val) -> None: ...
    @property
    def titlefont(self): ...
    @titlefont.setter
    def titlefont(self, val) -> None: ...
    @property
    def titleoffset(self): ...
    @titleoffset.setter
    def titleoffset(self, val) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        arraydtick: Any | None = ...,
        arraytick0: Any | None = ...,
        autorange: Any | None = ...,
        autotypenumbers: Any | None = ...,
        categoryarray: Any | None = ...,
        categoryarraysrc: Any | None = ...,
        categoryorder: Any | None = ...,
        cheatertype: Any | None = ...,
        color: Any | None = ...,
        dtick: Any | None = ...,
        endline: Any | None = ...,
        endlinecolor: Any | None = ...,
        endlinewidth: Any | None = ...,
        exponentformat: Any | None = ...,
        fixedrange: Any | None = ...,
        gridcolor: Any | None = ...,
        griddash: Any | None = ...,
        gridwidth: Any | None = ...,
        labelalias: Any | None = ...,
        labelpadding: Any | None = ...,
        labelprefix: Any | None = ...,
        labelsuffix: Any | None = ...,
        linecolor: Any | None = ...,
        linewidth: Any | None = ...,
        minexponent: Any | None = ...,
        minorgridcolor: Any | None = ...,
        minorgridcount: Any | None = ...,
        minorgriddash: Any | None = ...,
        minorgridwidth: Any | None = ...,
        nticks: Any | None = ...,
        range: Any | None = ...,
        rangemode: Any | None = ...,
        separatethousands: Any | None = ...,
        showexponent: Any | None = ...,
        showgrid: Any | None = ...,
        showline: Any | None = ...,
        showticklabels: Any | None = ...,
        showtickprefix: Any | None = ...,
        showticksuffix: Any | None = ...,
        smoothing: Any | None = ...,
        startline: Any | None = ...,
        startlinecolor: Any | None = ...,
        startlinewidth: Any | None = ...,
        tick0: Any | None = ...,
        tickangle: Any | None = ...,
        tickfont: Any | None = ...,
        tickformat: Any | None = ...,
        tickformatstops: Any | None = ...,
        tickformatstopdefaults: Any | None = ...,
        tickmode: Any | None = ...,
        tickprefix: Any | None = ...,
        ticksuffix: Any | None = ...,
        ticktext: Any | None = ...,
        ticktextsrc: Any | None = ...,
        tickvals: Any | None = ...,
        tickvalssrc: Any | None = ...,
        title: Any | None = ...,
        titlefont: Any | None = ...,
        titleoffset: Any | None = ...,
        type: Any | None = ...,
        **kwargs
    ) -> None: ...
