from typing import Any, ClassVar

class MultinomialLogLoss32:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

class MultinomialLogLoss64:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _multinomial_grad_loss_all_samples(*args, **kwargs) -> Any: ...
def sag32(*args, **kwargs) -> Any: ...
def sag64(*args, **kwargs) -> Any: ...
