from typing import Any

LIBSVM_KERNEL_TYPES: list

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def cross_validation(*args, **kwargs) -> Any: ...
def decision_function(*args, **kwargs) -> Any: ...
def fit(*args, **kwargs) -> Any: ...
def predict(*args, **kwargs) -> Any: ...
def predict_proba(*args, **kwargs) -> Any: ...
def set_verbosity_wrap(*args, **kwargs) -> Any: ...
