from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def libsvm_sparse_decision_function(*args, **kwargs) -> Any: ...
def libsvm_sparse_predict(*args, **kwargs) -> Any: ...
def libsvm_sparse_predict_proba(*args, **kwargs) -> Any: ...
def libsvm_sparse_train(*args, **kwargs) -> Any: ...
def set_verbosity_wrap(*args, **kwargs) -> Any: ...
