from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Dimension(_BaseTraceHierarchyType):
    @property
    def categoryarray(self): ...
    @categoryarray.setter
    def categoryarray(self, val) -> None: ...
    @property
    def categoryarraysrc(self): ...
    @categoryarraysrc.setter
    def categoryarraysrc(self, val) -> None: ...
    @property
    def categoryorder(self): ...
    @categoryorder.setter
    def categoryorder(self, val) -> None: ...
    @property
    def displayindex(self): ...
    @displayindex.setter
    def displayindex(self, val) -> None: ...
    @property
    def label(self): ...
    @label.setter
    def label(self, val) -> None: ...
    @property
    def ticktext(self): ...
    @ticktext.setter
    def ticktext(self, val) -> None: ...
    @property
    def ticktextsrc(self): ...
    @ticktextsrc.setter
    def ticktextsrc(self, val) -> None: ...
    @property
    def values(self): ...
    @values.setter
    def values(self, val) -> None: ...
    @property
    def valuessrc(self): ...
    @valuessrc.setter
    def valuessrc(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        categoryarray: Any | None = ...,
        categoryarraysrc: Any | None = ...,
        categoryorder: Any | None = ...,
        displayindex: Any | None = ...,
        label: Any | None = ...,
        ticktext: Any | None = ...,
        ticktextsrc: Any | None = ...,
        values: Any | None = ...,
        valuessrc: Any | None = ...,
        visible: Any | None = ...,
        **kwargs
    ) -> None: ...
