version: '3'
services:
  py:
    container_name: py-predictables
    image: aaweaver9/py
    volumes:
      - ..:/app
      # - ../../hit-ratios/data:/data
    working_dir: /app
    environment:
      - PYTHONPATH=/app/.venv/bin/python
      - PYDEVD_DISABLE_FILE_VALIDATION=1
    command: "tail -f /dev/null"
