# This is the Dockerfile that defines my development environment 
# for predictables. It is based on the official Python 3.11 image
# and installs the required packages from the requirements.txt file.

# Use an official Python runtime as a parent image
FROM ubuntu:20.04

# Set the working directory in the container to root
WORKDIR /

# Add the current directory contents into the container at root
ADD . /

# Update the package list and install software
RUN apt-get update && apt-get install -y \
    bash \
    && apt-get clean


# # Create a virtual environment and activate it
# RUN python -m venv /venv
# ENV PATH="/venv/bin:$PATH"

# # Install any needed packages specified in requirements.txt to the virtual environment
# RUN pip install --upgrade pip
# RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Run bash when the container launches
CMD ["/bin/sh"]