from typing import Any

class UnsetMetadataPassedError(ValueError):
    unrequested_params: Any
    routed_params: Any
    def __init__(self, *, message, unrequested_params, routed_params) -> None: ...

class NotFittedError(ValueError, AttributeError): ...
class ConvergenceWarning(UserWarning): ...
class DataConversionWarning(UserWarning): ...
class DataDimensionalityWarning(UserWarning): ...
class EfficiencyWarning(UserWarning): ...
class FitFailedWarning(RuntimeWarning): ...
class SkipTestWarning(UserWarning): ...
class UndefinedMetricWarning(UserWarning): ...
class PositiveSpectrumWarning(UserWarning): ...

class InconsistentVersionWarning(UserWarning):
    estimator_name: Any
    current_sklearn_version: Any
    original_sklearn_version: Any
    def __init__(
        self, *, estimator_name, current_sklearn_version, original_sklearn_version
    ) -> None: ...
