from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Colorscale(_BaseTraceHierarchyType):
    @property
    def cmax(self): ...
    @cmax.setter
    def cmax(self, val) -> None: ...
    @property
    def cmin(self): ...
    @cmin.setter
    def cmin(self, val) -> None: ...
    @property
    def colorscale(self): ...
    @colorscale.setter
    def colorscale(self, val) -> None: ...
    @property
    def label(self): ...
    @label.setter
    def label(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def templateitemname(self): ...
    @templateitemname.setter
    def templateitemname(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        cmax: Any | None = ...,
        cmin: Any | None = ...,
        colorscale: Any | None = ...,
        label: Any | None = ...,
        name: Any | None = ...,
        templateitemname: Any | None = ...,
        **kwargs
    ) -> None: ...
