from typing import Any

issparse: function

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _predict_regression_tree_stages_sparse(*args, **kwargs) -> Any: ...
def _random_sample_mask(*args, **kwargs) -> Any: ...
def np_zeros(*args, **kwargs) -> Any: ...
def predict_stage(*args, **kwargs) -> Any: ...
def predict_stages(*args, **kwargs) -> Any: ...
