from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Minor(_BaseLayoutHierarchyType):
    @property
    def dtick(self): ...
    @dtick.setter
    def dtick(self, val) -> None: ...
    @property
    def gridcolor(self): ...
    @gridcolor.setter
    def gridcolor(self, val) -> None: ...
    @property
    def griddash(self): ...
    @griddash.setter
    def griddash(self, val) -> None: ...
    @property
    def gridwidth(self): ...
    @gridwidth.setter
    def gridwidth(self, val) -> None: ...
    @property
    def nticks(self): ...
    @nticks.setter
    def nticks(self, val) -> None: ...
    @property
    def showgrid(self): ...
    @showgrid.setter
    def showgrid(self, val) -> None: ...
    @property
    def tick0(self): ...
    @tick0.setter
    def tick0(self, val) -> None: ...
    @property
    def tickcolor(self): ...
    @tickcolor.setter
    def tickcolor(self, val) -> None: ...
    @property
    def ticklen(self): ...
    @ticklen.setter
    def ticklen(self, val) -> None: ...
    @property
    def tickmode(self): ...
    @tickmode.setter
    def tickmode(self, val) -> None: ...
    @property
    def ticks(self): ...
    @ticks.setter
    def ticks(self, val) -> None: ...
    @property
    def tickvals(self): ...
    @tickvals.setter
    def tickvals(self, val) -> None: ...
    @property
    def tickvalssrc(self): ...
    @tickvalssrc.setter
    def tickvalssrc(self, val) -> None: ...
    @property
    def tickwidth(self): ...
    @tickwidth.setter
    def tickwidth(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        dtick: Any | None = ...,
        gridcolor: Any | None = ...,
        griddash: Any | None = ...,
        gridwidth: Any | None = ...,
        nticks: Any | None = ...,
        showgrid: Any | None = ...,
        tick0: Any | None = ...,
        tickcolor: Any | None = ...,
        ticklen: Any | None = ...,
        tickmode: Any | None = ...,
        ticks: Any | None = ...,
        tickvals: Any | None = ...,
        tickvalssrc: Any | None = ...,
        tickwidth: Any | None = ...,
        **kwargs
    ) -> None: ...
