from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Rangeselector(_BaseLayoutHierarchyType):
    @property
    def activecolor(self): ...
    @activecolor.setter
    def activecolor(self, val) -> None: ...
    @property
    def bgcolor(self): ...
    @bgcolor.setter
    def bgcolor(self, val) -> None: ...
    @property
    def bordercolor(self): ...
    @bordercolor.setter
    def bordercolor(self, val) -> None: ...
    @property
    def borderwidth(self): ...
    @borderwidth.setter
    def borderwidth(self, val) -> None: ...
    @property
    def buttons(self): ...
    @buttons.setter
    def buttons(self, val) -> None: ...
    @property
    def buttondefaults(self): ...
    @buttondefaults.setter
    def buttondefaults(self, val) -> None: ...
    @property
    def font(self): ...
    @font.setter
    def font(self, val) -> None: ...
    @property
    def visible(self): ...
    @visible.setter
    def visible(self, val) -> None: ...
    @property
    def x(self): ...
    @x.setter
    def x(self, val) -> None: ...
    @property
    def xanchor(self): ...
    @xanchor.setter
    def xanchor(self, val) -> None: ...
    @property
    def y(self): ...
    @y.setter
    def y(self, val) -> None: ...
    @property
    def yanchor(self): ...
    @yanchor.setter
    def yanchor(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        activecolor: Any | None = ...,
        bgcolor: Any | None = ...,
        bordercolor: Any | None = ...,
        borderwidth: Any | None = ...,
        buttons: Any | None = ...,
        buttondefaults: Any | None = ...,
        font: Any | None = ...,
        visible: Any | None = ...,
        x: Any | None = ...,
        xanchor: Any | None = ...,
        y: Any | None = ...,
        yanchor: Any | None = ...,
        **kwargs
    ) -> None: ...
