from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Rangebreak(_BaseLayoutHierarchyType):
    @property
    def bounds(self): ...
    @bounds.setter
    def bounds(self, val) -> None: ...
    @property
    def dvalue(self): ...
    @dvalue.setter
    def dvalue(self, val) -> None: ...
    @property
    def enabled(self): ...
    @enabled.setter
    def enabled(self, val) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, val) -> None: ...
    @property
    def pattern(self): ...
    @pattern.setter
    def pattern(self, val) -> None: ...
    @property
    def templateitemname(self): ...
    @templateitemname.setter
    def templateitemname(self, val) -> None: ...
    @property
    def values(self): ...
    @values.setter
    def values(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        bounds: Any | None = ...,
        dvalue: Any | None = ...,
        enabled: Any | None = ...,
        name: Any | None = ...,
        pattern: Any | None = ...,
        templateitemname: Any | None = ...,
        values: Any | None = ...,
        **kwargs
    ) -> None: ...
