from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType
from typing import Any

class Symbol(_BaseLayoutHierarchyType):
    @property
    def icon(self): ...
    @icon.setter
    def icon(self, val) -> None: ...
    @property
    def iconsize(self): ...
    @iconsize.setter
    def iconsize(self, val) -> None: ...
    @property
    def placement(self): ...
    @placement.setter
    def placement(self, val) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, val) -> None: ...
    @property
    def textfont(self): ...
    @textfont.setter
    def textfont(self, val) -> None: ...
    @property
    def textposition(self): ...
    @textposition.setter
    def textposition(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        icon: Any | None = ...,
        iconsize: Any | None = ...,
        placement: Any | None = ...,
        text: Any | None = ...,
        textfont: Any | None = ...,
        textposition: Any | None = ...,
        **kwargs
    ) -> None: ...
