from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Font(_BaseTraceHierarchyType):
    @property
    def color(self): ...
    @color.setter
    def color(self, val) -> None: ...
    @property
    def colorsrc(self): ...
    @colorsrc.setter
    def colorsrc(self, val) -> None: ...
    @property
    def family(self): ...
    @family.setter
    def family(self, val) -> None: ...
    @property
    def familysrc(self): ...
    @familysrc.setter
    def familysrc(self, val) -> None: ...
    @property
    def size(self): ...
    @size.setter
    def size(self, val) -> None: ...
    @property
    def sizesrc(self): ...
    @sizesrc.setter
    def sizesrc(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        color: Any | None = ...,
        colorsrc: Any | None = ...,
        family: Any | None = ...,
        familysrc: Any | None = ...,
        size: Any | None = ...,
        sizesrc: Any | None = ...,
        **kwargs
    ) -> None: ...
