from typing import Any

import numpy.dtypes

HIERARCHY_dtype: numpy.dtypes.VoidDType
MST_edge_dtype: numpy.dtypes.VoidDType

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def make_single_linkage(*args, **kwargs) -> Any: ...
def mst_from_data_matrix(*args, **kwargs) -> Any: ...
def mst_from_mutual_reachability(*args, **kwargs) -> Any: ...
