from typing import Any, ClassVar

import numpy.dtypes

CONDENSED_dtype: numpy.dtypes.VoidDType
HIERARCHY_dtype: numpy.dtypes.VoidDType

class TreeUnionFind:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def __pyx_unpickle_TreeUnionFind(*args, **kwargs) -> Any: ...
def _condense_tree(*args, **kwargs) -> Any: ...
def _do_labelling(*args, **kwargs) -> Any: ...
def get_cluster_tree_leaves(*args, **kwargs) -> Any: ...
def labelling_at_cut(*args, **kwargs) -> Any: ...
def recurse_leaf_dfs(*args, **kwargs) -> Any: ...
def tree_to_labels(*args, **kwargs) -> Any: ...
