from typing import Any, ClassVar

import numpy.dtypes

CELL_DTYPE: numpy.dtypes.VoidDType

class _QuadTree:
    capacity: ClassVar[getset_descriptor] = ...
    cell_count: ClassVar[getset_descriptor] = ...
    cumulative_size: ClassVar[getset_descriptor] = ...
    leafs: ClassVar[getset_descriptor] = ...
    max_depth: ClassVar[getset_descriptor] = ...
    n_dimensions: ClassVar[getset_descriptor] = ...
    n_points: ClassVar[getset_descriptor] = ...
    verbose: ClassVar[getset_descriptor] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def _check_coherence(self, *args, **kwargs) -> Any: ...
    def _py_summarize(self, *args, **kwargs) -> Any: ...
    def build_tree(self, *args, **kwargs) -> Any: ...
    def get_cell(self, *args, **kwargs) -> Any: ...
    def __getstate__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
