from typing import Any

class CensoredData:
    def __init__(
        self,
        uncensored: Any | None = ...,
        *,
        left: Any | None = ...,
        right: Any | None = ...,
        interval: Any | None = ...
    ) -> None: ...
    def __sub__(self, other): ...
    def __truediv__(self, other): ...
    def __len__(self): ...
    def num_censored(self): ...
    @classmethod
    def right_censored(cls, x, censored): ...
    @classmethod
    def left_censored(cls, x, censored): ...
    @classmethod
    def interval_censored(cls, low, high): ...
