from typing import Any

def hdquantiles(data, prob=..., axis: Any | None = ..., var: bool = ...): ...
def hdmedian(data, axis: int = ..., var: bool = ...): ...
def hdquantiles_sd(data, prob=..., axis: Any | None = ...): ...
def trimmed_mean_ci(
    data, limits=..., inclusive=..., alpha: float = ..., axis: Any | None = ...
): ...
def mjci(data, prob=..., axis: Any | None = ...): ...
def mquantiles_cimj(data, prob=..., alpha: float = ..., axis: Any | None = ...): ...
def median_cihs(data, alpha: float = ..., axis: Any | None = ...): ...
def compare_medians_ms(group_1, group_2, axis: Any | None = ...): ...
def idealfourths(data, axis: Any | None = ...): ...
def rsh(data, points: Any | None = ...): ...
