from ._continuous_distns import norm as norm
from typing import Any

class PageTrendTestResult:
    statistic: float
    pvalue: float
    method: str

def page_trend_test(
    data, ranked: bool = ..., predicted_ranks: Any | None = ..., method: str = ...
): ...

class _PageL:
    all_pmfs: Any
    def __init__(self) -> None: ...
    k: Any
    def set_k(self, k) -> None: ...
    def sf(self, l, n): ...
    def p_l_k_1(self): ...
    def pmf(self, l, n): ...
