from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _cy_van_der_corput(*args, **kwargs) -> Any: ...
def _cy_van_der_corput_scrambled(*args, **kwargs) -> Any: ...
def _cy_wrapper_centered_discrepancy(*args, **kwargs) -> Any: ...
def _cy_wrapper_l2_star_discrepancy(*args, **kwargs) -> Any: ...
def _cy_wrapper_mixture_discrepancy(*args, **kwargs) -> Any: ...
def _cy_wrapper_update_discrepancy(*args, **kwargs) -> Any: ...
def _cy_wrapper_wrap_around_discrepancy(*args, **kwargs) -> Any: ...
