from scipy._lib._util import check_random_state as check_random_state
from typing import Any

def rvs_ratio_uniforms(
    pdf, umax, vmin, vmax, size: int = ..., c: int = ..., random_state: Any | None = ...
): ...
