from typing import Any

_MAXDEG: int
_MAXDIM: int
_cscramble: fused_cython_function
_draw: fused_cython_function
_fast_forward: fused_cython_function
_initialize_v: fused_cython_function
_poly_dict: dict
_vinit_dict: dict

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _categorize(*args, **kwargs) -> Any: ...
def _fill_p_cumulative(*args, **kwargs) -> Any: ...
def _initialize_direction_numbers(*args, **kwargs) -> Any: ...
def _test_find_index(*args, **kwargs) -> Any: ...
def get_poly_vinit(*args, **kwargs) -> Any: ...
