from typing import Any

_weightedrankedtau: fused_cython_function
gaussian_kernel_estimate: fused_cython_function
gaussian_kernel_estimate_log: fused_cython_function
solve_triangular: function

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _center_distance_matrix(*args, **kwargs) -> Any: ...
def _kendall_dis(*args, **kwargs) -> Any: ...
def _local_correlations(*args, **kwargs) -> Any: ...
def _local_covariance(*args, **kwargs) -> Any: ...
def _rank_distance_matrix(*args, **kwargs) -> Any: ...
def _studentized_range_cdf_logconst(*args, **kwargs) -> Any: ...
def _studentized_range_pdf_logconst(*args, **kwargs) -> Any: ...
def _toint64(*args, **kwargs) -> Any: ...
def _transform_distance_matrix(*args, **kwargs) -> Any: ...
def genhyperbolic_logpdf(*args, **kwargs) -> Any: ...
def genhyperbolic_pdf(*args, **kwargs) -> Any: ...
def geninvgauss_logpdf(*args, **kwargs) -> Any: ...
def von_mises_cdf(*args, **kwargs) -> Any: ...
