from typing import Any

def _Aij(*args, **kwargs) -> Any: ...
def _Dij(*args, **kwargs) -> Any: ...
def _a_ij_Aij_Dij2(*args, **kwargs) -> Any: ...
def _compute_outer_prob_inside_method(*args, **kwargs) -> Any: ...
def _concordant_pairs(*args, **kwargs) -> Any: ...
def _discordant_pairs(*args, **kwargs) -> Any: ...
def siegelslopes(*args, **kwargs) -> Any: ...
