from typing import Any

def linregress(x, y: Any | None = ..., alternative: str = ...): ...
def theilslopes(y, x: Any | None = ..., alpha: float = ..., method: str = ...): ...
def siegelslopes(y, x: Any | None = ..., method: str = ...): ...

# Names in __all__ with no definition:
#   _find_repeats
