from typing import Any, ClassVar

import scipy.sparse._csr
import scipy.sparse._matrix

issparse: function

class DenseDenseMiddleTermComputer32(MiddleTermComputer32):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class DenseDenseMiddleTermComputer64(MiddleTermComputer64):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class MiddleTermComputer32:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def get_for(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def unpack_csr_matrix(cls, *args, **kwargs) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class MiddleTermComputer64:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def get_for(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def unpack_csr_matrix(cls, *args, **kwargs) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class SparseDenseMiddleTermComputer32(MiddleTermComputer32):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class SparseDenseMiddleTermComputer64(MiddleTermComputer64):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class SparseSparseMiddleTermComputer32(MiddleTermComputer32):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class SparseSparseMiddleTermComputer64(MiddleTermComputer64):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class csr_matrix(scipy.sparse._matrix.spmatrix, scipy.sparse._csr._csr_base): ...

def __pyx_unpickle_DenseDenseMiddleTermComputer32(*args, **kwargs) -> Any: ...
def __pyx_unpickle_DenseDenseMiddleTermComputer64(*args, **kwargs) -> Any: ...
def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def __pyx_unpickle_MiddleTermComputer32(*args, **kwargs) -> Any: ...
def __pyx_unpickle_MiddleTermComputer64(*args, **kwargs) -> Any: ...
def __pyx_unpickle_SparseDenseMiddleTermComputer32(*args, **kwargs) -> Any: ...
def __pyx_unpickle_SparseDenseMiddleTermComputer64(*args, **kwargs) -> Any: ...
def __pyx_unpickle_SparseSparseMiddleTermComputer32(*args, **kwargs) -> Any: ...
def __pyx_unpickle_SparseSparseMiddleTermComputer64(*args, **kwargs) -> Any: ...
