from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Lighting(_BaseTraceHierarchyType):
    @property
    def ambient(self): ...
    @ambient.setter
    def ambient(self, val) -> None: ...
    @property
    def diffuse(self): ...
    @diffuse.setter
    def diffuse(self, val) -> None: ...
    @property
    def facenormalsepsilon(self): ...
    @facenormalsepsilon.setter
    def facenormalsepsilon(self, val) -> None: ...
    @property
    def fresnel(self): ...
    @fresnel.setter
    def fresnel(self, val) -> None: ...
    @property
    def roughness(self): ...
    @roughness.setter
    def roughness(self, val) -> None: ...
    @property
    def specular(self): ...
    @specular.setter
    def specular(self, val) -> None: ...
    @property
    def vertexnormalsepsilon(self): ...
    @vertexnormalsepsilon.setter
    def vertexnormalsepsilon(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        ambient: Any | None = ...,
        diffuse: Any | None = ...,
        facenormalsepsilon: Any | None = ...,
        fresnel: Any | None = ...,
        roughness: Any | None = ...,
        specular: Any | None = ...,
        vertexnormalsepsilon: Any | None = ...,
        **kwargs
    ) -> None: ...
