name: Create mypy report

env:
  REPO_NAME: ${{ github.repository }}
  REPORT_FOLDER: "mypy-report"
  PYTHON_VERSION: "3.11.8"
  CONFIG_FILE: ".mypy.ini"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install mypy
      - run: mypy --install-types --non-interactive
      - run: mypy --version
      - run: python -c "import mypy; print(mypy.__version__)"

  run-mypy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: |
          source .venv/bin/activate
          mypy --config-file ${{ env.CONFIG_FILE }} --html-report ${{ env.REPORT_FOLDER }} .
      - name: Upload mypy report
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.REPORT_FOLDER }}
          path: ${{ env.REPORT_FOLDER }}

  publish-mypy-report:
    runs-on: ubuntu-latest
    needs: run-mypy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.REPORT_FOLDER }}
          path: ${{ env.REPORT_FOLDER }}
      - name: Publish mypy report
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.REPORT_FOLDER }}
          path: ${{ env.REPORT_FOLDER }}