name: Create mypy report

env:
  REPO_NAME: ${{ github.repository }}
  REPORT_FOLDER: "mypy-report"
  PYTHON_VERSION: "3.11.8"
  CONFIG_FILE: ".mypy.ini"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  setup-run-publish-mypy-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install mypy
        run: python -m pip install mypy
      - name: Verify mypy installation
        run: mypy --version
      - name: Create virtual environment
        run: python -m venv .venv
      - name: Activate virtual environment
        run: source .venv/bin/activate
      - name: Install dependencies
        run: |
        pip install -r requirements.txt
        pip install mypy

      - name: Run mypy & generate report (even if there are errors -- we want to see these errors)
        run: |
        mkdir -p $HOME/report_output
        mypy --config-file ${{ env.CONFIG_FILE }} --xml-report $HOME/report_output/mypy_report.xml . || true

      - name: Upload mypy report
        uses: actions/upload-artifact@v4
        with:
          name: mypy-report
          path: $HOME/report_output/mypy_report.xml

      - name: Download and store the mypy report
        uses: actions/download-artifact@v2
        with:
          name: mypy-report
          path: $HOME/report_output/mypy_report.xml
       