from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from typing import Any

class Hoverlabel(_BaseTraceHierarchyType):
    @property
    def align(self): ...
    @align.setter
    def align(self, val) -> None: ...
    @property
    def alignsrc(self): ...
    @alignsrc.setter
    def alignsrc(self, val) -> None: ...
    @property
    def bgcolor(self): ...
    @bgcolor.setter
    def bgcolor(self, val) -> None: ...
    @property
    def bgcolorsrc(self): ...
    @bgcolorsrc.setter
    def bgcolorsrc(self, val) -> None: ...
    @property
    def bordercolor(self): ...
    @bordercolor.setter
    def bordercolor(self, val) -> None: ...
    @property
    def bordercolorsrc(self): ...
    @bordercolorsrc.setter
    def bordercolorsrc(self, val) -> None: ...
    @property
    def font(self): ...
    @font.setter
    def font(self, val) -> None: ...
    @property
    def namelength(self): ...
    @namelength.setter
    def namelength(self, val) -> None: ...
    @property
    def namelengthsrc(self): ...
    @namelengthsrc.setter
    def namelengthsrc(self, val) -> None: ...
    def __init__(
        self,
        arg: Any | None = ...,
        align: Any | None = ...,
        alignsrc: Any | None = ...,
        bgcolor: Any | None = ...,
        bgcolorsrc: Any | None = ...,
        bordercolor: Any | None = ...,
        bordercolorsrc: Any | None = ...,
        font: Any | None = ...,
        namelength: Any | None = ...,
        namelengthsrc: Any | None = ...,
        **kwargs
    ) -> None: ...
